### ISSUE TITLE
Offhours/Onhours may always go to default?

### ISSUE THREAD

**Issue by fdosani** [capitalone/cloud-custodian#100]
@kapilt just hoping to confirm the logic here. Was tracing through the offhours module in paticular:
```
class OffHour(Time):

    def get_sentinel_time(self, tz):
        t = super(OffHour, self).get_sentinel_time(tz)
        return t.replace(hour=self.data.get('offhour', DEFAULT_OFFHOUR))


class OnHour(Time):

    def get_sentinel_time(self, tz):
        t = super(OnHour, self).get_sentinel_time(tz)
        return t.replace(hour=self.data.get('onhour', DEFAULT_ONHOUR))
```
Executing the following policy:
```
  - name: onhour-start-10
    resource: ec2
    comments: |
      Daily start at 10am
    filters:
      - type: onhour
        tag: c7n_downtime
        hour: 10
    actions:
      - start
```

I'm printing `self.data` and get the following: `{'tag': 'c7n_downtime', 'type': 'onhour', 'hour': 10}`
Seems like `get_sentinel_time` of the child classes will always return the default regardless of whats in the policy due to the key being `type` in this situation. Does this seem right? I'm assuming not the behaviour we'd want.

logger output:  `comparing sentinel: 2016-05-10 07:00:00-04:00 to current: 2016-05-10 21:00:00-04:00`

Thanks,
Faisal
