### ISSUE TITLE
ec2 instances with unencrypted root ebs volumes

### ISSUE THREAD

**Issue by abhilash14j** [capitalone/cloud-custodian#1002]
I am looking to filter out ec2 instances that are running with unencrypted root ebs volumes. I see a filter "ebs" for ec2 resource which I tried to use to get the desired requirement but no luck. can you help me with this ??

**Comment by scotwk** [comment]
Did you get this question answered already (on gitter or somewhere else?)

Something like this should get you started.  (The `skip-devices` line can be used and adjusted if necessary)

```
  - name: ec2-find-unencrypted-ebs
    resource: ec2
    comments: |
      Detect EC2 instances with unencrypted EBS volumes
    filters:
      - type: ebs
        key: Encrypted
        value: false
        #skip-devices: ['/dev/xvda']
```
