### ISSUE TITLE
lambda policy should validate ids expressions pre deploy

### ISSUE THREAD

**Issue by willjgillen** [capitalone/cloud-custodian#1011]
Policy yaml below works to create the lambda function however when triggered the function fails with this error:
**ParseError: Unexpected token: CopyImage: Parse error at column 5, token "CopyImage" (QUOTED_IDENTIFIER), for expression:
"event"CopyImage""**

thanks
Will

```
policies:

  - name: ec2-ami-compliance
    resource: ami

    mode:
      type: cloudtrail
      events:
       - source: ec2.amazonaws.com
         event: RegisterImage
         ids: "eventRegisterImage"
       - source: ec2.amazonaws.com
         event: DeregisterImage
         ids: "eventDeregisterImage"
       - source: ec2.amazonaws.com
         event: CopyImage
         ids: event"CopyImage"
       - source: ec2.amazonaws.com
         event: ImportImage
         ids: "eventImportImage"
       - source: ec2.amazonaws.com
         event: ModifyImageAttribute
         ids: "eventModifyImageAttribute"
       - source: ec2.amazonaws.com
         event: ResetImageAttribute
         ids: "eventResetImageAttribute"

    filters:
       - type: value
         key: ImageId
         op: ni
         value:
          - ami-1234546

    actions:
      - type: notify
        to:
         - event-user
         - resource-creator
         - user@email.com
        template: policy-template
        transport:
          type: sqs
          region: us-east-1_
```
