### ISSUE TITLE
How does regex filter work?

### ISSUE THREAD

**Issue by iceycake** [capitalone/cloud-custodian#1018]
I'm unable to figure out how the regex works.  By reading the source code, it just a plain simple Python regex with ignore case.

Considering the following policy, I want to filter any EC2 instances that are missing tag `CostCenter` or the value of `CostCenter` needs to be CC[0-9]+

```
- name: discover-untagged-ec2-instances
    resource: ec2
    filters:
      - State.Name: running
      - "tag:aws:autoscaling:groupName": absent
      - and:
        - or:
          - "tag:CostCenter": absent
          - type: value
            key: "tag:CostCenter"
            op: regex
            value: ^((?!\ACC\d+\Z).)*$
```

However, I can't make the above policy work.  Am I missing anything up there?
