### ISSUE TITLE
EC2 filters on instance type

### ISSUE THREAD

**Issue by anandchida** [capitalone/cloud-custodian#1033]
Thank you for open sourcing the wonderful tool! This make AWS management simpler 

I was looking for 2 things for ec2 that I could not figure out from the ec2 filters docs - http://www.capitalone.io/cloud-custodian/docs/policy/resources/ec2.html

I would like to be able to -
* filter ec2 by instance type by tags
I'm looking at enforcing certain tags to run only certain type of instances 
Example:  A tag value of service: nginx should only be running c4.large instance type 

* List any older instance types to enforce usage of latest generation instances with some instance type exclusions for reserve instances already procured

**Comment by kapilt** [comment]
```
policies:
  - name: myinstances
     resource: ec2
     filters:
       - "tag:service": nginx
       - type: value
          key: InstanceType
          value:
             - m3.medium
             - m4.xlarge
          op: not-in
```

the other filter should logically follow from that example.
