### ISSUE TITLE
Detecting events for changes done via web console (manual)

### ISSUE THREAD

**Issue by mechastorm** [capitalone/cloud-custodian#1132]
Is it at all possible to filter by CloudTrail metadata?

I am figuring out how to do set a policy that will 
1.  detect AWS resources that were created manually on the web console
2. Automatically add a tag to the resource - "provisioned:web-console"

Programatically I know I can grab the cloudtrail event and look up the "userAgent" property - if it was "signin.amazonaws.com" then that should mean that resource was created manually on the web console. 

My problem I cannot figure out in the docs on how to filter on that or if it is not supported at the moment. 
```
  - name: ec2-auto-tag-provision-type
    resource: ec2
    mode:
      type: cloudtrail
      role: arn:aws:iam::123:role/custodian-auto-tagger
      events:
        - RunInstances
      filters: 
        - # How to filter by cloudtrail data?
      actions:
        - # Whatever action I want to do on the ec2 instance
```

I can alternatively just detect if the "provisioned" tag is absent and action on that, but I feel it might be more accurate to detect it based on the cloudtrail metadata?
