### ISSUE TITLE
Support for logging filter and action for elb/alb

### ISSUE THREAD

**Issue by tim-elliott** [capitalone/cloud-custodian#1155]
We need a way to filter ELBs for whether or not they are logging, and if not, a way to set up logging to a named bucket using a prefix.  In a perfect world that prefix could reference a tag on the ELB, but that may be another issue.

**Comment by kapilt** [comment]
we do something along these lines with the s3 is-logging-target in terms of scanning the elbs for those with logging we should enable that as a standalone filter, also applies to alb.

**Comment by gfranxman** [comment]
Elb log related action and filter examples:

```yaml
policies:
  - name: log-all-the-things
    resource: elb
    actions:
      - type: enable-elb-logging
        s3_bucket_name: some-name
        s3_bucket_prefix: some-prefix
        emit_interval: some-number

  - name: turn-off-elb-logs
    resource: elb
    actions:
      - type: disable-elb-logging

  - name: find-logging-elbs
    resource: elb
    filters:
      - type: elb-logging-filter
        enabled: true|false
        s3_bucket_name: regex
        s3_bucket_prefix: regex
        emit_interval: digits
        min_interval: digits
        max_interval: digits
```
In the case of the filter, all keys after type are optional.


The AWS console lumps classic ELBs and Application type load balancers together.
These actions and filters could work against Application load balancers conceptually as well, but the api service and underlying data structures, though containing compatible data, are completely different.
Filters like the s3.is-log-target don’t presently have visibility into alb logging for these same reasons.
Given that and the expanded capabilities of the ALBs I think we’d want a discrete alb resource since the actions and other filters they would ultimately support would be pretty different.

You mention setting the s3_bucket_prefix to match a tag on the lb.     What should the syntax for that look like?
