### ISSUE TITLE
An error occurred (AuthFailure)

### ISSUE THREAD

**Issue by MichaelLiZhou** [capitalone/cloud-custodian#1167]
I am receiving an auth failure on the following policy. I first tried to use a limited policy that only allows EC2ReadOnly then moved onto a more dangerous AdminPolicy. Still receiving the following error:

`ClientError: An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials`

Here is the policy:
```
policies:
  - name: ec2-old-instances
    resource: ec2
    comment: |
      Report running instances older than 60 days
    query:
      - instance-state-name: running
    filters:
      - type: instance-age
        days: 60
```

Thanks for the help :)
