### ISSUE TITLE
Multiple Dry Runs Show Same resources

### ISSUE THREAD

**Issue by MichaelLiZhou** [capitalone/cloud-custodian#1215]
So testing a basic vpc check for an email tag

```
policies:
  - name: VPCTags
    resource: vpc
    filters:
      - "tag:Default": absent
    actions:
      - type: mark
        key: CloudCustodianIdentified
        value: Missing email tag
```
I run 
```
custodian run --dryrun -s . vpctag.yml
2017-05-23 14:45:35,308 - custodian.policy - INFO - policy: VPCTags resource:vpc region:us-east-2 count:4 time:0.00
```
Then tried to add that 'Default' tag on 2 VPCs hoping something would take effect
```
custodian run --dryrun -s . vpctag.yml
2017-05-23 14:47:49,008 - custodian.policy - INFO - policy: VPCTags resource:vpc region:us-east-2 count:4 time:0.00
```

The same amount of VPCs will have actionable items. Looks like it is caching API calls? Maybe?
Is this not the proper method of performing dry runs?
