### ISSUE TITLE
Lambda Function Error

### ISSUE THREAD

**Issue by MichaelLiZhou** [capitalone/cloud-custodian#1218]
So i have the following policy that checks for SG
```
    resource: security-group
    filters:
      - type: ingress
        Cidr:
          value: 0.0.0.0/0
          op: eq
          value_type: cidr
      - type: ingress
        Ports: [22]
    mode:
      type: periodic
      role: arn:aws:iam::<something>:role/<something>
      schedule: "rate(1 hour)"
    actions:
      - type: remove-permissions
        egress: matched
```
And looks like it provisioned perfectly fine
```
2017-05-23 21:34:49,961: custodian.policy:INFO Provisioning policy lambda SecurityGroupIdentifier
2017-05-23 21:34:50,979: custodian.lambda:INFO Publishing custodian policy lambda function custodian-SecurityGroupIdentifier
```
Though when i look with the console i see nothing in my function but boiler plate 
```
from c7n import handler

def run(event, context):
    return handler.dispatch_event(event, context)
```
But i see errors and no logs to help debug

![image](https://cloud.githubusercontent.com/assets/10261388/26377584/e1fecba6-3fde-11e7-8643-eaef581b2127.png)
![image](https://cloud.githubusercontent.com/assets/10261388/26377613/fd13a0a6-3fde-11e7-8788-31763c82a555.png)

Should i expect something else for the function
