### ISSUE TITLE
attach-encrypt error caused by file name

### ISSUE THREAD

**Issue by JAizen** [capitalone/cloud-custodian#1239]
It seems certain filenames makes the lambda function fail to encrypt after uploading.

policy used:
```
policies:
  - name: s3-automatic-encryption
  resource: s3
  actions:
    - type: attach-encrypt
      role: arn:aws:iam::<ACCOUNTNUMBER>:role/-
      topic: default
```
file uploaded:
Screen Shot 2017-04-21 at 9.12.10 AM.png

error output:

`error config-bucket-:Screen+Shot+2017-04-21+at+9.12.10+AM.png code:{'Message': 'Not Found', 'Code': '404'}`
