### ISSUE TITLE
notification action - trunk missing payload keys vs 0.8.24.22

### ISSUE THREAD

**Issue by sbasgall** [capitalone/cloud-custodian#1280]
Hello, I am writing a lambda function triggered by SNS for a chatops integration and I'm seeing some difference in the json posted about the policy before the resources block
I have a policy like this:
```
policies:
- name: tag-compliance-ec2
  resource: ec2
  description: |
    Schedule a resource that does not meet tag compliance policies
    to be stopped in fourteen days.
  filters:
    - "tag:app_group": absent
  actions:
    - type: mark-for-op
      op: stop
      days: 14
    - type: notify
      to:
        - resource-creator
      transport:
        type: sns
        topic: arn:aws:sns:us-east-1:1234567890:custodian
```

I don't mind processing the raw json in my lambda function. The json sent to SNS from the master branch of custodian has the `account_id` field which is very helpful. However it's lacking the `policy["resource"]` and `policy["name"]` fields which are quite helpful for my purposes when processing the SNS message json.
When I install the pypi release using pip the message includes the `policy["resource"]` and `policy["name"]` fields but the commit adding the account_id isn't there.

for example a message from the `0.8.42.2` release looks like:
```
Message: {
    u 'account': u '',
    u 'region': u 'us-east-1',
    u 'action': {
        u 'to': [u 'resource-creator'],
        u 'type': u 'notify',
        u 'transport': {
            u 'topic': u 'arn:aws:sns:us-east-1:1234567890:custodian',
            u 'type': u 'sns'
        }
    },
    u 'policy': {
        u 'actions': [{
            u 'type': u 'mark-for-op',
            u 'days': 14,
            u 'op': u 'stop'
        }, {
            u 'to': [u 'resource-creator'],
            u 'type': u 'notify',
            u 'transport': {
                u 'topic': u 'arn:aws:sns:us-east-1:1234567890:custodian',
                u 'type': u 'sns'
            }
        }],
        u 'resource': u 'ec2',
        u 'name': u 'tag-compliance-ec2',
        u 'filters': [{
            u 'tag:app_group': u 'absent'
        }],
        u 'description': u 'Schedule a resource that does not meet tag compliance policies\nto be stopped in fourteen days.\n'
    },
    u 'event': None,
    u 'resources': [...]
}
```

where the message from the `master` branch looks like:
```Message: {
    u 'account': u '',
    u 'account_id': u '1234567890',
    u 'region': u 'us-east-1',
    u 'action': {
        u 'to': [u 'resource-creator'],
        u 'type': u 'notify',
        u 'transport': {
            u 'topic': u 'arn:aws:sns:us-east-1:1234567890:custodian',
            u 'type': u 'sns'
        }
    },
    u 'policy': {
        u 'to': [u 'resource-creator'],
        u 'type': u 'notify',
        u 'transport': {
            u 'topic': u 'arn:aws:sns:us-east-1:1234567890:custodian',
            u 'type': u 'sns'
        }
    },
    u 'event': None,
    u 'resources': [...]
}
```

These are both generated using `custodian run` and the same yaml policy posted above. The only difference is using the `0.8.42.2` release vs the `master` branch.

Thank you.
