### ISSUE TITLE
set-ssl-listener-policy not updating multiple listeners

### ISSUE THREAD

**Issue by tim-elliott** [capitalone/cloud-custodian#1295]
When an ELB has multiple listeners the set-ssl-listener-policy action can sometimes update only one listener with a new policy or create a new policy and not update any listeners.  For example, when the Custodian policy is of the form:
```
  - name: elb-ssl-policies
    resource: elb
    filters:
      - type: ssl-policy
        whitelist:
          - Protocol-TLSv1.1
          - Protocol-TLSv1.2
          - Server-Defined-Cipher-Order
          - DES-CBC3-SHA
          - ...etc...
    actions:
      - type: set-ssl-listener-policy
        name: MYSSLPolicy
        attributes:
          - Protocol-TLSv1.1
          - Protocol-TLSv1.2
          - Server-Defined-Cipher-Order
          - DES-CBC3-SHA
          - ...etc...
```
1) Create a new ELB with two SSL listeners and let AWS assign a default policy to both of them.
2) When the Custodian policy runs it correctly assigns the desired listener policy to both listeners.
3) Replace both listener policies with a custom policy that adds Protocol-TLSv1.
4) When the Custodian policy runs it generates a new policy but doesn't assign it to either listener, and it will do the same thing every time the policy runs.  Eventually it uses up the space allocated for listener policies and throws an error.

There are other cases where the Custodian policy will assign to a single listener on one run, then just create new policies and not assign them to any listeners on subsequent runs.  For example, I had an ELB with 5 listeners.  Steps 1 and 2 were the same.  On step 3 I updated the first listener with a default policy and updated the third listener with a custom policy.  The next time Custodian ran it created a new policy and updated the first listener only.  In subsequent runs it created a new policy and didn't assign it to any listeners.
