### ISSUE TITLE
resource:ec2 filter: imageid policy is broken

### ISSUE THREAD

**Issue by dommmmm** [capitalone/cloud-custodian#1305]
I am using the following policy: 
```
#Policy to return instances with invalid AMI's
- name: ec2-invalid-ami
  resource: ec2
  comment: |
    Find all running EC2 instances that are using invalid AMIs
  filters:
    - "State.Name": running
    - type: value
      key: imageid
      op: in
      value:
          - ami-abc12345 # Invalid
```

Upon running that policy I receive the following error: 

> Traceback (most recent call last):
  File "/root/custodian/bin/custodian", line 9, in <module>
    load_entry_point('c7n==0.8.24.3', 'console_scripts', 'custodian')()
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/cli.py", line 398, in main
    command(options)
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/commands.py", line 55, in _load_policies
    collection = policy_load(options, fp, vars=vars)
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/policy.py", line 59, in load
    if not data or data.get('policies') is None:
AttributeError: 'list' object has no attribute 'get'

Please let me know if I can do something to resolve.
