### ISSUE TITLE
Ec2 policy notify sqs 

### ISSUE THREAD

**Issue by football52** [capitalone/cloud-custodian#1312]
I wrote a policy that filters all ec2 instances that have specific tags absent. After filtering them, I'm trying to notify the Resource Owner that their resource is not compliant with tags. We have the tag Owner on every resource, how do I grab the Owner value?

My policy:
```
policies:

- name: ec2-tag-compliance-mark
  resource: ec2
  mode:
    type: periodic
    schedule: "rate(5 minutes)"
    role: xxxxxxxxxxxxxxxxxxxxx
  filters:
  - or:
    - "tag:Owner": absent
    - "tag:Name": absent
  actions:
    - type: mark
      key: non-compliant
      value: non-compliant
    - type; notify
       template: default
       template_format: 'html'
       priority_header: '1'
       subject: fix your tags
       to:
          - owner
       transport:
         type: sqs
         queue: https://xxxxxxxxxxxxxxxxxxxx
```
