### ISSUE TITLE
Filter out SGs using ec2 resource. 

### ISSUE THREAD

**Issue by srinivas-anant** [capitalone/cloud-custodian#1328]
I have succeeded in filtering out SGs which have open RDP and SSH ports using the below policy. 
``` 
policies:
  - name: Open-security-groups
    resource: security-group
    comment: |
      security groups that have SSH and RDP access from everywhere
    filters:
      - type: ingress
        Ports: [22, 3389]
      - type: ingress
        Cidr:
          value_type: cidr
          op: eq
          value: 0.0.0.0/0
```
I wanted to know if this level of filtering is possible using the ec2 resource? I want to print out the instances which have open RDP and SSH connections rather than the security-group ids.
