### ISSUE TITLE
need tag augment added to RDS aurora

### ISSUE THREAD

**Issue by ocampocj** [capitalone/cloud-custodian#1341]

**Comment by scotwk** [comment]
This policy found my aurora DB in the skunkworks account:

```
policies:
  - name: rds-aurora-tag-test
    resource: rds
    filters:
      - tag:foo: bar
```
