### ISSUE TITLE
Tagging of lambda execution mode

### ISSUE THREAD

**Issue by jantman** [capitalone/cloud-custodian#1351]
This seems sort of ironic to me given how much of what c7n does is tag-based, but it appears that the Lambda execution modes (i.e. ``mode: periodic``) don't have a way to tag the resulting lambda functions... it would be really nice to be able to tag them with the policy name, as well as some user-defined tags.

**Comment by jantman** [comment]
Sorry... I just dug through the code a bit deeper and noticed that the policy's ``mode`` dict can have a ``tags`` key.

**Comment by jtroberts83** [comment]
Would you be able to provide an example policy that tags the Lambdas?

**Comment by jantman** [comment]
@jtroberts83 I haven't actually run it yet, but if my reading of the code is correct...

```yaml
mode:
  type: periodic
  schedule: rate(1 day)
  role: arn:aws:iam::xxxxx:role/cloud-custodian-xxxxx
  tags:
    Project: cloud-custodian
    Component: lambda
    Environment: dev
    OwnerEmail: foo@example.com
```
