### ISSUE TITLE
CreateLoadBalancer event shortcut doesn't account for app-elb

### ISSUE THREAD

**Issue by tim-elliott** [capitalone/cloud-custodian#1354]
The shortcut Cloudtrail event "CreateLoadBalancer" in cwe.py is specific to elb resources and causes a "Could not find resource id" error for any cloudtrail policy created for an app-elb resource.  This is because the resource-id match of "requestParameters.loadBalancerName" is only valid for the elb type; the corresponding match for app-elb resources is "requestParameters.name".  Even when I specify the correct "ids" value in my policy it is ignored because the shortcut list is checked first, the the CreateLoadBalancer event type is matched, and the specification in the policy is never checked.

**Comment by kapilt** [comment]
you'll have to clarify, looking through the code, I see that we only lookup in shortcuts if its a string is specified as the event instead of the full dictionary specification.

**Comment by tim-elliott** [comment]
My policy contains:
```
    resource: app-elb
    mode:
      type: cloudtrail
      events:
        - event: CreateLoadBalancer
          source: "elasticloadbalancing.amazonaws.com"
          ids: "requestParameters.name"
```
Event in Lambda log in Cloudwatch contains:
```
        "eventSource": "elasticloadbalancing.amazonaws.com",
```
and
```
        "requestParameters": {
            "type": "application",
            "name": "my-alb-test1"
             ...
        },
```
However, no resource is found:
```
[INFO]	2017-07-08T23:01:32.259Z	611b185e-6431-11e7-9538-11132a999bad	Found resource ids: []
```

The code looked to me like it checked for a canned event first by event name, and only if it wasn't found would it check the full event spec:
```
    def get_trail_ids(cls, event, mode):
        """extract resources ids from a cloud trail event."""
        # Check if we have a short cut / alias
        info = CloudWatchEvents.match(event)
        if info:
            return info['ids'].search(event)
```

**Comment by kapilt** [comment]
ah.. okay I was checking in a different location (cwe target generation), thanks for the additional detail.

**Comment by ArtemK007** [comment]
I've also hit that issue

I have policy for autotagging ALBs:
```
- name: app-lb-auto-tag-user
    resource: app-elb
    description: |
      Triggered when a new App ELB Instance is launched. Checks to see if
      it's missing the Project of Owner tag. If missing it gets created
      with the value of the ID of whomever called the RunInstances API
    mode:
      type: cloudtrail
      role: ${c7n_autotagger_role}
      events:
        - source: elasticloadbalancing.amazonaws.com
          event: CreateLoadBalancer
          ids: "requestParameters.name"
    filters:
      - and:
        - tag:Project: absent
        - tag:Owner: absent
    actions:
      - type: auto-tag-user
        tag: Owner
        principal_id_tag: OwnerId
```

and lambda log:
```
2018-06-06 09:34:49
START RequestId: dabfd719-696c-11e8-983b-29f4cd80c140 Version: $LATEST
[INFO] 2018-06-06T09:34:49.295Z dabfd719-696c-11e8-983b-29f4cd80c140 Processing event
{
    "account": "123456789012",
    "region": "eu-central-1",
    "detail": {
        "eventVersion": "1.04",
        "eventID": "c2c4de29-f038-4259-92d5-f1379bd03f3f",
        "eventTime": "2018-06-06T09:34:13Z",
        "requestParameters": {
            "ipAddressType": "ipv4",
            "name": "artemk-app-test-lb",
            "subnetMappings": [
                {
                    "subnetId": "subnet-4bd87920"
                },
                {
                    "subnetId": "subnet-7063870d"
                }
            ],
            "securityGroups": [
                "sg-78c1a915"
            ],
            "scheme": "internet-facing",
            "type": "application"
        },
        "eventType": "AwsApiCall",
        "responseElements": {
            "loadBalancers": [
                {
                    "ipAddressType": "ipv4",
                    "vpcId": "vpc-ab786ac3",
                    "loadBalancerArn": "arn:aws:elasticloadbalancing:eu-central-1:123456789012:loadbalancer/app/artemk-app-test-lb/5573d50d88b3ad4d",
                    "scheme": "internet-facing",
                    "canonicalHostedZoneId": "Z215JYRZR1TBD5",
                    "state": {
                        "code": "provisioning"
                    },
                    "dNSName": "artemk-app-test-lb-261782865.eu-central-1.elb.amazonaws.com",
                    "securityGroups": [
                        "sg-78c1a915"
                    ],
                    "loadBalancerName": "artemk-app-test-lb",
                    "createdTime": "Jun 6, 2018 9:34:13 AM",
                    "availabilityZones": [
                        {
                            "subnetId": "subnet-4bd87920",
                            "zoneName": "eu-central-1a"
                        },
                        {
                            "subnetId": "subnet-7063870d",
                            "zoneName": "eu-central-1b"
                        }
                    ],
                    "type": "application"
                }
            ]
        },
        "awsRegion": "eu-central-1",
        "eventName": "CreateLoadBalancer",
        "userIdentity": {
            "principalId": "AROAINFXXXXXXXXX:artemk",
            "accessKeyId": "ASIAIXXXXXXXXXX",
            "sessionContext": {
                "sessionIssuer": {
                    "userName": "developer",
                    "type": "Role",
                    "arn": "arn:aws:iam::123456789012:role/developer",
                    "principalId": "AROAINFXXXXXXXXX",
                    "accountId": "123456789012"
                },
                "attributes": {
                    "creationDate": "2018-06-06T09:05:04Z",
                    "mfaAuthenticated": "true"
                }
            },
            "type": "AssumedRole",
            "arn": "arn:aws:sts::123456789012:assumed-role/developer/artemk",
            "accountId": "123456789012"
        },
        "eventSource": "elasticloadbalancing.amazonaws.com",
        "requestID": "c5b5564e-696c-11e8-9b64-c70c52abb2e7",
        "apiVersion": "2015-12-01",
        "userAgent": "console.ec2.amazonaws.com",
        "sourceIPAddress": "8.8.8.8"
    },
    "detail-type": "AWS API Call via CloudTrail",
    "source": "aws.elasticloadbalancing",
    "version": "0",
    "time": "2018-06-06T09:34:13Z",
    "debug": true,
    "id": "7d547762-7e6f-01aa-dfbc-5f3561b4d403",
    "resources": []
}

[DEBUG] 2018-06-06T09:34:49.833Z dabfd719-696c-11e8-983b-29f4cd80c140 Disabling cache
[INFO] 2018-06-06T09:34:49.833Z dabfd719-696c-11e8-983b-29f4cd80c140 Found resource ids: [u'artemk-app-test-lb']
[INFO] 2018-06-06T09:34:50.120Z dabfd719-696c-11e8-983b-29f4cd80c140 Resources []
END RequestId: dabfd719-696c-11e8-983b-29f4cd80c140
REPORT RequestId: dabfd719-696c-11e8-983b-29f4cd80c140 Duration: 1329.52 ms Billed Duration: 1400 ms Memory Size: 512 MB Max Memory Used: 51 MB 
```

**Comment by tasador** [comment]
I confirm the same issue.  The resource ids are found now, but not the resources:
[INFO]	2018-06-28T06:03:50.128Z	06ee377d-7a99-11e8-a0db-3d54651ec545	Found resource ids: [u'roose-test']
[INFO]	2018-06-28T06:03:50.566Z	06ee377d-7a99-11e8-a0db-3d54651ec545	Resources []

The event looks similar to the previous post.

Policy:

```
policies:

  - name: app-elb-delete-new-internet-facing
    resource: app-elb
    mode:
      type: cloudtrail
      role: arn:aws:iam::XXX:role/lambda_custodian_role
      events:
        - source: elasticloadbalancing.amazonaws.com
          event: CreateLoadBalancer
          ids: "requestParameters.name"
    description: |
      Any newly created Application Load Balanacers launched with
      a internet-facing schema will be deleted right away.
    filters:
      - type: event
        key: "detail.requestParameters.scheme"
        op: eq
        value: "internet-facing"
    actions:
      - delete
      - type: tag
        key: Custodian
        value: DeletionTriggered
```
