### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by ss1921** [capitalone/cloud-custodian#1405]
**I have been trying to implement the following policy to terminate the unencrypted public instances:**

```
- name: terminate-unencrypted-public-rds
    description: |
    Terminate all unencrypted or publicly available RDS upon creation
  resource: rds
  mode:
    type: cloudtrail
    events:
      - CreateDBInstance
   filters:
    - or:
       - StorageEncrypted: false
       - PubliclyAccessible: true
 actions:
   - type: delete
      skip-snapshot: true
```

**and I am getting the following errors:**

`Traceback (most recent call last):`
  `File "/home/sukhpreet/cases/custodian/bin/custodian", line 11, in <module>
    sys.exit(main())`
  `File "/home/sukhpreet/cases/custodian/local/lib/python2.7/site-packages/c7n/cli.py", line 398, in main
    command(options)`
  `File "/home/sukhpreet/cases/custodian/local/lib/python2.7/site-packages/c7n/commands.py", line 55, in _load_policies`
    `collection = policy_load(options, fp, vars=vars)`
`  File "/home/sukhpreet/cases/custodian/local/lib/python2.7/site-packages/c7n/policy.py", line 59, in load
    if not data or data.get('policies') is None:`
`AttributeError: 'list' object has no attribute 'get'`

**Can anybody help?**
