### ISSUE TITLE
No action performed on implementing the policy.

### ISSUE THREAD

**Issue by ss1921** [capitalone/cloud-custodian#1406]
Hi! I am implementing the following policy and trying to terminate the unencrypted public RDS Instances: 
```
policies:
- name: terminate-unencrypted-public-rds
  description: |
    Terminate all unencrypted or publicly available RDS upon creation
  resource: rds
  mode:
    type: cloudtrail
    role: arn:aws:iam::xyz:role/myRDSRole
    events:
      - CreateDBInstance
  filters:
    - or:
        - StorageEncrypted: false
        - PubliclyAccessible: true
  actions:
    - type: delete
      skip-snapshot: true
```

First, I tried to implement this role without using Lambda, but it gave me following error:

```
AssertionError: Lambda function role must be specified
```
Now, I have created a role for AWS Lambda and given it full access for RDS, it went through fine, but no action was performed. The unencrypted public RDS instances remained intact. The following message was displayed on the cli:

```
2017-07-12 17:28:55,934: custodian.policy:INFO Provisioning policy lambda terminate-unencrypted-public-rds
2017-07-12 17:28:56,287: custodian.lambda:INFO Publishing custodian policy lambda function custodian-terminate-unencrypted-public-rds
```
Any suggestions?

**Comment by scotwk** [comment]
Hi @ss1921 -

I edited out your account ID.  

It looks like you set up your policy to work on DB creation.  Did you create the DBs after the policy was in place?  It sounds from your description like you are talking about existing DBs that were not affected?

**Comment by ss1921** [comment]
Yes, I am talking about existing DBs that were not affected.

**Comment by kapilt** [comment]
you've setup the lambda to target only net-new rds instances ie. in response to createdb instance event, if you want to to target existing, you need to pick a different execution mode.

**Comment by ss6851** [comment]
Thank you very much for the suggestion. I have selected a different policy for my lambda function now: `AWSLambdaVPCAccessExecutionRole.`  But the RDS instances still remained unaffected. Any suggestions?

**Comment by scotwk** [comment]
@ss1921 - try this policy from the command line (I've just removed the `mode` section)

```
policies:
- name: terminate-unencrypted-public-rds
  description: |
    Terminate all unencrypted or publicly available RDS upon creation
  resource: rds
  filters:
    - or:
        - StorageEncrypted: false
        - PubliclyAccessible: true
  actions:
    - type: delete
      skip-snapshot: true
```
