### ISSUE TITLE
Any suggestions on how to use Cloud Custodian for creating security groups?

### ISSUE THREAD

**Issue by ss1921** [capitalone/cloud-custodian#1409]
I want to create AWS security groups using Cloud Custodian and since I couldn't find any use case on this topic, can you suggest where to start from?

**Comment by kapilt** [comment]
we generally don't create resources with custodian, and recommend terraform or cloud formation for those purposes. custodian is used more fleet management, ie in this context validating that the extant sg match up to some criteria (allows access on x or y port, from z cidr, etc) and then take action on them (modify, delete, send notification, etc), or finding resources using a particular security group.

**Comment by ss6851** [comment]
@kapilt Could you provide a link to the documentation for that? Or a sample policy to see what the implementation looks like?

**Comment by barundel** [comment]
Yes I would be interested in seeing an example on how one would find a security group with outbound 0.0.0.0/0 and then remove that outbound rule.

**Comment by alfredgamulo** [comment]
@barundel you can use the `schema` command to find examples as follows:

```
$ custodian schema security-group
security-group:
  actions: [delete, invoke-lambda, mark, mark-for-op, normalize-tag, notify, patch,
    put-metric, remove-permissions, remove-tag, rename-tag, tag, tag-trim, unmark,
    untag]
  filters: [and, default-vpc, diff, egress, event, ingress, marked-for-op, not, or,
    stale, tag-count, unused, used, value]

$ custodian schema security-group.filters.unused

Help
----

Filter to just vpc security groups that are not used.

We scan all extant enis in the vpc to get a baseline set of groups
in use. Then augment with those referenced by launch configs, and
lambdas as they may not have extant resources in the vpc at a
given moment. We also find any security group with references from
other security group either within the vpc or across peered
connections.

Note this filter does not support classic security groups atm.

:example:

    .. code-block: yaml

        policies:
          - name: security-groups-unused
            resource: security-group
            filters:
              - unused

Schema
------

{
    "additionalProperties": false, 
    "required": [
        "type"
    ], 
    "type": "object", 
    "properties": {
        "type": {
            "enum": [
                "unused"
            ]
        }
    }
}

```

To answer your other question, I believe the policy you're looking for would look something like:

```
        policies:
          - name: security-groups-egress
            resource: security-group
            filters:
              - type: egress
                Cidr:
                  value: 0.0.0.0/0
                  value_type: cidr
            actions:
              - type: remove-permissions
                egress: matched
```

**Comment by ss6851** [comment]
2017-08-14 13:54:45,612: custodian.policy:INFO policy: security-groups-egress resource:security-group region:us-west-1 count:0 time:0.51

**Comment by ss6851** [comment]
Hi @alfredgamulo, I created a security group with outbound 0.0.0.0/0 and implemented the following policy: 
```
        policies:
          - name: security-groups-egress
            resource: security-group
            filters:
              - type: egress
                Cidr:
                  value: 0.0.0.0/0
                  value_type: cidr
            actions:
              - type: remove-permissions
                egress: matched
```

The above policy couldn't find the security group with 0.0.0.0/0 and generated the following output: 

`2017-08-14 13:54:45,612: custodian.policy:INFO policy: security-groups-egress resource:security-group region:us-west-1 count:0 time:0.51`

**Comment by alfredgamulo** [comment]
@ss6851 ah, the `value_type: cidr` isn't behaving as I'd expected it to work.  Try a policy that removes that line:

```
  - name: security-groups-egress
    resource: security-group
    filters:
      - type: egress
        Cidr:
          value: "0.0.0.0/0"
```

**Comment by ss6851** [comment]
@alfredgamulo, the suggested changes worked! Thank you very much. 

The following information is regarding implementing the policy to find unused security groups:
```
policies:
          - name: security-groups-unused
            resource: security-group
            filters:
              - unused
```
The following output was generated when the above policy was implemented:
```
2017-08-14 14:15:20,830: custodian.policy:INFO policy: security-groups-unused resource:security-group region:us-west-1 count:7 time:0.35
```
New unused security groups were created after this experiment and Cloud Custodian was executed again with the same policy. It was found that the `count` variable, which informs about the unused security groups, remained fixed at 7.
