### ISSUE TITLE
Filter resources based on their name using Regex

### ISSUE THREAD

**Issue by Dhruvin1** [capitalone/cloud-custodian#1437]
Hi, I need to fix an issue with my AWS account set up. I have many users in my account, some are humans and some are for programmatic API access. Their name has a unique property to differentiate them. Can you please specify the filter to use for string manipulation based on resource name if at all possible? 
Thanks in Advance.

**Comment by scotwk** [comment]
Hi @Dhruvin1 

Here is an example policy using regexes to match on users.  I assumed you meant the `UserName` field, but adjust that if needed.  Note that the regex is case-insensitive.

```
policies:
  - name: dhruvins-user-filter-policy
    resource: iam-user
    filters:
      - type: value
        key: UserName
        op: regex
        value: "PUT YOUR REGEX HERE"
```
