### ISSUE TITLE
config rule s3 Lambda - no resources matched

### ISSUE THREAD

**Issue by sudharsans** [capitalone/cloud-custodian#1451]
I have custodian policy which doesn't work from lambada but works on the local machine. following is the logs found in the cloudwatch. Could you please help?

```
 - name: S3-enable-logging
   mode:
     type: config-rule
     role: arn:aws:iam::account:role/CloudCustodian
   resource: s3
   filters:
      - "tag:Name": present
   actions:
     - type: toggle-logging
       target_bucket:s3-logs
       target_prefix: logs
```

Policy:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
```

Logs:
> Filtering resources with [<c7n.filters.core.ValueFilter object at 0x7f0303204ad0>]
> applied filter <c7n.filters.core.ValueFilter object at 0x7f0303204ad0> 1->0
> Filtered from 1 to 0 s3
> [INFO] Filtered resources 0
> [INFO] policy: S3 resources: s3 no resources matched
> [INFO] policy: S3 resources: s3 no resources matched
