### ISSUE TITLE
Number Value Filters Should Work on Tags

### ISSUE THREAD

**Issue by eagle6525** [capitalone/cloud-custodian#147]
I have an ec2 instance with a tag named `my-tag` and a value of `10`. I run these policies and it includes the instance in the filter in both cases. You would have to do something for non-number values. Maybe they should always filtered out.

Policy one:
```
policies:
  - name: ec2
    resource: ec2
    filters:
      - type: value
        value: 5
        op: gt
        key: tag:my-tag
```
Policy two:
```
policies:
  - name: ec2
    resource: ec2
    filters:
      - type: value
        value: 500
        op: gt
        key: tag:my-tag
```

**Comment by kapilt** [comment]
tag values are always strings, which limits numeric comparison on them. ideally we could include some additional jmespath expression on key as we do with non 'tag:' prefixed values to allow for jmespath functions like to_number to be utilized. alternatively we'd have to add some additional 'key_type' or 'value_type' to enable the conversion.

**Comment by kapilt** [comment]
value_type makes a bit more sense, we typically have to do this conversion for date matches as is and do custom filters for them. so value_type would basically do the resource and config type conversion.

**Comment by kapilt** [comment]
supported in trunk via additional parameter to value type filter, note default is currently hardcoded to 0, i'll try and make that adjustable next pull request via a default param on the filter.

```
policies:
  - name: ec2
    resource: ec2
    filters:
      - type: value
        value: 5
        value_type: integer
        op: gt
        key: tag:my-tag
```
