### ISSUE TITLE
add CreateSecurityGroup as shortcut in cwe.py

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#1470]
Desire is to have ingress filter run when this event occurs

**Comment by salwandhruvdev** [comment]
Hi @FireballDWF You can define arbitrary CloudWatch Events by specifying ids and source in the config file itself. For instance:
```
policies:
    - name: filter-ingress
       resource: security-group
       mode: 
         type: cloudtrail
         events:
           - source: ec2.amazonaws.com
              event: CreateSecurityGroup
              ids: "requestParameters.groupName"
```
The mappings/shortcuts in cwe.py is for most common events, and I believe the above policy should work for the use-case you have. 
Thanks!
