### ISSUE TITLE
iam-role cloudtrail events aren't returning anything. 

### ISSUE THREAD

**Issue by JAizen** [capitalone/cloud-custodian#1480]
I've been trying to create a policy which would notify me if a role has a managed policy attached.

Using this policy i don't seem to be able to filter the event or action my notify.

even hardcoding a filter that would be a sure fire still doesn't seem to work.

the policy:
```
policies:
- name: iam-roles-with-escalated-permissions
  resource: iam-role
  mode:
    role: arn:aws:iam::<ACCOUNTNUMBER>:role/custodian
    type: cloudtrail
    events:
      - source: "iam.amazonaws.com"
        event: AttachRolePolicy
        ids: "requestParameters.roleName"
  filters:
    - type: event
      key: "detail.requestParameters.policyArn"
      op: regex
      value: (^arn:aws:iam::aws:policy\/)\w+

  actions:
    - type: notify
      template: default
      priority_header: 2
      subject: "test"
      violation_desc: "test"
      action_desc: "test"
      to:
          - arn:aws:sns:eu-west-1::mailer-sns
      transport:
        type: sqs
        queue: https://sqs.eu-west-1.amazonaws.com//mailer
```

log:
```
16:43:11
[INFO]   Found resource ids: [u'jenkins']

[INFO]   Resources []

END RequestId:
```
