### ISSUE TITLE
Provide generic support for "missing" resources

### ISSUE THREAD

**Issue by erickascic** [capitalone/cloud-custodian#1517]
As it stands, I *believe* there is no generic way of searching for "missing" resources short of writing a custom filter.

For example - if I'm fishing for an IAM user with UserName X - I can't look for it and then measure the resource_count.  If no resources come back, then that's that - no match.  I have to write a custom filter (at the account level?) that sends back a synthetic IAM user resource to match the missing resource.

**Comment by alfredgamulo** [comment]
Hi Eric,
What is it that you're trying to accomplish? If you don't find the IAM user named "X" then are you looking to create it?

**Comment by erickascic** [comment]
In our case, we're just looking for a notification when a resource we expect to be there (in a managed account) is no longer there.  In our situation, we have the potential for a rogue admin mangling stuff, and proactively confirming the existence of certain resources is part of the mitigation strategy.

**Comment by kapilt** [comment]
its an interesting use case, and agreed with the analysis, we effectively need a synthetic resource to mark the absence of something to run through on actions, which the account resource is already effectively. we could do it as a filter that does an embedded resource policy that matches when its . and then have action like deploy cft and notify as a remediation. 

so sketching it out, something like this where in the filter matches if the named bucket doesn't exist.

```
name: missing-s3-bucket
resource: account
filters:
   - type: missing
      policy:
        resource: s3
        filters:
           - Name: my-bucket
actions:
    - notify
```

thoughts?

**Comment by alfredgamulo** [comment]
Perhaps this could be implemented using config's list_discovered_resources or get_resource_config_history where the policy could be something like

```
name: stack-status
resource: account
filters:
  - type: missing
     resource: s3
     names_from: 
        url: *list_of_s3_names
        format: txt
```
