### ISSUE TITLE
OnHour/OffHour filter 

### ISSUE THREAD

**Issue by geek876** [capitalone/cloud-custodian#1561]
Is it possible to filter on tags as well as the offhour/onhour policy ?

eg:
```
policies:
  - name: offhours-stop1
    resource: ec2
    filters:
      - "tag:sometag": x
      - "tag:someothertag": y
      - type: offhour
        weekends: false
        default_tz: pt
        tag: downtime
        opt-out: true
        onhour: 8
        offhour: 20
   - name: offhours-stop2
    resource: ec2
    filters:
      - "tag:sometag": p
      - "tag:someothertag": q
      - type: offhour
        weekends: false
        default_tz: pt
        tag: downtime
        opt-out: true
        onhour: 7
        offhour: 18
```

My use-case is we have `sometag` and `someothertag` Tags on all of our instances and I want to drive the `offhours-stop` policy based on the values of these tags rather than changing it via `downtime` tag.

**Comment by kapilt** [comment]
yes you can sets of resources by arbitrary counts and combinations of filters. not sure what the question is. if you do opt-out then a non value for the downtime tag will result in the values from the policy being used. note offhour/onhour filters only match when the current execution time matches the time configured.

**Comment by geek876** [comment]
Thanks @kapilt.
My use case is that I want to drive Stopping/Starting instances entirely via Policies (not via custom Tag). I have certain set of instances (each set having 1 to 100 instances) that I want to stop/start as per their respective schedules. They all have unique tags. 

**Set1 Tags** (start at 8, stop at 22)
```
Department: finance
Class: production
CloudCustodian: true
```

**Set2 Tags** (start at 10, stop at 16)
```
Department: insurance
Class: production
CloudCustodian: true
```
So rather than setting start-stop times within **Tag - CloudCustodian** I intend to have policies like

```
policies:
   - name: start-set-1-instances
     resource: ec2
     filters:
         - "tag:Department": insurance
         - "tag:Class": production
         - type: onhour
           tag: CloudCustodian
           onhour: 10
    actions:
         - start

   - name: start-set-2-instances
     resource: ec2
     filters:
         - "tag:Department": finance
         - "tag:Class": production
         - type: onhour
           tag: CloudCustodian
           onhour: 8
    actions:
         - start

   - name: stop-set-1-instances
     resource: ec2
     filters:
         - "tag:Department": insurance
         - "tag:Class": production
         - type: offhour
           tag: CloudCustodian
           offhour: 22
    actions:
         - stop

   - name: stop-set-2-instances
     resource: ec2
     filters:
         - "tag:Department": finance
         - "tag:Class": production
         - type: offhour
           tag: CloudCustodian
           onhour: 16
    actions:
         - stop
```
We frequently have requirements to change the **start/stop** schedule so the idea is that we would only update the policies _start/stop hour specifically_ under such circumstances 

** How-ever ** I think I am hitting a **cache** issue here
The policies do run first time but whenever they are changed (ex: say I change stop time for Set1 to be 20 from 22), I have to **clear** the cache ` rm -rf /home/<user>/.cache/cloud-custodian.cache` or else the original time of **22** is always in effect.

Perhaps I need to set the **cache** to expire more quickly if possible at all ?
