### ISSUE TITLE
Feature Request - Add policy option to add s3 object lifecycle to buckets

### ISSUE THREAD

**Issue by jtroberts83** [capitalone/cloud-custodian#1580]
As I was replacing our internal S3 tools with Cloud Custodian policies I noticed there isn't an option to apply an S3 bucket lifecycle in Custodian.  This would be a great policy option addition as it falls under the cost savings pillar of Custodian.  I would attempt to code this myself but have way too much going on this sprint.  Here is an example policy that I was thinking for adding a LifeCycle config to a bucket:

```
policies:
- name: apply-s3-lifecycle-policy
  resource: s3
  filters:
        - type: value
          key: "Lifecycle"
          value: null
  actions:
      - type: object-lifecycle
        prefix: "/"
        transition:
              - days: 180
              - storage_class: "STANDARD_IA"
        versionexpiration:
              - noncurrentdays: 35
```

As an enhancement down the road the ability to load the lifecycle config parameters via a json from s3 something like this:

```
policies:
- name: apply-s3-lifecycle-policy
  resource: s3
  filters:
      - type: value
        key: "Lifecycle"
        value: null
  actions:
      - type: object-lifecycle
        config_from: s3://bucketname/s3-lifecycle-config.json
```

Where the s3-lifecycle-config.json file contains something like this: 
```
{
	"Rules": [
		{
			'ID': 'S3-LifeCycle-Policy',
			"Prefix": "/",
			"Status": "Enabled",
			"Transition": {  
				"Days": 180,
				"StorageClass": "STANDARD_IA"
			},
			"NoncurrentVersionExpiration": {
				"NoncurrentDays": 35,
			}
		}
	]
}
```
