### ISSUE TITLE
Issue: Security Group Actions Schema bug

### ISSUE THREAD

**Issue by andrewalexander** [capitalone/cloud-custodian#1593]
Seems to be an issue in the way schemas are validating. Tried in both python2 and 3, with slightly different behavior in both. See gist: https://gist.github.com/andrewalexander/9c528ccba3b62e743b5d858503ae5c4f

Long story short:
- For actions, we should be able to do one of the following, but can only do the last two (`['remove', 'isolation-group']` and `'add'` by itself)
```
['add', 'remove']
['remove', 'isolation-group']
['add']
```
- Seems to be valid under two of the above; could be getting confused on which happy path to take (since it satisfies two separate schema definitions)
- When split out into two separate actions statements, both the old SG (that we were supposed to remove) and the new one are left attached. Example actions that seem to be what we want, but leaves both SGs instead of just the one from the 'add':
```
    actions:
      - type: modify-security-groups
        remove: matched
        isolation-group: sg-deadbeef
      - type: modify-security-groups
        add: sg-bdca74ce
```
- Errors are different in different python versions; python2 seemed to point to issue (duplicate matching schemas); python3 seemed to treat the policy as a lambda/event-based policy. Unsure based on error of `custodian.commands:ERROR 'security-group' is not one of ['event']`

Might just be as simple as swapping the `oneOf` to an embedded `enum` to more explicitly force a happy path.
