### ISSUE TITLE
Security group CIDR when compare to 0.0.0.0/0 matches the source security groups as well

### ISSUE THREAD

**Issue by Dhruvin1** [capitalone/cloud-custodian#1595]
I have been implementing a policy to match the security groups that allow the source 0.0.0.0/0 for some vulnerable ports. However, the rule is also matching when the source field contains security group and not 0.0.0.0/0. Snippet of my config file looks like below.
```yaml
    filters:
      - or:
        - type: ingress
          Ports: [22]
          Cidr:
            value: 0.0.0.0/0
            op: eq
            value_type: cidr
 ```
