### ISSUE TITLE
mark-for-op with fraction of a day does not have intended impact

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#1608]
When a mark-for-op action contains a days setting which is set to 30mins, like the following 
```  
  actions:
      - type: mark-for-op
        op: terminate        
        tag: custodian_status
        days: 0.02
```
a marked-for-op filter with return true even if executed only 1 minute later, as the tag used to store the date only contains a whole number of days.  Example below
```
  filters:
     - type: marked-for-op
        tag: custodian_status
        op: terminate
```

The workaround is to add a filter for instance-age or other type of age of resource which does work correctly.  However, since fractional days are allowed for mark-for-op, anyone who assumes that fractional days will be actually between mark-for-op and marked-for-op actually works (without also implementing the age of resource filter) will have their actions take effect earlier than they intended.
