### ISSUE TITLE
offhour filter without tag

### ISSUE THREAD

**Issue by lightbeard** [capitalone/cloud-custodian#1639]
The schema output of the `offhour` filter does not have `tag` as required. This to me indicates that it should work without looking for a tag. This is ideal for our use case because we always want to shutdown sandbox instances in the evening but do not wish to turn them back on with cloud custodian. We run the policy periodically with a scheduler so tagging is redundant.

The following does not result in instance shutdowns:

```
  - name: daily-sandbox-shutdown
    resource: ec2
    comment: EC2 servers in sandbox environments are shutdown daily at 8pm

    filters:
        - type: offhour
          offhour: 20
          default_tz: est
    actions:
      - stop
```

It does work when the `tag` element is specified. It seems there is either a bug with the filter or the filter schema should require `tag`?
