### ISSUE TITLE
ASG -Invalid filter is marking Community AMIs as Invalid

### ISSUE THREAD

**Issue by jtroberts83** [capitalone/cloud-custodian#1659]
When running the ASG policy with just the -Invalid filter it is stating that Autoscaling groups using Community AMIs are invalid.

```
- name: asg-invalid-config
  resource: asg
  description: |
     Policy finds invalid ASG based on these checks: invalid subnets, invalid security groups, 
     invalid key pair name, invalid launch config volume snapshots, invalid amis, invalid health check elb
     It will then email the ASG owner and CloudCustodian to notify of bad setup which will prevent the 
     ASG from scaling out.  Most commonly the AMI has been deleted.
  filters:
   - invalid
  actions:
    - notify............
```

A couple community AMI examples that are being flagged as invalid:
ami-809f84e6
ami-ebd02392
