### ISSUE TITLE
EC2s not getting stopped

### ISSUE THREAD

**Issue by hav3wb** [capitalone/cloud-custodian#1673]
Running a cloud trail policy for stopping EC2s with expired AMIs, not all of the instances are being stopped. All are being correctly identified and tagged, but not all are stopped. Attached are screenshots of one example of this where of 10 instances started, 10 were tagged but then only 9 were stopped. Here is a snippet of the policy in question: 
```
- name: ec2-ami-ancient-create-stop-event-baldur
    resource: ec2
    description: Stop EC2s launched with expired AMI
    mode:
      type: cloudtrail
      events:
        - RunInstances
    filters:
      - type: image-age
        days: 60
        op: gt
      - "tag:aws:autoscaling:groupName": absent
      - "tag:aws:elasticmapreduce:job-flow-id": absent
      - "tag:aws:elasticmapreduce:instance-group-role": absent
      - type: value
        key: "tag:custodian_ami_compliance"
        value: exclude
        op: ne
    actions:
      - type: tag
        key: baldur-above-60
        value: "AMIExpired instance Stopped"
      - stop
```
