### ISSUE TITLE
lambda delete action - handle lambda @ edge functions

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#1688]
`
An error occurred (InvalidParameterValueException) when calling the DeleteFunction operation: Lambda was unable to delete arn:aws:lambda:us-east-1:xxx:function:xxx-Test-LambdaEdge:1 because it is a replicated function.: InvalidParameterValueException`

**Comment by lfreneda** [comment]
+1

**Comment by zacharya** [comment]
Looks like AWS is handling the deletion of replicated functions behind the scenes: 
 https://forums.aws.amazon.com/ann.jspa?annID=5529

The way you trigger this is by removing the CloudFront associations which then kicks off the deletion of the replicated functions automatically, but until that completes you can't delete the parent function.

AWS says the replicated functions are "typically deleted within a few hours".  Does c7n have a framework we could plug into for handling deferred actions that periodically check and wait on a precondition before processing?

**Comment by thisisshi** [comment]
@zacharya the best way to do it would be to use the `mark-for-op` pattern I suppose, pseudocode policy:

```yaml
policies:
  - name: mark-lambda-edge-for-deletion
    resource: lambda
    actions:
      - delete-associated-cloudfront-distributions # not a real action, just spitballling
      - type: mark-for-op
        tag: c7n_lambda_edge_delete
        op: delete
        days: 1

  - name: delete-lambda-edge
    resource: lambda
    filters:
      - type: marked-for-op
        tag: c7n_lambda_edge_delete
      - no-cloudfront-distributions # not a real filter either
    actions:
      - delete
```
