### ISSUE TITLE
Prevent S3 set-inventory action failures from killing the whole policy run

### ISSUE THREAD

**Issue by jhnlsn** [capitalone/cloud-custodian#1702]
When iterating over a set of matched s3 buckets and a single bucket throws a ClientError, the whole policy run will terminate.  It would be better to fail gracefully, logging on the failed buckets and performing actions on the remainder.

```yaml
- name: inventory-setter
  resource: s3
  actions:
    - type: set-inventory
      ... 
```
