### ISSUE TITLE
S3 action to add bucket policy statements

### ISSUE THREAD

**Issue by ewbankkit** [capitalone/cloud-custodian#1744]
Add an S3 action to add specified bucket policy statements.
Relates to:
* https://github.com/capitalone/cloud-custodian/issues/973
* https://github.com/capitalone/cloud-custodian/issues/1714

**Comment by ewbankkit** [comment]
Possible syntax:
```yml
policies:
    - name: force-s3-https
    resource: s3
    actions:
        - type: add-statements
        statements:
            - Sid: "DenyHttp"
            Effect: "Deny"
            Action: "s3:GetObject"
            Principal:
                AWS: "*"
            Resource: "arn:aws:s3:::{bucketname}/*"
            Condition:
                Bool:
                    "aws:SecureTransport": false
```

We will need a way to substitute at least the account ID and "current" bucket name into the statement (`{bucketname}` in the sample) - Overlap with https://github.com/capitalone/cloud-custodian/pull/1739?
