### ISSUE TITLE
CreateDBInstance cloudtrail event type does not see tags

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#1745]
Suspect regression somewhere between current tip and 0.8.24.0 version when remember testing this this policy.
While I see all expected tags in the CWE logs where it dumps the inbound event contents "Processing Event", the following logs indicates a match for missing tags and the notify action I output the value of c7n:MatchedFilters which indicates it saw all the tags absent. I suspect with recent tagging changes, it needs to call the list-tags-for-resource api, or get the tags from the inbound event
```
policies:
  - name: mark-rds-tagcompliance-cloudtrail
    resource: rds
    description: |
      mark RDS instance if RequiredTags Absent
    mode:
      type: cloudtrail
      role: "arn:aws:iam::{account_id}:role/lambda-cloudcustodian"
      events: 
        - CreateDBInstance
    filters:
      - or:
        - "tag:OwnerEmail": absent
        - "tag:ProjectCode": absent
        - "tag:CostCenter": absent
        - "tag:Name": absent
        - "tag:AppName": absent
        - "tag:Component": absent
```
Example value of c7n:MatchedFilters=[u'tag:OwnerEmail', u'tag:ProjectCode', u'tag:CostCenter', u'tag:Name', u'tag:AppName', u'tag:Component']
```

**Comment by kapilt** [comment]
hmm.. thats about where we switched to resource group tagging api. @alfredgamulo can you have a look this?

**Comment by alfredgamulo** [comment]
That's really odd. I'll take a look. 
In general though, I think that a tag policy on CreateDBInstance should probably be reworked because iirc you cannot add tags to an RDS atomically in the console unless you are using cloudformation.

**Comment by alfredgamulo** [comment]
@FireballDWF I'm unable to recreate the issue.
I created two Stacks with the CFT having commented out the tag for one stack:
```
Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      DBInstanceClass: db.m1.small
      Engine: MySQL
      MasterUsername: MyName
      MasterUserPassword: MyPassword
      Tags:
      - Key: k1
        Value: v1
      # - Key: peekaboo
      #   Value: iseeyou
```

and I ran a policy on createDBInstance which executes as expected

```
policies: 
  - name: peekaboo-rds
    resource: rds
    description: |
      mark RDS instance if RequiredTags Absent
    mode:
      type: cloudtrail
      role: "arn:aws:iam::0123456789012:role/lambda-role"
      events: 
        - CreateDBInstance
    filters:
      - "tag:peekaboo": absent
    actions:
      - type: tag
        key: "missing"
        value: "tag"
```

Would you be able to provide more info on the cloudtrail events? 
I am using the latest HEAD from master.
