### ISSUE TITLE
Example of tag compliancy needs an 'or' in the doc

### ISSUE THREAD

**Issue by caversa** [capitalone/cloud-custodian#1776]
The example for 'Enforce Tag Compliance' needs an 'or' added to look for whether any of those required tags are missing. 
http://www.capitalone.io/cloud-custodian/docs/usecases/tagcompliance.html

```
policies:

- name: ec2-tag-compliance-mark
  resource: ec2
  comment: |
    Find all (non-ASG) instances that are not conformant
    to tagging policies, and tag them for stoppage in 1 days.
  filters:
    - or:       <-------------------- add this line
       - "tag:aws:autoscaling:groupName": absent
       - "tag:c7n_status": absent
       - "tag:Owner": absent
       - "tag:CostCenter": absent
       - "tag:Project": absent
  actions:
    - type: mark-for-op
      op: stop
      days: 1
```
