### ISSUE TITLE
Lambda w/ py2.7 remote and py3 local hits SyntaxError

### ISSUE THREAD

**Issue by vishnuvpotti** [capitalone/cloud-custodian#1784]
Hi All,

I just started using custodian and was looking at 
http://www.capitalone.io/cloud-custodian/docs/policy/lambda.html#cloudwatch-events

1) I created IAM role using this link 
https://aws.amazon.com/premiumsupport/knowledge-center/start-stop-lambda-cloudwatch/

2) I created my rule as below and saved it as policy.yml

```
policies:
  - name: my-first-policy
    mode:
        type: config-rule
        role: arn:aws:iam::123456789012:role/lambda_start_stop_ec2
    resource: ec2
    filters:
      - "tag:custodiantest": present
    actions:
      - stop
```

3) Ran command from my machine
custodian run -s . policy.yml --region ap-southeast-2
I created an EC2 machine with tag "custodiantest". 

Saw Logs in machine as below

ubuntu@ip-1xx-xx-x-xxx:~/custodiantest$ custodian run -s . policy.yml --region ap-southeast-2
2017-11-14 04:54:31,691: custodian.policy:INFO Provisioning policy lambda my-first-policy
2017-11-14 04:54:31,756: custodian.lambda:INFO Publishing custodian policy lambda function custodian-my-first-policy

Cloud watch error logs shown in below image.
![custodian_error](https://user-images.githubusercontent.com/17942857/32764074-b1eb6cdc-c957-11e7-9418-60e253fefdd8.JPG)

Can you please let me know what is going wrong.
Is this an existing bug?

Thanks in advance

Vishnu
