### ISSUE TITLE
New filter for S3 buckets

### ISSUE THREAD

**Issue by dlut2** [capitalone/cloud-custodian#1790]
With a custodian filter, we would like to be able to select Empty Buckets and use Bucket Age to refine the results.  For example, a filter that selects empty buckets over 60 days old would help us identify buckets to delete.

**Comment by jtroberts83** [comment]
@dlut2   While having a filter would be nice for less clutter in the policy files, you can achieve the same results by using a metrics and age filter like so:

```
- name: delete-empty-s3-buckets-over-60-days-old
  resource: s3
  filters:
      - type: value
        value_type: age
        key: CreationDate
        value: 60
        op: greater-than
      - type: metrics
        name: NumberOfObjects
        days: 60
        value: 0
        op: eq
  actions:
      - delete
```
