### ISSUE TITLE
S3 lifecycle schema issue

### ISSUE THREAD

**Issue by scotwk** [capitalone/cloud-custodian#1830]
@jtroberts83 asked me why this policy is failing:

```
- name: agt-s3-apply-lifecycle
  resource: s3
  actions:
    - type: configure-lifecycle
      rules:
        - ID: agt-s3-lifecycle
          Status: Enabled
          Prefix: /
          Transitions:
            - Days: 180
              StorageClass: STANDARD_IA
          NoncurrentVersionExpiration:
            NoncurrentDays: 35
```

I tracked it down to a problem in the S3 lifecycle schema.  I'll have a PR shortly.
