### ISSUE TITLE
RDS - snapshot action - specify hour-minute on backup name to prevent DBSnapshotAlreadyExists errors on intra day backups

### ISSUE THREAD

**Issue by vishnuvpotti** [capitalone/cloud-custodian#1833]
Hi,

I have created a policy to create backups of RDS and EC2 instance at regular intervals.
```
policies:
  - name: test-ec2-backup-creation
    mode:
        type: periodic
        schedule: "cron(00 1,5,9 ? * MON-FRI *)"
        role: arn:aws:iam::::randomnumber:role/custodian_ec2_role
    resource: ec2
    filters:
       - "tag:testcust": present
    actions:
      - type: snapshot
        copy-tags:
            - Name
  - name: test-rds-backup-creation
    mode:
        type: periodic
        schedule: "cron(00 1,5,9 ? * MON-FRI *)"
        role: arn:aws:iam::randomnumber:role/custodian_rds_role
    resource: rds
    filters:
      - "tag:testcust": present
    actions:
      -  type: snapshot
```

The policy works fine for EC2.
For RDS, the policy works fine for first time, but from second time onwards I get these errors .

Exception creating rds snapshot 
An error occurred (DBSnapshotAlreadyExists) when calling the CreateDBSnapshot operation: Cannot create the snapshot because a snapshot with the identifier backup-devdb-2017-11-22 already exists.

The error is because RDS snapshots is named like backup-databasename-2017-11-22 and this will prevent multiple snapshots on same day.
Is there a way we can append custom name or append hour:minutes:seconds to snapshot name?

Thanks in advance.
Vishnu
