### ISSUE TITLE
Ability to use account_id variable within the output_dir of execution options?

### ISSUE THREAD

**Issue by caversa** [capitalone/cloud-custodian#1882]
I'm very happy to see that account can be referenced now for a queue or a role, as I'd love to simplify the number of policy scripts I manage.  

There's one other place I reference the account, and that is the bucket.  I append the account id to make a unique bucket name.  Is that in the plans to be addressed?  Or is there another way you'd recommend to do this?  I've noticed that when deploying a lambda function, the output parameter flag does not get passed to the lambda function for execution, so I believe it must be embedded within the policy itself. 

```
  mode:
      type: config-rule
      role: arn:aws:iam::{account_id}:role/cloud-custodian      <----- works great
      execution-options:
        output_dir: s3://cloudcustodian-{account_id}     <------ does not work
      ....

```
Thanks!
Carrie

error message:
 "errorType": "ParamValidationError",
  "errorMessage": "Parameter validation failed:\nInvalid bucket name \"cloudcustodian-{account_id}\": Bucket name must match the regex \"^[a-zA-Z0-9.\\-_]{1,255}$\""
