### ISSUE TITLE
OffHours Policy Error

### ISSUE THREAD

**Issue by chaosdarky** [capitalone/cloud-custodian#1922]
Hi, I am having an issue in running the offhours policy. Can someone help or guide me to fix this?

> 2018-01-08 10:54:11,967: custodian.commands:ERROR Configuration invalid: offhours.yml
2018-01-08 10:54:11,969: custodian.commands:ERROR Additional properties are not allowed ('onhour' was unexpected)

>Failed validating u'additionalProperties' in schema[12]:
    {u'additionalProperties': False,
     u'properties': {u'default_tz': {u'type': u'string'},
                     'offhour': {u'maximum': 23,
                                 u'minimum': 0,
                                 u'type': u'integer'},
                     u'opt-out': {u'type': u'boolean'},
                     u'skip-days': {u'items': {u'pattern': u'^[0-9]{4}-[0-9]{2}-[0-9]{2}',
                                               u'type': u'string'},
                                    u'type': u'array'},
                     u'skip-days-from': {u'additionalProperties': u'False',
                                         u'properties': {u'expr': {u'oneOf': [{u'type': u'integer'},
                                                                              {u'type': u'string'}]},
                                                         u'format': {u'enum': [u'csv',
                                                                               u'json',
                                                                               u'txt',
                                                                               u'csv2dict']},
                                                         u'url': {u'type': u'string'}},
                                         u'required': [u'url'],
                                         u'type': u'object'},
                     u'tag': {u'type': u'string'},
                     u'type': {u'enum': [u'offhour']},
                     u'weekends': {u'type': u'boolean'},
                     u'weekends-only': {u'type': u'boolean'}},
     u'required': [u'offhour', u'default_tz', u'type'],
     u'type': u'object'}

>On instance:
    {'default_tz': 'pt',
     'offhour': 20,
     'onhour': 8,
     'opt-out': True,
     'tag': 'downtime',
     'type': 'offhour',
     'weekends': False}

**Comment by thisisshi** [comment]
Using onhours/offhours requires two separate policies, one to turn off the instance and one to turn it back on i.e.:

```yaml
- name: off-hour
  resource: ec2
  filters:
    - type: offhour
      tag: downtime
      default_tz: pt
      offhour: 20
      opt-out: True
      weekends: False
  actions:
    - stop

- name: on-hour
  resource: ec2
  filters:
    - type: onhour
      tag: downtime
      default_tz: pt
      onhour: 8
      opt-out: True
      weekends: False
  actions:
    - start
```
