### ISSUE TITLE
MetricsFilter ignores "dimensions" configuration, returns 0 for invalid metric

### ISSUE THREAD

**Issue by jantman** [capitalone/cloud-custodian#1926]
I found this out because I had a policy attempting to identify RDS Clusters with 0 DatabaseConnections, but the filter doesn't appear to be working right.

```yaml
  filters:
  - {op: delete, tag: c7n-rds-cluster-no-connections, type: marked-for-op}
  - days: 14
    dimensions: [DBClusterIdentifier, Role]
    name: DatabaseConnections
    op: eq
    statistics: Maximum
    type: metrics
    value: 0
  - {key: ClusterCreateTime, op: gte, type: value, value: 14, value_type: age}
  name: rds-cluster-no-connections-stop
  resource: rds-cluster
```

However, on execution, I see that ``get_metric_statistics()`` is being called with ``'Dimensions': [{u'Name': u'DBClusterIdentifier', u'Value': 'tems-sv'}]``.

While the MetricsFilter has a [dimensions](https://github.com/capitalone/cloud-custodian/blob/master/c7n/filters/metrics.py#L59) key in the schema, that is actually completely ignored as it just calls [get_dimensions()](https://github.com/capitalone/cloud-custodian/blob/master/c7n/filters/metrics.py#L141):

```python
    def get_dimensions(self, resource):
        return [{'Name': self.model.dimension, 'Value': resource[self.model.dimension]}]
```

Even worse, the metric I'm using - DatabaseConnections on rds-cluster - doesn't *exist* with only the DBClusterIdentifier dimension. However, ``get_metric_statistics()`` is returning a 0 value.

It seems to me that either the ``dimensions`` array needs to be removed from the schema, since it's unused, or we need to actually take it into account. Ideally, we'd build the dimensions based on a hash that takes into account the model's dimension, i.e. a (rds-cluster as an example) policy containing:

```
- dimensions:
  DBClusterIdentifier: null
  Role: READER
```

Would do the "right" thing and end up with dimensions of ``DBClusterIdentifier: resource[self.model.dimension], Role: "READER"``.

**Comment by kapilt** [comment]
so dynamic values for dimensions need to be supplied by a metrics filter subclass for aurora, there's not much that can be done by done in the policy for this i agree, and we should remove that setting since its not valid per se. i have some additional work in a branch for extending the capabilities of the metrics filters (metrics index and next-next).

**Comment by jtroberts83** [comment]
I ran into this issue where the metrics aren't reporting properly and I had to pull an RDS policy and EC2 policy and they reported back 0 values when there should have actually been values pulled back.  Luckily I found the issue before it terminated customers DBs and servers :)

**Comment by rbowlby** [comment]
Is this issue relevant to the example RDS policy on the wiki?

https://www.capitalone.io/docs/usecases/rdsdeleteunused.html

```
vars:
  metrics-filters: &metrics-filter
        type: metrics
        name: DatabaseConnections
        days: 14
        value: 0
        op: equal
```

**Comment by wallabyies** [comment]
I'm using the filters below, and it will periodically (maybe 5% of runs), match on actively used databases.     Any thoughts on this? 

```yaml
filters:
  - type: metrics
    name: DatabaseConnections
    days: 30
    value: 0
    op: equal
    statistics: Sum
  - type: value
    value_type: age
    key: InstanceCreateTime
    value: 29
    op: greater-than
  - "tag:CustodianDeleteThisRDSDatabaseOn": absent 
```
Here is the run log with no changes to the policy, randomly matching on actively used databases:

```
2019-05-13 15:24:46,912 - custodian.policy - INFO - policy: rds-stale-databases resource:rds region:us-east-1 count:14 time:6.01
2019-05-13 15:28:29,274 - custodian.policy - INFO - policy: rds-stale-databases resource:rds region:us-east-1 count:14 time:6.26
2019-05-13 15:31:03,246 - custodian.policy - INFO - policy: rds-stale-databases resource:rds region:us-east-1 count:14 time:6.55
2019-05-13 15:34:24,437 - custodian.policy - INFO - policy: rds-stale-databases resource:rds region:us-east-1 count:14 time:5.85
2019-05-13 15:36:44,139 - custodian.policy - INFO - policy: rds-stale-databases resource:rds region:us-east-1 count:23 time:6.24
```
