### ISSUE TITLE
iam-role resource can not be triggered on when events don't have roleId available

### ISSUE THREAD

**Issue by twitherspoon** [capitalone/cloud-custodian#1928]
This issue is similar to issue #1480, but I'm providing additional details and use cases.

I'm looking to alert on when policies are events when a policy (both managed and inline) are attached to a role or added to an instance profile. Basically for a production environment we want to be alerted if someone is trying to elevate access to their instance profile or IAM role by adding additional IAM policies to it. We would like to trigger on the following events:
- AttachRolePolicy
- DetachRolePolicy
- PutRolePolicy
- UpdateAssumeRolePolicy
- AddRoleToInstanceProfile
- DeleteRolePolicy

Here's a snippet of what I thought would work (only have 3 events as an example:
```
policies:
- name: iam-role-update-detected
  resource: iam-role
  description: |
    Notifies on IAM Role Updates to IAM Role Policies (Managed and Inline)
  mode:
     type: cloudtrail
     role: arn:aws:iam::123456:role/CustodianLambdaRole
     events:
      - event: AttachRolePolicy
        source: iam.amazonaws.com
        ids: "requestParameters.roleName"
      - event: PutRolePolicy
        source: iam.amazonaws.com
        ids: "requestParameters.roleName"
      - event: AddRoleToInstanceProfile
        source: iam.amazonaws.com
        ids: "requestParameters.roleName"
  actions:
    - type: notify
      template: default.html
      priority_header: 1
      subject: "IAM Role Policy Update Detected in [custodian {{ account }}]"
      violation_desc: "IAM Role Policy Updates Detected"
      action_desc: |
        "Please investigate and notify the appropriate account owners to remediate this risk."
      to:
        - someone@email.com
      transport:
        type: sqs
        queue: https://sqs.us-east-1.amazonaws.com/123456/CustodianNotifications
        region: us-east-1
```

The following does not work for several reasons:
- The ids for the iam-role resource only works if you use roleId which isn't present in any of the events above
- I could change the resource for the Custodian rule to iam-policy and change the ids to requestParameters.policyArn. But that will return the iam-policy resource and I really want to know which iam role was affected. It doesn't help me to just know the policy and not the iam-role that it was attached to.

```
policies:
- name: iam-role-update-detected
  resource: iam-policy
  description: |
```
- In addition using the iam-policy as resource also does not work with inline policy events like PutRolePolicy

Question/Ask:
- Can we please add roleName as a possible id for iam-role resources? It is the only thing common in events like the ones I'm looking at not roldId.
- If you point me in the right direction where that logic can be added I can take a crack at fixing this issue.

Thanks!
