### ISSUE TITLE
lambda policies need a virtualenv installation.

### ISSUE THREAD

**Issue by frc9** [capitalone/cloud-custodian#193]
Getting the following error in the cloudwatch log stream associated with the lambda function provisioned after running a policy: 

> Unable to import module 'custodian_policy': No module named pkg_resources

using the policy below and invoking it with `custodian run -c policy.yml -s out --log-group=/cloud-custodian/dev-account/us-west-2 --region us-west-2 -m`

Is there something I'm missing that is causing the mu to not create the lambda function zip file correctly?

```yaml
policies:
- name: ec2-require-non-public-and-encrypted-volumes
  resource: ec2
  description: |
   Provision a lambda and cloud watch event target
   that looks at all new instances not in an autoscale group
   and terminates those with unencrypted volumes.
  mode:
   type: cloudtrail
   role: arn:aws:iam::XXXXXXXXXXXX:role/custodianRole
   events:
  - RunInstances
    filters:
  - "tag:aws:autoscaling:groupName": absent
  - type: ebs
    key: Encrypted
    value: false
    actions:
  - terminate
- name: tag-compliance
  resource: ec2
  description:
   Schedule a resource that does not meet tag compliance policies
   to be stopped in four days.
  filters:
  - State.Name: running
  - "tag:Environment": absent
  - "tag:AppId": absent
  - or:
    - "tag:OwnerContact": absent
    - "tag:DeptID": absent
      actions:
  - type: mark-for-op
    op: stop
    days: 4
```

**Comment by kapilt** [comment]
I haven't seen that one before. It sounds like an issue with the installed environment that's uploading. Could you provide a few more details around the machine your using to run custodian, specifically

- what python version is this?
- which os ?
- How did you install custodian? 
- Which custodian version are you using? ($ custodian version)

**Comment by frc9** [comment]
Hey - false alarm. I did a fresh install and reran my policies and this issue went away.

**Comment by kapilt** [comment]
i got a report in gitter 1x1 that
```
seems that "mu.py" was searching for "pkg_resources" in the python2.7/site-packages path, rather than python2.7/dist-packages
updating that path directive and removing the mu.pyc has made a build that works 
```

we should check both, linux distros have some variations here wrt to location on install that we should respect.

**Comment by barundel** [comment]
Hello 

Hope I can re-open this as am getting the same thing and unable to get past it based on what has already been discussed.

Error when running lambda:
`Unable to import module 'custodian_policy': No module named pkg_resources.extern`

I updated mu.py line 205 to be dist-packages but that produced the same error with .extern before it was just:

`Unable to import module 'custodian_policy': No module named pkg_resources`

I have confirmed that pkg_resources exist, tried a fresh AMI, pip install --upgrade setuptools,
pip install --upgrade distribute but no luck 

what python version is this? - 2.7.12
which os ? -  Amazon Linux AMI
How did you install custodian? - sudo pip install c7n
Which custodian version are you using? ($ custodian version) - 0.8.22.0

**Comment by kapilt** [comment]
at this time.. we need a virtualenv installation for lambda policies

**Comment by barundel** [comment]
Thanks

virtualenv was installed in usr/lib/python2.7/dist-packages but not installed to usr/local/lib/python2.7/site-packages where pkg_resources is currently 

I removed and installed it to usr/local/lib/python2.7/site-packages and rebuilt with no success 

I'm going to try and uninstall and reinstall the packages to the usr/local python, see what that does.

**Comment by vijayrcse** [comment]
Could you please suggest how to do this virtualenv installation as well ?

I am getting the same error

**Comment by barundel** [comment]
$ [sudo] pip install virtualenv

**Comment by vijayrcse** [comment]
okay thanks let me try

**Comment by vijayrcse** [comment]
it doesn't work. I did below

root@ip-10-14-15-77 ec2-user]# pip install virtualenv
You are using pip version 6.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): virtualenv in /usr/local/lib/python2.7/site-packages

i see installation files here 
[root@ip-10-14-15-77 ec2-user]# ls -lrt /usr/local/lib/python2.7/site-packages

But still get below error

Unable to import module 'custodian_policy': No module named pkg_resources

Also there is no files under
[root@ip-10-14-15-77 ec2-user]# ls -lrt /usr/lib/python2.7/site-packages/
total 0

Please advise what i am doing wrong?

**Comment by vijayrcse** [comment]
I am unable to proceed further on this.

can anyone help me how to resolve this

I ran below commands
pip install c7n
pip install virtualenv

After that i executed my policy. When i run my lambda function i get the below error

Unable to import module 'custodian_policy': No module named pkg_resources

Please advise how to resolve this issue

**Comment by barundel** [comment]
What OS are you running this on?

**Comment by vijayrcse** [comment]
Its amazon linux AMI free tier
4.4.5-15.26.amzn1.x86_64

**Comment by vijayrcse** [comment]
okay thx let me try that

**Comment by vijayrcse** [comment]
I spinned-up an Ubuntu server in Amazon and did the following

pip install virtualenv
pip install c7n

The lambda functions that is getting created still throws the below error

TART RequestId: 6d15b00a-e701-11e6-879f-891763142e64 Version: $LATEST
Unable to import module 'custodian_policy': No module named pkg_resources

END RequestId: 6d15b00a-e701-11e6-879f-891763142e64

**Comment by kapilt** [comment]
you have to create and activate the virtualenv, merely installing is not sufficient. ie 

```
$ virtualenv custodian
$ source custodian/bin/activate
(custodian)$ pip install c7n
```

**Comment by vijayrcse** [comment]
thx kapil, let me try this

**Comment by vijayrcse** [comment]
it didn't work, but i am going to re-create my ubuntu instance and do a clean installation. will let you know.

**Comment by vijayrcse** [comment]
Now i get a different error

Unable to import module 'custodian_policy': No module named packaging.version

**Comment by vijayrcse** [comment]
I just reverted back to Amazon linux AMI and it worked now ( under virtualenv)

**Comment by kapilt** [comment]
that packaging.version issue is resolved in 0.8.23.0 release

**Comment by vijayrcse** [comment]
thanks kapil will take latest release

**Comment by kapilt** [comment]
@whit537 could you have a look at this one.

**Comment by kapilt** [comment]
nutshell we need check both dist-packages/site-packages within virtualenv also some variation on linux distros.

**Comment by kapilt** [comment]
in the meantime we should update the install docs

**Comment by whit537** [comment]
> @whit537 could you have a look at this one.

Sure thing!

**Comment by whit537** [comment]
> in the meantime we should update the install docs, till this is resolved.

https://github.com/capitalone/cloud-custodian/pull/983

**Comment by whit537** [comment]
Here's the test case I've whittled down to:

### Steps

1. Spin up and login to an EC2 instance (Amazon Linux AMI free tier 4.4.5-15.26.amzn1.x86_64).
1. `sudo pip install c7n` to install globally.
1. Create file `policy.yml` with below content.
1. Populate `~/.aws/credentials`.
1. `custodian run policy.yml -s . --region us-east-1` to install a Lambda.
1. Hit the Lambda using the "test" feature in the Console.

```yaml
policies:
- name: foo
  resource: ec2
  mode:
    type: cloudtrail
    role: arn:aws:iam::644160558196:role/custodian-mu
  events:
     - RunInstances
```

### Expected 

???

### Actual

```
Unable to import module 'custodian_policy': No module named ipaddress
```
