### ISSUE TITLE
Error when trying to disable S3 Lifecycle Policy 'absent' or 'Disabled'

### ISSUE THREAD

**Issue by joshuaroot** [capitalone/cloud-custodian#1933]
When trying to leverage `configure-lifecycle` to remove a policy, the following error is returned

```
ClientError: An error occurred (MalformedXML) when calling the 
PutBucketLifecycleConfiguration operation: The XML you provided 
was not well-formed or did not validate against our published schema

```

Policy:
```
  - name: disable-bucket-lifecycle
    resource: s3
    filters:
      - type: value
        value_type: swap
        key: Lifecycle.Rules[].ID
        value: LIFECYCLE_RULE_ID
        op: in
    actions:
      - type: configure-lifecycle
        rules:
          - ID: LIFECYCLE_RULE_ID
            Status: Disabled
```
