### ISSUE TITLE
security-group ingress filters do not support both OnlyPorts and Cidr

### ISSUE THREAD

**Issue by jsvazic** [capitalone/cloud-custodian#1943]
Here's a sample policy that I've been fighting with for the past week with no success:

```
policies:
  - name: high-risk-security-groups-notify
    resource: security-group
    description: |
      Notifies if any rule from a security group that allows 0.0.0.0/0 
      ingress, not on ports 80 or 443, and notify the user who added the 
      violating rule.
    mode:
        type: cloudtrail
        role: arn:aws:iam::xxx:role/CloudCustodian
        events:
          - source: ec2.amazonaws.com
            event: AuthorizeSecurityGroupIngress
            ids: "requestParameters.groupId"
          - source: ec2.amazonaws.com
            event: AuthorizeSecurityGroupEgress
            ids: "requestParameters.groupId"
          - source: ec2.amazonaws.com
            event: RevokeSecurityGroupEgress
            ids: "requestParameters.groupId"
          - source: ec2.amazonaws.com
            event: RevokeSecurityGroupIngress
            ids: "requestParameters.groupId"
    filters:
        - type: ingress
          OnlyPorts: [80, 443]
          Cidr:
            value: "0.0.0.0/0"
    actions:
      - type: notify
        template: default.html
        priority_header: 1
        subject: "Open Security Group Rule Created-[custodian {{ account }} - {{ region }}]"
        violation_desc: "Security Group(s) Which Had Rules Open To The World:"
        action_desc: |
            "Actions Taken:  The Violating Security Group Rule Violates Our Company's 
            Cloud Policy.  Please Refer To The Cloud FAQ."
        to:
          - event-owner
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/xxx/cloud-custodian-mailer
          region: us-east-1
```

I've tried using `-and` when defining the filter conditions, but that didn't seem to make a difference.

**Comment by jhnlsn** [comment]
I setup my sg like this and then ran your filter against the account.
![screen shot 2018-01-17 at 2 22 10 pm](https://user-images.githubusercontent.com/137058/35062325-f15fabbe-fb91-11e7-8e91-200da689d064.png)

Here is my simplified policy:
```yaml
policies:
  - name: github-1943
    resource: security-group
    filters:
      - type: ingress
        OnlyPorts: [80, 443]
        Cidr:
          value: "0.0.0.0/0"
```

That returns the security group.  Is that not what you are expecting or are you not getting the same result?

**Comment by kapilt** [comment]
we were discussing this over gitter before it was filed. i think the crux was that it was applying as an `or` instead of an `and`, looking at the implementation its hardwired for `or`, for most multi attribute filters like this we typically specify a `match-operator` that allows specifying `or|and`

**Comment by jsvazic** [comment]
@jhnlsn It's close, but not quite the same.  Using your example if I were to create another rule for TCP/80 or TCP/443 for 0.0.0.0/0, I *should not* get a notification, but I do.  That's where @kapilt's comment comes into play.  I need an `and` condition for the `Cidr` and `OnlyPorts` condition, i.e. the Cidr is 0.0.0.0 AND it is for any port EXCEPT 80 or 443.

The reasoning is that I'm trying to ensure only web ports are open to the world, and no other port should be.

**Comment by kapilt** [comment]
working on this now.. i have to admit, i find the default or behavior incredibly confusing and i'm wondering if we should change it to 'and' by default.

**Comment by thomasbiddle** [comment]
> Notifies if any rule from a security group that allows 0.0.0.0/0 
>       ingress, not on ports 80 or 443, and notify the user who added the 
>       violating rule.

So how would this work now after all the changes? Everything I've tried breaks in one manner or another.

**Comment by karthikeayan** [comment]
i am looking for an yaml sample to achieve this

**Comment by arafatheds** [comment]
I am still have this problem, I am trying to notify if any rule from a security group that allows 0.0.0.0/0
ingress, not on ports 80 or 443. But it notifies for all..

    filters:
      - and:
        - type: ingress
          OnlyPorts: [80,443]
        - type: ingress
          Cidr:
            value: 0.0.0.0/0

**Comment by karthikeayan** [comment]
@arafatheds remove the and

**Comment by kapilt** [comment]
you need to combine the two ingress filters. you want a single ingress filter to match on *ALL* the attributes of a single permission, not partial.

ie.
```
filters:
    - type: ingress
      OnlyPorts: [80,443]
      Cidr:
        value: 0.0.0.0/0
```
