### ISSUE TITLE
WIP - Add API Gateway (rest-api resource) Enable CW Logging filter and action.

### ISSUE THREAD

**Issue by jtroberts83** [capitalone/cloud-custodian#1947]
Some Cloud Team peers and I will be working to get this code put in with a possibility of a little help from Kapil and maybe Alfred.  The use case being that any time a new API is created or a c7n poll scan is ran it can identify API Gateway APIs which have Stages without CloudWatch Logging enabled or where the Logging level is set to OFF or ERROR.  Then the c7n policy would need to check and verify that a CW Role is specified in the API Gateway Settings for that account and region and if the CW role is missing the role from the policy is extracted and applied.  Once proper CW role is applied to the API Gateway settings it would enable CW logging on all stages from the filter set and turn logging level to users choice (INFO in our case).  I imagine the policy looking something like the following:

```
- name: api-gateway-enable-cw-logging-poll
  resource: rest-api
  filters:
     - or:
         - LoggingLevel: OFF
         - LoggingLevel: ERROR
         - LoggingEnabled: false
  actions:
     - type: enable-logging
       enabled: true
       logging-level: "INFO"
       logging-role: "arn:aws:iam::{{ account }}:role/APIGatewayLoggingRole"



- name: api-gateway-enable-cw-logging-realtime
  resource: rest-api
  mode:
     type: cloudtrail
     events:
        - source: aws.apigateway
          event: UpdateStage
          ids: "requestParameters.restApiId"
        - source: aws.apigateway
          event: CreateDeployment
          ids: "requestParameters.restApiId"
  filters:
     - or:
         - LoggingLevel: OFF
         - LoggingLevel: ERROR
         - LoggingEnabled: false
  actions:
     - type: enable-logging
       enabled: true
       logging-level: "INFO"
       logging-role: "arn:aws:iam::{{ account }}:role/APIGatewayLoggingRole"

```

The Python API calls are as follows:
 
Check to see if a CW Logging Role is set (Required to enable logging)

```
response = restclient.get_account()
```

Response Syntax:

```
{
    'cloudwatchRoleArn': 'string',
    'throttleSettings': {
        'burstLimit': 123,
        'rateLimit': 123.0
    },
    'features': [
        'string',
    ],
    'apiKeyVersion': 'string'
}
```

Then if the role is missing it would need to grab the logging-role specified in the policy and set it to a variable for ex: loggingrole  and then apply it with:

```
response = restclient.update_account(
    patchOperations=[
        {
            'op': 'replace',
            'path': '/cloudwatchRoleArn',
            'value':  loggingrole,
        },
    ]
)
```

Once the CW Logging Role has been confirmed or set it will need to see if logging is currently enabled for the stages associated with each API with the following command:

```
response = restclient.get_stages(
    restApiId=id,
)
```

With Response Syntax (reduced to applicable items):

```
{
    'item': [
        {
            'deploymentId': 'string',
            'stageName': 'string',
            'description': 'string',
            'methodSettings': {
                    'loggingLevel': 'string',
                    'dataTraceEnabled': True|False,
                }
            },
            'tags': {
                'string': 'string'
            },
        },
    ]
}
```

Then with the response it needs to pull in:

```
LoggingEnabled = item[]['methodSettings']['*/*']['dataTraceEnabled']
LoggingLevel = item[]['methodSettings']['*/*']['loggingLevel']
```

to see if logging is enabled (true|false) and to see what level (OFF | ERROR | INFO)
Then to apply different logging settings (Enable Logging and set level to INFO in the following example) the command would be:

```
            response = restclient.update_stage(
                restApiId=id,
                stageName=stageName,
                patchOperations=[
                    {
                        'op': 'replace',
                        'path': '/*/*/logging/dataTrace',
                        'value': 'true'
                    },
                    {
                        'op': 'replace',
                        'path': '/*/*/logging/loglevel',
                        'value': 'info'
                    },
                ]
            )
```

**Comment by kapilt** [comment]
here's a policy for the stage update, per the pr in #1955,  there's a separate rest-account update that is also supported.

```
  - name: api-stage
    resource: rest-stage
    filters:
      - type: value
        key: 'methodSettings."*/*".loggingLevel'
        value: absent
    actions:
      - type: update
         patch: 
           - op: replace
             path: "/*/*/logging/dataTrace"
             value: "true"
           - op: replace
             path: "/*/*/logging/loglevel"
             value: "info"
```
