### ISSUE TITLE
provisioning lambda to vpc appears to be broken still

### ISSUE THREAD

**Issue by aardvarq** [capitalone/cloud-custodian#1953]
Hi,

I've tested https://github.com/capitalone/cloud-custodian/pull/1919.

I see the validation now passes, but it looks like the vpc attributes are not being passed when the lambda is created.

Policy:
```
policies:
- name: vpc-test-sandbox
  resource: ec2
  mode:
    type: config-rule
    role: arn:aws:iam::{{ACCOUNT}}:role/service-role/tscloud_lambda_role
    timeout: 180
    security_groups: [sg-ea399290]
    subnets: [subnet-3c3d8367,subnet-a09275c6,subnet-278bb56e]
  description: |
    Testing vpc provisioning
  filters:
    - "tag:c7n_testing": present
  actions:
    - type: mark-for-op
      tag: c7n_tag_compliance
      op: terminate
      days: 1
```

Deploy:
```
$ custodian run -s /tmp/c7n --cache-period 0 vpc-test.yml 
2018-01-18 07:48:42,873: custodian.policy:INFO Provisioning policy lambda vpc-test-sandbox
2018-01-18 07:48:43,233: custodian.lambda:INFO Publishing custodian policy lambda function custodian-vpc-test-sandbox
```
 
Get function vpc config:
```
$ aws lambda get-function --function-name custodian-vpc-test-sandbox | jq '.Configuration.VpcConfig'
null
Expected result:

$ aws lambda get-function --function-name custodian-vpc-test-sandbox | jq '.Configuration.VpcConfig'
{
  "SubnetIds": [
    "subnet-3c3d8367",
    "subnet-a09275c6",
    "subnet-278bb56e"
  ],
  "SecurityGroupIds": [
    "sg-ea399290"
  ],
  "VpcId": "vpc-d3519bb5"
}
```

The role I'm using has access to vpc provisioning, as far as I can tell, using the canned AWS Policy AWSLambdaVPCAccessExecutionRole. I'm able to use the role to add vpc config manually after provisioning with c7n.
