### ISSUE TITLE
Mailer notifying iam role event-owner

### ISSUE THREAD

**Issue by jtroberts83** [capitalone/cloud-custodian#1966]
For example the following policy will trigger and delete public or unencrypted ES Domains but it doesn't pickup the event owner of the CloudTrail event so the customer never gets notified that their Domain was deleted and therefore making this policy unusable for us as we HAVE to communicate to customers when we do something with their resources.  Please assist
```
- name: elasticsearch-delete-unencrypted-or-public-real-time
  resource: elasticsearch
  description: |
    "If a public facing or unencrypted Elasticsearch domain is launched it will be deleted
    and the customer will receive an email notifying them of the non-compliance and deletion of the ES domain."
  mode:
    type: cloudtrail
    events:
        - CreateElasticsearchDomain
  filters:
    - or:
        - type: value
          key: "EncryptionAtRestOptions.Enabled"
          value: false
        - type: value
          key: VPCOptions
          value: absent
  actions:
    - type: auto-tag-user
      tag: CreatorName
    - type: notify
      template: AGTdefault.html
      priority_header: 1
      subject: "ES - New Public or Unencrypted Elasticsearch Domain Non-Compliant - [custodian {{ account }} - {{ region }}]" 
      violation_desc: |
        "The following Elasticsearch Domain that you launched is either
        NOT in VPC mode or is NOT encrypted as required per company policy!"
      action_desc: |
        "Actions Taken:  The Elasticsearch Domain is required to be encrypted and not public facing.
        Your domain may be acted on in the near future.  Please delete this domain and launch a new Elasticsearch
        Domain in VPC mode using encryption and delete this non-compliant Domain."
      to:
         - CloudCustodian@Company.com
         - event-owner
      transport:
           type: sqs
           queue: https://sqs.us-east-1.amazonaws.com/XXXXXXXXXXXXX/cloud-custodian-mailer
           region: us-east-1
    - delete
```
