### ISSUE TITLE
feature request: optional vpc parameters in c7n-org's accounts.yml

### ISSUE THREAD

**Issue by aardvarq** [capitalone/cloud-custodian#2043]
What: provide vpc configuration (subnets and security groups) at the config level instead of the policy level
Where: c7n-org's `accounts.yml` file
Why: to further abstract policy data, resulting in fewer redundant lines of code

Unless I'm misunderstanding the status quo, I need to specify subnets and sgs in each policy file. This means less policy files or more redundant code. Our preference is to separate policies into multiple files, thus we are repeating the vpc config in each file. Additionally, we need to maintain identical policy files across regions and accounts with the only delta being the vpc config. 

This might be a nice approach:

[ accounts.yml ]
```
accounts:
- account_id: 'XXXXXXXXXXXX'
  name: myaccount-east
  role: arn:aws:iam::XXXXXXXXXXXX:role/custodian
  regions:
  - us-east-1
  vpc:
    security_groups:
      - sg1 
      - sg2 
    subnets:
      - subnet1
      - subnet2
```

In fact, might we ultimately imagine the account name(s) as an option in the policy block, gradually merging org functionality into the base?

[ policy.yml ]
```
policies:
- name: config_ec2_terminate-invalid-tags
  resource: ec2
  mode:
    type: config-rule
    timeout: 180
  accounts:
    - myaccount-east
    - myaccount-west
```

**Comment by thisisshi** [comment]
You can use variable interpolation (`account_id` and `region`) and a separate variables file to use one set of policies for multiple accounts:

```yaml
vars:
  accounts-metadata: &accounts-metadata s3://some-bucket/accounts-metadata.json # can also be a local file or url

policies:
  - name: ec2-invalid-vpc
    description: filters in ec2 instances that are operating in a non-whitelisted vpc
    resource: ec2
    filters:
      - type: value
        key: vpc
        value_from:
          url: *accounts-metadata
          format: json
          expr: metadata."{account_id}"."{region}".vpc_id
        op: ne
```


`accounts-metadata.json`:
```json
{
  "metadata": {
    "123123123123" : {
      "us-east-1": {
        "vpc_id": "vpc-123123123"
        }
      }
  }
}

```
