### ISSUE TITLE
Filter on multiple regex

### ISSUE THREAD

**Issue by timbo256** [capitalone/cloud-custodian#2044]
I am trying to create a policy which pulls out an Security Groups which do not have a user supplied Description, ie with a filter on Description  which either starts with "launch-wizard" or is "default VPC security group".
I can make it work for each in turn (used regex) but struggling with getting both filters in one policy.
Suggesetion on filter syntax would be helpful.

**Comment by thisisshi** [comment]
This should work:

```
filter:
  - type: value
    key: Description
    value: (launch-wizard.*|default VPC security group)
    op: regex
```

matches on:

```
launch-wizard asdf

default VPC security group
```
