### ISSUE TITLE
How can i filter S3 bucket by retention policy?

### ISSUE THREAD

**Issue by dharaghodasara** [capitalone/cloud-custodian#2056]
I want to send notification of S3 buckets in which 30 days expiration policy is not set.

**Comment by thisisshi** [comment]
you can filter on the Lifecycle key on a bucket, this will give you all the lifecycle rules attached to the bucket

```yaml
policies:
  - name: s3-lifeycycle-filter
    comment: |
      filters in any bucket with a Lifecycle rule
      which has a expiration policy of less than 30 days
    resource: s3
    filters:
      - type: value
        key: min(Lifecycle.Rules[].Expiration.Days)
        value: 30
        op: lt
```

the `key` is a jmespath expression. docs: http://jmespath.readthedocs.io/en/latest/index.html
