### ISSUE TITLE
S3 Encryption policy giving error (AccessDenied) when calling the Copyobject

### ISSUE THREAD

**Issue by Krishna1408** [capitalone/cloud-custodian#2071]
Hi Team,

I am running cloud custodain s3 policy from a instance in Frankfurt (eu-central-1)  region. I found that the policy is giving error of buckets in other regions e.g. Ohio in US.

**Policy:**
``` YAML
policies:
  - name: s3-key-encryption
    resource: s3
    actions:
      - type: encrypt-keys
        crypto: aws:kms

```

**Command:** 
`AWS_ACCESS_KEY_ID=$1 AWS_SECRET_ACCESS_KEY=$2 custodian run --output-dir=. --region all custodian.yml`
>> 2018-03-02 06:35:51,260: custodian.s3:ERROR Exception Processing bucket:cvstesloggingbuckets-388376138984-eu-central-1 key batch An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
None

Can you please let me know How I can proceed with this?
