### ISSUE TITLE
vaule_type: age does not appear to be working with date value in tag

### ISSUE THREAD

**Issue by sw97272** [capitalone/cloud-custodian#2118]
I am trying to get either the expiration or age value_type to work with a tag that has a date value. So, the format of the tag value is something along the lines of "2017-02-31".  However, if I try something like:

```
policies:
- name: check-ManagedBy-tag
  resource: ec2
  filters:
  - State.Name: running
  - type: value
    key: 'tag:ManagedBy'
    op: greater-than
    value_type: age
    value: 0
```

which as far as I can tell, should report instances that have a ManagedBy tag that has a date older than now. It is reporting a 0 count.  I have also tried the format for the value of ManagedBy to be "2017/02/31" but get the same result.
