### ISSUE TITLE
S3 buckets that have Condition absent

### ISSUE THREAD

**Issue by caversa** [capitalone/cloud-custodian#2125]
We are desiring to flag public buckets.  I'm using the global-grants functionality for the ACL check, and I also look at the policy where the principal = '*'.  However, my policy was capturing non-public buckets, due to the fact that the policy had an associated condition specifying IP addresses.  Although maybe not perfect, I thought I could handle that use case by excluding policies that had a condition, like below, but that functionality is not supported.  I'm interested in hearing your feedback on whether that might be something supported in the future?  Or is there a better way to do this that I'm not understanding?

Thanks,
Carrie

```
 filters:
    - or:
      - type: global-grants
      - type: has-statement
        statements:
          - Effect: 'Allow'
            Principal: '*'
            Condition: absent
..
```

**Comment by kapilt** [comment]
the cross-account filter has the desired functionality here wrt to examining bucket policies, wrt to checking for access and evaluating and whitelisting conditions.

**Comment by caversa** [comment]
Thanks for the tip, Kapil.  I've tested it with this now, and it appears to be working as desired.

```
  filters:
    - or:
      - type: global-grants
      - type: cross-account
        everyone_only: true
```
