### ISSUE TITLE
[Question] how is the order of execution of multiple policies be enforced or if there is any order gurantee?

### ISSUE THREAD

**Issue by etsangsplk** [capitalone/cloud-custodian#2146]
does  cloud custodian gurantee the order of execution of policies?

**Comment by thisisshi** [comment]
Custodian will execute the policies in the policy file sequentially

```yaml
policies:
  - name: policy-1
  ...
  - name: policy-2
...
```
