### ISSUE TITLE
Add Policy tags: and accounts: filter fields

### ISSUE THREAD

**Issue by jtroberts83** [capitalone/cloud-custodian#2198]
When running c7n-org run it allows you to specify --tags type:Non-Prod for example and then it only runs against the accounts in the config file which are tagged as type:Non-Prod. I was wondering if that could be done at a policy level? For example:
```
- name: ec2-non-prod-policy
  resource: ec2
  tags: ["type:Non-Prod"]
  filters:
      - "tag:SomeTag"
  actions:
      - stop
```
^ that policy would only execute against accounts with the Non-Prod tag in the config file. 
or filtering on accounts:
```
- name: ec2-specified-accounts-policy
  resource: ec2
  accounts: ["account_alias1","account_alias2"]
  filters:
      - "tag:SomeTag"
  actions:
      - stop
```
^ that policy would only execute against accounts named account_alias1 and account_alias2. 

or if just tags was added then I could always just create a tag with the account alias name on it which would do the same thing as the accounts: filter I believe

That way I don't have to maintain a separate policy file for different account types and all policies can be within 1 file and execute faster
