### ISSUE TITLE
Filter using regex is not returning any values

### ISSUE THREAD

**Issue by timbo256** [capitalone/cloud-custodian#2283]
I am running a policy against EC2 resources with a filter to do a partial match on the Security Groups configured of the instances, to ensure a specific SG is configured for the instances:
policies:

```yaml
  - name: ec2-sgs
    resource: ec2
    filters:
      - type: value
        key: "SecurityGroups[].GroupName"
        op: regex
        value: \S*NexposeScanTargetsSG\S*
```
I have four instances which should match on a groupname of Rapid7ScanEngineEC2Instance-NexposeScanTargetsSG-xxxxxxxxxxxxx. 
Two with a single SG of that name and two where this SG is the second value in the key. 
If use SecurityGroups[].GroupName or SecurityGroups[*].GroupName then there is no match but if use SecurityGroups[0].GroupName or SecurityGroups[1].GroupName then the two that match this item in the array are returned. 
Is this right?
If I test using the following filter specifying the full SG value and 'contains' then returns all 4 instances

```yaml
    filters:
      - type: value
        key: "SecurityGroups[].GroupName"
        op: contains
        value: "Rapid7ScanEngineEC2Instance-NexposeScanTargetsSG-xxxxxxxxxxxxx"
```

**Comment by timbo256** [comment]
For info - I made this work by using the following filter
```
    filters:
        - type: security-group
          key: GroupName
          op: regex
          value: \S*NexposeScanTargetsSG\S*
```
