### ISSUE TITLE
Filter based on subnet tag 

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2310]
This is somewhat related to #2257 but of a different variant.

The use case is as follows:

Development and test users are not allowed to launch instances on any subnets that route through an Internet Gateway.  Such instances must route traffic through a NAT Gateway.

I was hoping I could filter subnets attached to EC2 instances based on a tag for the subnet where the subnet tag would contain a string "public" or "private" in them. The assumption is all subnets would be primed with such a tag. Unfortunately, I haven't had much luck filtering on tags associated to a subnet attached to an EC2 instance  (versus the Name tag associated with the EC2 instance itself).
 
Is there a better approach that would result in the desired outcome?

**Comment by kapilt** [comment]
the `type: subnet` filter can be used on network attached resources to filter resources based on the attributes of the network they are attached to .. ie

```
- policies:
   - name: ec2-net
      resource: ec2
      filters:
        - type: subnet
           key: "tag:Location"
           value: "Internet"
    actions:
       - stop
```

ie to stop all instances in subnets with a given tag key/value.
