### ISSUE TITLE
Collection size in filters

### ISSUE THREAD

**Issue by blytheaw** [capitalone/cloud-custodian#232]
Hey!

I think it would be really useful to be able to examine/compare collection sizes in filters. The idea is that the size of the collection could be used in conjunction with the existing comparison operators in filters.

Example:
```
filters:
      - type: collection-size
        key: "Attachments[]"
        value: 1
        op: gt
``` 

Sample use cases:
- # Attached volumes
- # Instances in ASG
- # SGs on an instance

Thoughts on this?

**Comment by kapilt** [comment]
sounds great, there's also discussion of a more generic facility in #147 via a value_type  for giving some guidance on conversion of values prior to comparison.

**Comment by kapilt** [comment]
implemented in #300 


example

```yaml
filters:
      - type: value
        value_type: size
        key: "Attachments[]"
        value: 1
        op: gt
```
