### ISSUE TITLE
Specify event source only for cloudtrail mode.

### ISSUE THREAD

**Issue by marvinestreet** [capitalone/cloud-custodian#2329]
I was wondering if there a way to specify cloudtrail events by source-only. I tried the below configuration as a test:

```
policies:
  - name: cloudtrail-testing
    resource: iam-user
    mode:
      type: cloudtrail
      role: arn:aws:iam::<account_number>:role/cloud-custodian-lambda-role
      events:
        - source: "iam.amazonaws.com"
          event: "*"
          ids: "*"
```

but it didn't work until I manually went into AWS and modified the Cloudwatch Rule to look like this:

```
{
  "source": [
    "aws.iam"
  ]
}
```

Is there a way to replicate the second one in the custodian policy?

Thanks
