### ISSUE TITLE
S3 metrics retrieving incorrect results

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#2336]
Policy used
```
policies:
  - name: s3-not-used
    resource: s3
    region: us-east-1
    filters:
      - not:
        - type: metrics
          name: NumberOfObjects
          statistics: Average
          days: 14
          period: 86400
          value: 0
          op: greater-than
```
**Intention :** Trying to find unused buckets by querying CW metrics that have Objects count not increased in last 14 days. 
**Issue:** Showing buckets that are in west for which there are no CW logs in East. Due to this c7n pulling false positives.

**Comment by kapilt** [comment]
Because s3 buckets are global in discovery, simply using a policy region limit isn't sufficient, you need to filter the buckets by their location constraint to have the matching region to pick up cw metrics.

**Comment by kapilt** [comment]
although I'm curious why it would show false positives given the policy here is looking for things with a non zero value. I'll try it out locally.

**Comment by kumarsiyer** [comment]
Testing using location constraint

**Comment by kumarsiyer** [comment]
Nope, same results. Ran the same policy like this 

`custodian run -c s3-not-used.yaml -s out --cache-period 0 --dryrun -v --region us-east-1`

**Comment by kumarsiyer** [comment]
Yep that worked @kapilt thanks. Used location constraint

```
policies:
  - name: s3-not-used
    resource: s3
    region: us-west-2
    filters:
      - or:
          - Location.LocationConstraint: us-west-2
          # - Location.LocationConstraint: null    
      - not:
        - type: metrics
          name: NumberOfObjects
          statistics: Average
          days: 14
          period: 86400
          value: 0
          op: greater-than
```
