### ISSUE TITLE
How to detect unused application-elbs reliably?

### ISSUE THREAD

**Issue by zfLQ2qx2** [capitalone/cloud-custodian#2354]
I'm having a tough time trying to get Cloud Custodian to flag unused application ELBs, after some Googling I'm trying this approach:
```
  - name: find-unused-app-elb
    resource: app-elb
    filters:
      - type: metrics
        name: ConsumedLCUs
        days: 1
        period: 86400
        op: eq
        value: 0
```
I've confirmed that this metric exists in cloudwatch for my test app-elb, however when run the rule gets this error:

018-05-08 13:54:42,469: custodian.filters:WARNING CW Retrieval error: Parameter validation failed:
Invalid type for parameter Dimensions[0].Name, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>

I'm not sure how to correct that or even if this is the best approach, I could use some advice.
