### ISSUE TITLE
Policy management across accounts and regions

### ISSUE THREAD

**Issue by neybar** [capitalone/cloud-custodian#2380]
I apologize if I missing something simple.  I'm just dipping my toes in cloud custodian.  A fellow dev has setup some rules in a test account and now we want to move forward and put these in place across all our accounts (10+), and across various regions (us-east-1, us-west-1 for example).

I've been poking through the issues and pull-requests and I see people talking about variable interpolation, but I'm not seeing any documentation on how to do it.

Few questions:

1.  Is there an easy way to swap in variables.  And is there a list of available variables somewhere? (this is just snippets of a policy, it isn't meant to be complete):

```yaml
mode:
  role: arn:aws:iam::{account_id}:role/acct-managed/CustodianElbS3LoggingRole
  ...
actions:
  - type: set-s3-logging
     state: enabled
     bucket: {account_name}-{region}-logs
 ...
    transport:
       type: sns
       topic: arn:aws:sns:{region}:{account_id}:cloud-custodian-notify
       region: {region}
```

My brain is in Terraform mode, so I'm kind of hoping there is some sort of analog to a vars file or tfvars.

2.  How are people managing policies across different kinds of accounts?  I may have three different accounts (dev/qa/prod) with different needs, and then times that by $n where each $n is a different context.  So I want to have my dev rules applied to each dev account and so on.  I'd like to keep my policies as DRY as possible, but I'm not seeing a great way to manage all that.

3.  With in an account can I roll a policy that will watch all regions?  Or do I need to apply the policy to each region?  Eg:  I have a policy that says sg ingress to port 22 from 0.0.0.0/0 is forbidden, and I want to enforce that across all regions.
