### ISSUE TITLE
AWS shield - sync action is acting on false positive resources 

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#2416]
**Policy**
```
  - name: shield-protection-elb
    resource: elb
    filters:
      - type: value
        key: Scheme
        value: internal
        op: not-equal
      - type: shield-enabled
        state: false
    actions:
      - type: set-shield
        state: true
        sync: true
```
Problem - While trying to enable shield protection on resources that are region specific and have a sync = true on the policy the resources that are added to shield are removed when the policy runs on the next region. For eg: you have 10 resources in us-east-1 that are added to shield, when you run the above policy in west-2 to add resources custodian removes the resources in east-1 because they are not available in west-2
