### ISSUE TITLE
Custom Slack URL Capability

### ISSUE THREAD

**Issue by RecursiveLooper1992** [capitalone/cloud-custodian#2427]
Again this is a great product and thank you for writing this!

We were wondering if it would be possible to allow a custom Slack URL Configuration?

For example, extending this capability out to MatterMost or a private Slack instance.

Right now the code is hard-coded to use ```slack.com```.

Let me know if you need any more details.

Thank You!

**Comment by GarHub0525** [comment]
Noticed in the doc for c7n-mailer that incoming webhooks is supported.  Could this be used for MatterMost which is slack compatible?  

- slack://#custodian-test
 - slack://webhook/#c7n-webhook-test

**Comment by thisisshi** [comment]
@GarHub0525 No, it doesn't, as of now we're checking if the webhook starts with hooks.slack.com, that should be easy to modify to make it applicable for Mattermost

**Comment by KeerthigaKrishnan** [comment]
Hi, 

I have created a slack app and using webhook url to send notify to our slack channel other than custodian-test. But I am not getting any error in cloudwatch and notification is not received..

**Comment by thisisshi** [comment]
@KeerthigaKrishnan what do the mailer logs say?

**Comment by sampritavh** [comment]
@KeerthigaKrishnan 
I think we need to set up something like `slack_webhook: https://hooks.slack.com/services/abcde/abcde/abcdefgh` in mailer.yml and then configure slack webhook in your policy file . This isn't mentioned in the documentation though.  Had to look into the code. 
So my **mailer.yml** file will look like this 
```yml
queue_url: https://sqs.us-east-1.amazonaws.com/12345678900/c7n-mailer-test
role: arn:aws:iam::12345678900:role/c7n-mailer-test
slack_webhook: https://hooks.slack.com/services/abcde/abcde/abcdefgh
```
A sample policy file will be like 
**test-policy.yml**
```
policies:
  - name: c7n-mailer-test
    resource: sqs
    filters:
    - "tag:SlackTest": absent
    actions:
      - type: notify
        slack_template: slack
        to:
          - slack://webhook/#c7n-test
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/12345678900/c7n-mailer-test
```
