### ISSUE TITLE
How to filter on EC2 instance limits

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2470]
The following [document](https://www.capitalone.io/docs/usecases/accountservicelimit.html) suggests there's a way to filter based on resource limits.

How would one go about filtering based on specific instance types?

For example, last night we reached 25/25 of p3.16xlarges in us-east-1 and would like to create a policy that alerts us when we're near it the next time as well as for a list of other specific instance types.

**Comment by davidclin** [comment]
OK to close.  

I read through the man page for `custodian schema account.filters.service-limit` and ran the following policy just for grins:

```
policies:
  - name: account-service-limits
    resource: account
    filters:
      - type: service-limit
        services:
          - EC2
        threshold: 1.0

```
only to discover:

`ClientError: An error occurred (SubscriptionRequiredException) when calling the DescribeTrustedAdvisorCheckResult operation: AWS Premium Support Subscription is required to use this service.
`
which we don't have at the moment. 

Will likely try it out in the future.
