### ISSUE TITLE
Security-group ingress rule to filter OnlyPorts

### ISSUE THREAD

**Issue by ctippur** [capitalone/cloud-custodian#2484]
Use case: 

```
Green: Access to port 80, 25, 443, or 465 is unrestricted.
Red: Access to port 20, 21, 1433, 1434, 3306, 3389, 4333, 5432, or 5500 is unrestricted.
Yellow: Access to any other port is unrestricted.
```

```
- filters:
  - type: ingress
    OnlyPorts: [443]
    Cidr:
      value_type: cidr
      op: eq
      value: "0.0.0.0/0"
```

The above filter resulted in 
```

 "IpPermissions": [
      {
        "FromPort": 443,
        "IpProtocol": "tcp",
        "IpRanges": [
          {
            "CidrIp": "0.0.0.0/0"
          }
        ],
        "Ipv6Ranges": [],
        "PrefixListIds": [],
        "ToPort": 443,
        "UserIdGroupPairs": []
      }
    ]
```

and corresponding matched ip permissions

```
"MatchedIpPermissions": [
      {
        "FromPort": 443,
        "IpProtocol": "tcp",
        "ToPort": 443,
        "IpRanges": [
          {
            "CidrIp": "0.0.0.0/0"
          }
        ],
        "Ipv6Ranges": [],
        "PrefixListIds": [],
        "UserIdGroupPairs": []
      }
    ]
```
Please correct me if I am wrong. Since I am using OnlyPorts, I was expecting other ports to appear in the resources.json. I am referencing the second example in http://capitalone.github.io/cloud-custodian/docs/azure/policy/resources/nsg.html

**Comment by krmckone** [comment]
We're having the same issue but wasn't #1954 meant to fix this? When I only have OnlyPorts in the filter, it works as it should. However, when coupled with Cidr, OnlyPorts fails to provide any function to the filter.

**Comment by timbo256** [comment]
I had a similar issue - seems to work okay if 'separate' the filters a la:
```
     - type: ingress
       OnlyPorts: [80, 443]
     - type: ingress
       Cidr:
          value_type: cidr
          op: eq
          value: 0.0.0.0/0
```
