### ISSUE TITLE
Unresolved issue with group filter when run as Lambda

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2527]
This is related to #2472. 

Something broke recently. 

The following policy is producing errors again when run as a Lambda.
<details>
<summary>Example.yml</summary>

<pre>
policies:
  - name: mfa-audit-reminder
    description: Cloud Custodian MFA Audit Notification
    comment: |
      Retrieve list of all IAM users with MFA disabled
      in the group 'Administrators' and send notification
      if MFA is not enabled after 3 days of the create date.
      Send notification via SES and Slack.
    resource: iam-user
    mode:
        type: periodic
        role: arn:aws:iam::929292782238:role/CloudCustodian
        schedule: "rate(5 minutes)"
    filters:
      - type: credential
        key: mfa_active
        value: false
      - type: group
        key: GroupName
        value: CloudCustodianAdmins
      - type: value
        key: CreateDate
        op: less-than
        value_type: age
        value: 3
    actions:
      - type: notify
        template: mfa-audit-reminder.html
        template_format: 'html'
        slack_template: slack-mfa-audit-reminder
        priority_header: '5'
        subject: 'Security Audit: IAM users in Administrators group with MFA Disabled'
        to:
          - email@domain.com
          - slack://#myslackchannel
        owner_absent_contact:
          - group@domain.com
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/1234567890/cloud-cloudcustodian
</pre>
</details>

<details>
<summary>CloudWatch Logs</summary>

<pre>
[ERROR]	2018-06-15T23:38:42.952Z	3cb9ad71-70f5-11e8-a714-cb331a3551ca	Error while executing policy
Traceback (most recent call last):
File "/var/task/c7n/policy.py", line 222, in run
resources = self.policy.resource_manager.resources()
File "/var/task/c7n/query.py", line 421, in resources
return self.filter_resources(resources)
File "/var/task/c7n/manager.py", line 90, in filter_resources
resources = f.process(resources, event)
File "/var/task/c7n/resources/iam.py", line 947, in process
for p in r['c7n:Groups']:
KeyError: u'c7n:Groups'
</pre>
</details>

Policy is fine when run locally.

```
(c7n_mailer) $ custodian run -s output foo.yml
2018-06-15 23:47:12,198: custodian.policy:INFO policy: mfa-audit-reminder resource:iam-user region:us-east-1 count:2 time:0.38
2018-06-15 23:47:12,330: custodian.actions:INFO sent message:0aa6358b-03d3-4b9c-bc65-04d7bfaa302c policy:mfa-audit-reminder template:mfa-audit-reminder.html count:2
2018-06-15 23:47:12,331: custodian.policy:INFO policy: mfa-audit-reminder action: notify resources: 2 execution_time: 0.13
```

I'm using a clean install from a new instance using the latest clone from master and able to reproduce. I noticed this problem earlier this week but didn't have time to report it.  I'm using a cron job as a workaround but it's not ideal.

**Comment by kapilt** [comment]
Thanks for reporting the issue and the pr.

**Comment by davidclin** [comment]
Sorry for not clarifying. The issue observed is the group filter used with the lambda cron policy. I haven't tested with the event based lambda policy as I don't have a use case for it yet. Hope that helps.

**Comment by davidclin** [comment]
Is there anymore information needed? If so, I'm more than happy to provide.

**Comment by kapilt** [comment]
@thisisshi could you have a look at this?

**Comment by thisisshi** [comment]
@davidclin have you updated the lambda since the fix went in for #2472? the lambda may be running an outdated version of c7n, if it works locally it should work in the lambda as well as deps are packaged with mu from the virtualenv on the local machine you're deploying from. Rather than pip installing custodian to get the bug fixes that were implemented in #2454 do a developer install as outlined in the readme to get the latest version in the lambda. 

I wasn't able to recreate the error but let me know if it persists after upgrading to the latest version in master.

**Comment by davidclin** [comment]
I upgraded to the latest version in master following the developer install as outlined in the README.md. 

Oddly, the errors are gone but the CloudWatch error log is showing **0 count** against the filter:

`[INFO]	2018-07-02T23:19:36.684Z	61f62496-7e4e-11e8-839c-3b304c445e1c	policy: mfa-audit-disable-access resource:iam-user region:us-east-1 count:0 time:1.52`

But when I do a --dryrun, I get a match:

```
2018-07-02 23:20:31,168: custodian.policy:INFO policy: mfa-audit-reminder resource:iam-user region:us-east-1 count:0 time:4.03
2018-07-02 23:20:34,882: custodian.policy:INFO policy: mfa-audit-disable-access resource:iam-user region:us-east-1 count:1 time:3.71
```

```
(c7n_mailer) $ custodian report -s output mfa-audit.yml --format grid
+------------------------+---------------------------+--------------------------+
| UserName               | CreateDate                | Policy                   |
+========================+===========================+==========================+
| david.lin.ctr-mfa-user | 2018-06-13T22:50:17+00:00 | mfa-audit-disable-access |
+------------------------+---------------------------+--------------------------+
```

**Comment by davidclin** [comment]
This is the mfa-audit-disable-access policy:

```
- name: mfa-audit-disable-access
    description: Cloud Custodian MFA Audit Disable Access
    comment: |
      Retrieve list of all IAM users with MFA disabled
      in the group 'Administrators' and send notification
      if MFA is not enabled after 5 days of inactivity.
      Send notification via SES and Slack.
      Disable user access to management console.
      Delete user access-keys.
    resource: iam-user
    mode:
      type: periodic
      role: arn:aws:iam::1234567890:role/CloudCustodian
      schedule: "rate(1 day)"
    filters:
      - type: credential
        key: mfa_active
        value: false
      - type: group
        key: GroupName
        value: Administrators
      - type: value
        key: CreateDate
        op: greater-than
        value_type: age
        value: 5
    actions:
      - type: delete
        options:
          - access-keys
          - console-access
      - type: notify
        template: mfa-audit-disable-access.html
        template_format: 'html'
        template_slack: slack-mfa-audit-disable-access
        priority_header: '5'
        subject: 'Security Audit: AWS Console Access Disabled and Access Keys Deleted'
        to:
          - email@domain.com
          - slack://#cloudcustodian
        owner_absent_contact:
          - email@domain.com
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/1234567890/cloud-cloudcustodian
```

I'm not sure if this matters, but I'd might as well mention for completeness.

The policy above is the bottom half section of a policy I run that's named `mfa-audit.yml`.

The first half is somewhat similar but doesn't take any actions to disable console access and delete access keys.  

Here's the full policy I'm running that includes the "mfa-audit-disable-access" policy:

<details>
<summary>mfa-audit.yml</summary>

<pre>
policies:
  - name: mfa-audit-reminder
    description: Cloud Custodian MFA Audit Notification
    comment: |
      Retrieve list of all IAM users with MFA disabled
      in the group 'Administrators' and send notification
      if MFA is not enabled after 3 days of the create date.
      Send notification via SES and Slack.
      This policy must be run as a cron job until lambda support
      with group filtering is supported.
    resource: iam-user
    mode:
      type: periodic
      role: arn:aws:iam::1234567890:role/CloudCustodian
      schedule: "rate(1 day)"
    filters:
      - type: credential
        key: mfa_active
        value: false
      - type: group
        key: GroupName
        value: Administrators
      - type: value
        key: CreateDate
        op: less-than
        value_type: age
        value: 3
    actions:
      - type: notify
        template: mfa-audit-reminder.html
        template_format: 'html'
        template_slack: slack-mfa-audit-reminder
        priority_header: '5'
        subject: 'Security Audit: IAM users in Administrators group with MFA Dis
abled'
        to:
          - email@domain.com
          - slack://#cloudcustodian
        owner_absent_contact:
          - email@domain.com
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/1234567890/cloud-cloudcustodian

- name: mfa-audit-disable-access
    description: Cloud Custodian MFA Audit Disable Access
    comment: |
      Retrieve list of all IAM users with MFA disabled
      in the group 'Administrators' and send notification
      if MFA is not enabled after 5 days of inactivity.
      Send notification via SES and Slack.
      Disable user access to management console.
      Delete user access-keys.
    resource: iam-user
    mode:
      type: periodic
      role: arn:aws:iam::1234567890:role/CloudCustodian
      schedule: "rate(1 day)"
    filters:
      - type: credential
        key: mfa_active
        value: false
      - type: group
        key: GroupName
        value: Administrators
      - type: value
        key: CreateDate
        op: greater-than
        value_type: age
        value: 5
    actions:
      - type: delete
        options:
          - access-keys
          - console-access
      - type: notify
        template: mfa-audit-disable-access.html
        template_format: 'html'
        template_slack: slack-mfa-audit-disable-access
        priority_header: '5'
        subject: 'Security Audit: AWS Console Access Disabled and Access Keys De
leted'
        to:
          - email@domain.com
          - slack://#cloudcustodian
        owner_absent_contact:
          - email@domain.com
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/1234567890/cloud-cloudcustodian
</pre>
</details>
