### ISSUE TITLE
shield-enabled filter not working for Elastic IPs

### ISSUE THREAD

**Issue by dfengshi** [capitalone/cloud-custodian#2529]
Hello,

A policy like this will return a list of all EIPs in the account instead of just the ones without shield protection enabled.

```
policies:
    - name: check-eip-shield
      resource: network-addr
      filters:
        - type: shield-enabled
          state: false
```

**Comment by dfengshi** [comment]
@thisisshi The resource.json looks like this:

```

**Comment by thisisshi** [comment]
this sounds similar to this https://github.com/capitalone/cloud-custodian/issues/2245

**Comment by dfengshi** [comment]
@thisisshi yeah you're right, sounds similar. However, I only see the issue with EIPs. `c7n:ShieldProtected` for ALBs/ELBs/HostedZones/CloudFront seems to work fine.

**Comment by thisisshi** [comment]
is it returning false for all resources or are some of them coming back as good?

**Comment by dfengshi** [comment]
@thisisshi it's returning false for all EIPs

**Comment by thisisshi** [comment]
ok, I think the issue is here: https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/shield.py#L62

model.type for elastic ip's in custodian is "network-addr" but "network-addr" doesn't appear in the elastic ip ARN, rather we should be looking for "eip-allocation".

**Comment by dfengshi** [comment]
@thisisshi cool, thanks

however, with your PR, filtering for 
```
policies:
    - name: check-eip-shield
      resource: eip-allocation
      filters:
        - type: shield-enabled
          state: false
```

will give a validation error
