### ISSUE TITLE
Regex over a list

### ISSUE THREAD

**Issue by ctippur** [capitalone/cloud-custodian#2563]
Use case: find all security groups that have cidr blocks that end with ```\0```
The below filter would fail as the cidr blocks is a list.
```
Cidr:
        value_type: cidr
        op: regex
        value: "/0"
```

**Comment by kapilt** [comment]
regexes don't make sense on cidr value types which are there to support cidr math semantics, ie they are not strings since value type converts them, but a regex over a list of string values does make sense.

**Comment by 12Manoz** [comment]
I am using for some other purpose for policies:
```
- name: ecs-task-definitions-complaince
    resource: aws.ecs-task-definition
    filters:
      - type: value 
        key: containerDefinitions[].environment[].value
        value: (?:.*maven.*)
        op: regex
```
here value returned is list. 
Regex over list does not work.
