### ISSUE TITLE
Unable to Assign a Tag Using "type: auto-tag-user"

### ISSUE THREAD

**Issue by riweston** [capitalone/cloud-custodian#2565]
Hi All,

I'm trying to test Cloud Custodian with AWS as the tagging policies seem perfect for one of our biggest niggles however through probably my own ignorance I'm not having any success, could anybody point me in the right direction?

This is the policy...
```
policies:
- name: ec2-auto-tag-owner
  resource: ec2
  mode:
    type: cloudtrail
    events:
      - source: ec2.amazonaws.com
        event: StartInstances
        ids: "responseElements.instancesSet.items[].instanceId"
      - source: ec2.amazonaws.com
        event: RunInstances
        ids: "responseElements.instancesSet.items[].instanceId"
      - source: ec2.amazonaws.com
        event: RebootInstances
        ids: "responseElements.instancesSet.items[].instanceId"
    role: arn:aws:iam::660910064092:role/custodian-auto-tagger
  filters:
    - tag:CreatorName: absent
  actions:
    - type: auto-tag-user
      tag: CreatorName
      principal_id_tag: CreatorId
```
The error in the Lambda...
```
11:56:24
[INFO]	2018-06-26T11:56:24.593Z	f304cba9-7937-11e8-80f6-7b22b832a002	Found resource ids: []
11:56:24
[WARNING]	2018-06-26T11:56:24.593Z	f304cba9-7937-11e8-80f6-7b22b832a002	Could not find resource ids
```
Let me know if there's anything more useful or helpful I can provide!

Cheers, Rich
