### ISSUE TITLE
Copy-instance-tags action on "Key": "device"

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2575]
Is the following `copy-instance-tags` action possible?

```
policies:
  - name: copy-instance-tags
    resource: ebs
    description: |
      Cloud Custodian Copy Instance Tag to Volume
    comment: |
      Copy instance tags to respective instance's ebs volume.
    mode:
      type: periodic
      role: arn:aws:iam::1234567890:role/CloudCustodian
      schedule: "rate(15 minutes)"
    filters:
      - type: value
        key: "Attachments[0].Device"
        value: not-null
    actions:
      - type: copy-instance-tags
        tags:
          - Name
      - type: copy-instance-tags
        tags:
          - Owner
      - type: copy-instance-tags
        tags:
          - Team
      - type: copy-instance-tags
        tags:
          - LastAttachInstance
      - type: copy-instance-tags
        tags:
          - device  <<<<<<<<<<<<<<<<<<<   Is this a valid Key name?
```

I'm trying to copy the EC2 instance's root device attribute (e.g., /dev/sda1) as an EBS volume tag and not seeing it get copied.

Note: The EC2 instance doesn't use an explicit tag key name of 'device'. Rather I'm assuming (or would like) it can be obtained implicitly from the **"Key":"device"** pair shown in the policy's **resources.json** output file.

Sample output of policy **resources.json** file:

```
(snip)
"Tags": [
      {
        "Value": "i-12345678901234567",
        "Key": "instance_id"
      },
      {
        "Value": "2017-07-14T22:37:29+00:00",
        "Key": "LastAttachTime"
      },
      {
        "Value": "Mr Magoo <mr.magoo@domain.com>",
        "Key": "Owner"
      },
      {
        "Value": "i-12345678901234567",
        "Key": "LastAttachInstance"
      },
      {
        "Value": "Cloud",
        "Key": "Team"
      },
      {
        "Value": "/dev/sda1",  <<<<  This tag value is what I'm interested in copying to the EBS volume
        "Key": "device"
      },
      {
        "Value": "cloud-fess",
        "Key": "Name"
      }
    ],
(end of snip)
```
