### ISSUE TITLE
Allow variable interpolation from filtered resource in a jmespath query

### ISSUE THREAD

**Issue by seth-carroll** [capitalone/cloud-custodian#2620]
We are working on a solution to prevent IAM role shopping and would like to be able to use the IAM role or instance profile from the filtered resource in the jmespath used in the value_from expression. The goal is to run a policy against all resources that allow the associate of an IAM role (ex: EC2, Lambda, Kinesis, etc) and validate that the IAM role is allowed based on a look up in a generated mapping json file.

We will generate a json file that contains the mapping of role / instance profile ARNs to the allowed "application" tag value. For example:

```
{
    "description": "Instance profile to application mapping",
    "instance_profiles": {
        "arn:aws:iam::123456789012:instance-profile/Application-ABC-InstanceProfile-123456789012": {
            "role": "Application-ABC-Role", 
            "application": "ABC"
        },
        "arn:aws:iam::123456789012:instance-profile/Application-XYZ-InstanceProfile-123456789012": {
            "role": "Application-XYZ-Role", 
            "application": "XYZ"
        }
    }
}
```

And here is an example policy:
```
policies:
  name: prevent_iam_role_shopping
  resource: ec2 
  filters:
    - type: value
      key: "tag:application"
      value_from:
        url: file://instance_profile_mapping.json
        format: json
        expression: instance_profiles."{'IamInstanceProfile.Arn'}".['application']
      op: not-in
```
