### ISSUE TITLE
Questions around c7n account service-limit-increase action

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2643]
Hi there,

I've been looking through the account service-limit-increase [use case document](https://www.capitalone.io/docs/usecases/accountservicelimit.html) and [c7n/resources/account.py](https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/account.py) and am hoping to get some clarifications on its usage.

Consider the following policy:
```
policies:
  - name: account-service-limits
    resource: account
    region: us-east-1
    filters:
      - type: service-limit
        services:
          - EC2
        threshold: 80
    actions:
      - type: request-limit-increase
        notify: [email]
        percent-increase: 25
        message: "Please raise the below account limit(s); \n {limits}"
```

**Question 1**
How does the policy get the account ID when creating the service limit request? 

**Question 2**
Say I want to run this policy across multiple accounts, what would the policy look like?

**Question 3**
What does the email address represent for the notify action?
I'm assuming that's where AWS will send notifications when the service limit request case gets updated?  

**Question 4** 
Is there a way to filter by ec2 instance type?  
For example, I want to filter on ec2 p3.8xlarge.

Thanks

**Comment by thisisshi** [comment]
1. The account ID is picked up from the role that custodian is executing as
2. If you want to run the policy against multiple accounts, either use c7n-org or use a different `--profile`  or a different `--assume` profile
3. you can cc an email address when contacting aws support, the email that you pass in will be cc'd onto the request
4. yes you can do it like so:

```yaml
      - service: EC2 limit: On-Demand instances - m3.medium
```

**Comment by davidclin** [comment]
Thanks for the explanations.

When I try to run my policy against a t2.micro for testing purposes, I'm not getting any matches (i.e. count=0).

Is the policy below written correctly?

```
policies:
  - name: account-service-limits
    resource: account
    region: us-east-1
    filters:
      - type: service-limit
      - service:
          EC2 limit: On-Demand instances - t2.micro
      - threshold: 0.0
    actions:
      - type: request-limit-increase
        notify: <email-address>
        amount-increase: 1
        message: "Please raise the below account limit(s); \n {limits}"
```

Output

```
(c7n_mailer) $ custodian run --dryrun -s output limit.yml
2018-08-07 07:56:56,179: custodian.policy:INFO policy: account-service-limits resource:account region:us-east-1 count:0 time:0.30
```

**Comment by davidclin** [comment]
After looking more carefully at the `account.filters.service-limit` schema, I can see options for setting: 

- [ ] threshold
- [ ] refresh-period
- [ ] limits
- [ ] services

However, it's not entirely clear to me where/how I insert the following line into my policy:

```yml
- service: EC2 limit: On-Demand instances - m3.medium
```

<details><summary>(c7n)$ custodian schema account.filters.service-limit</summary>

...
Schema
------

{
    "additionalProperties": false,
    "required": [
        "type"
    ],
    "type": "object",
    "properties": {
        "threshold": {
            "type": "number"
        },
        "refresh_period": {
            "type": "integer"
        },
        "type": {
            "enum": [
                "service-limit"
            ]
        },
        "limits": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "services": {
            "items": {
                "enum": [
                    "EC2",
                    "ELB",
                    "VPC",
                    "AutoScaling",
                    "RDS",
                    "EBS",
                    "SES",
                    "IAM"
                ]
            },
            "type": "array"
        }
    }
}
```
</details>

**Comment by davidclin** [comment]
I was able to get the following policy to work but for all EC2 instance types that match the defined threshold:

```
policies:
  - name: account-service-limits
    resource: account
    region: us-east-1
    filters:
      - type: service-limit
        services:
          - EC2
        threshold: 10
      - service:
    actions:
      - type: request-limit-increase
        notify:
          - <email-address-goes-here>
        amount-increase: 1
        message: "Please raise the below account limit(s); \n {limits}"
```

If there's a way to filter based on instance type (i.e. t2.micro, p3.x8large, etc.),  a working example would be greatly appreciated!
