### ISSUE TITLE
Deserialization error on invoke-lambda

### ISSUE THREAD

**Issue by troylar** [capitalone/cloud-custodian#2652]
Run this simple policy to invoke a lambda causes the JSON encoder to break with the error `TypeError: Object of type 'bytes' is not JSON serializable`. This is due to the fact that the `read()` operation is returning a `bytes` object.

```
- actions:
  - function: cloud-custodian-dev-responder
    type: invoke-lambda
  description: All CloudTrail logs
  name: all-cloudtrail-logs
  resource: cloudtrail
```

https://github.com/capitalone/cloud-custodian/blob/ef77f93d2bfc77be0dc5286e61144254850a4a9f/c7n/actions.py#L380
