### ISSUE TITLE
mugc.py does not work if you have a single policy

### ISSUE THREAD

**Issue by thomasbiddle** [capitalone/cloud-custodian#2671]
Start with a policy:

```
policies:
 - name: password-policy-check
   resource: account
   region: us-east-1
   mode:
     role: arn:aws:iam::123456789000:role/your-role
     type: periodic
     schedule: "rate(3 minutes)"
   filters:
     - type: password-policy
       key: MinimumPasswordLength
       value: 10
       op: ge
     - type: password-policy
       key: RequireSymbols
       value: true
```

Run custodian, try to remove either everything, or just everything under `policies` and mugc will throw an error.

I guess actually; this bug means I wouldn't ever be able to remove *all* of my policies - regardless
