### ISSUE TITLE
logs not being generated from c7n-org 

### ISSUE THREAD

**Issue by pwatt** [capitalone/cloud-custodian#2674]
I have the following policy saved as s3.yaml:

```
policies:
  - name: cloud-custodian-s3-encryption-policy
    # ensure s3 buckets are encrypted
    resource: s3
    actions:
      - set-bucket-encryption

  - name: cloud-custodian-s3-delete-global-grants-policy
    # global grants are not allowed
    resource: s3
    filters:
      - type: global-grants
    actions:
      - delete-global-grants
```

Executing with the following command:
`c7n-org run -c accounts.yml -s s3://my-bucketname -u global/s3.yaml --region all`

The log file (custodian-run.log.gz) that are generated are empty.
[custodian-run.log.gz](https://github.com/capitalone/cloud-custodian/files/2233536/custodian-run.log.gz)
