### ISSUE TITLE
Azure validate throwing error 'Bag' object is not callable

### ISSUE THREAD

**Issue by aluong** [capitalone/cloud-custodian#2691]
Issuing the command
```
custodian validate policies/policy.yml
```

Policy:
```
policies:
- name: test-azure
  resource: azure.vm
  actions:
  - type: tag
    tag: "mytag"
    value: "tag"
```

Result:
```
2018-08-01 14:32:21,553: custodian.commands:ERROR Configuration invalid: policies/policy.yml
2018-08-01 14:32:21,553: custodian.commands:ERROR Policy: test-azure is invalid: 'Bag' object is not callable
```
