### ISSUE TITLE
Stop actions against EC2 instances break on spot

### ISSUE THREAD

**Issue by IDT-kcrook** [capitalone/cloud-custodian#2718]
Bug / Feature Request

The root issue is the api request StopInstances breaks against Spot instances. 

If there was a way we could filter out spot instances (without needing to manually tag every spot instance so cloud custodian can filter on it), that would be fantastic.

Spot instances have a special field called "Lifecycle" that on-demand instances don't have. When engineering our own solutions outside of cloud custodian we have needed to use this to determine whether an instance is spot or not.

**Comment by kumarsiyer** [comment]
Have you looked at the value filter to exempt instances. You should be able to filter based on the values from the resources.json file.

**Comment by IDT-kcrook** [comment]
Thanks!
I also found #970 after I posted this. This worked wonders for me:
```
policies:
- name: ec2-off-hours
  resource: ec2
  filters:
    - SpotInstanceRequestId: null
  actions:
    - stop
```
