### ISSUE TITLE
c7n_mailer throwing JSON errors on sagemaker-notebook

### ISSUE THREAD

**Issue by troylar** [capitalone/cloud-custodian#2734]
The `resource_format` with the j2 template is not rendering correct JSON for some resources and therefore not able to send messages.

Example:
```
policies:
- actions:
  - slack_template: slack_default
    to:
    - slack://webhook/#my-channel
    transport:
      type: sqs
      queue: https://sqs.us-east-1.amazonaws.com/12345678/my_queue
    type: notify
  filters:
  - or:
    - DirectInternetAccess: Enabled
    - KmsKeyId: absent
  resource: sagemaker-notebook
```
A section of the rendered JSON that's broken . . .
```
{
   "attachments":[
      {
         "fallback":"Cloud Custodian Policy Violation",
         "title":"Custodian",
         "color":"danger",
         "fields":[
            {
               "title":"Resources",
ERROR ---->               "value":"{
  "NetworkInterfaceId": "eni-0df98f3f169c8153f", 
  "NotebookInstanceStatus": "InService", 
  "Tags": [], 
  "Url": "public-test.notebook.us-east-1.sagemaker.aws", 
  "RoleArn": "arn:aws:iam::1234567:role/service-role/AmazonSageMaker-ExecutionRole-20180123T145367", 
  "NotebookInstanceName": "public-test", 
  "CreationTime": "2018-08-10T18:22:32.969000-04:00", 
  "c7n:MatchedFilters": [
    "DirectInternetAccess", 
    "KmsKeyId"
  ],
Traceback (most recent call last):
  File "/var/task/c7n_mailer/sqs_queue_processor.py", line 174, in process_sqs_message
    slack_delivery.slack_handler(sqs_message, slack_messages)
  File "/var/task/c7n_mailer/slack_delivery.py", line 104, in slack_handler
    json.loads(payload, strict=False)["channel"])
  File "/usr/lib64/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 11 column 4 (char 241)
```
