### ISSUE TITLE
iam user filter on access key age

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#279]

**Comment by kapilt** [comment]
closed in #272 example
```
policies:
  - name: iam-user-check
    resource: iam-user
    filters:
      - type: policy
        key: PolicyName
        value: AdministratorAccess
      - type: access-key
        key: Status
        value: Active
      - type: access-key
        key: CreateDate
        value: 2
        op: greater-than
        value_type: age
```

**Comment by sbourlon** [comment]
Here is another example of value_type age for ELB. This policy returns ELB older than a day with no attached instance.

```
policies:
  - name: elb-pruning 
    description: |
      Prune unused ELB
    resource: elb
    filters:
      - type: value
        key: "CreatedTime"
        value: 1
        op: greater-than
        value_type: age
      - type: value
        key: "Instances"
        op: equal
        value: []
```
