### ISSUE TITLE
Azure - Non existing metric mapped to a random one.

### ISSUE THREAD

**Issue by ivan-shaporov** [capitalone/cloud-custodian#2792]
Tried running this policy:
 ```
policies:
    - name: bad-metric
      description: |
        Non existing metric mapped to a random one.
      resource: azure.vm
      
      filters:
      - type: metric
        metric: NonExistingMetric
        aggregation: average
        op: ne
        threshold: 17
        timeframe: 12

      actions:
       - type: tag
         tag: bug
         value: NonExistingMetric
 ```
Expected an error message, got the tag assigned.

Also tried le 0.75 condition, got one instance assigned the tag and one not. Looks like if a metric is not found a random metric is picked up.

VM OS - Linux, Cent OS.
