### ISSUE TITLE
config rule not working for resource type 'app-elb'

### ISSUE THREAD

**Issue by namanan** [capitalone/cloud-custodian#2814]
So we have a policy that looks for app-elb resource types and reports the resources back. The policy runs just fine over c7n CLI but when its run inside AWS Config as a Lambda function it blows up with the following error message. Also, the same behavior is observed when the Lambda is manually executed. The same rule works just fine with Config and Lambda for 'elb' resource type.

It complains about the Tags array.

`$ custodian run -s . policy.yml`

 Here is the policy snippet

```
policies:

  - name: app-elb-outdated-securitypolicy
    description: Notify when the app-elb has outdated security policy
    resource: app-elb
    mode:
        type: config-rule
        role: arn:aws:iam::<account id>:role/<role>
    filters:
       - .......

```
expected string or buffer: TypeError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 5, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 91, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 776, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 662, in run
resources = super(ConfigRuleMode, self).run(event, lambda_context)
File "/var/task/c7n/policy.py", line 441, in run
resources = self.resolve_resources(event)
File "/var/task/c7n/policy.py", line 645, in resolve_resources
return [source.load_resource(self.cfg_event['configurationItem'])]
File "/var/task/c7n/resources/appelb.py", line 106, in load_resource
for t in json.loads(item['supplementaryConfiguration']['Tags'])]
File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

Any insight would be appreciated.

Thank you
