### ISSUE TITLE
Feature Request - Add copy-tags support from EBS volumes to Snapshots

### ISSUE THREAD

**Issue by IDT-kcrook** [capitalone/cloud-custodian#2827]
This is supported already here:
- EC2 -> snapshots
- EC2 -> EBS Volumes

For example:
```
policies:
  - name: ec2-snapshots
    resource: ec2
  actions:
    - type: snapshot
      copy-tags:
        - Name
```

This feature request would allow ebs volumes to copy their tags to their snapshots upon deletion.
For example:
```
policies:
- name: ebs-snapshot
  resource: ebs
  comments: |
    Snapshot and ebs volumes that have reached the 30 day mark.
  filters:
    - type: marked-for-op
      tag: orphaned
      op: snapshot
  actions:
    - type: snapshot
      copy-tags:
        - Name
```
