### ISSUE TITLE
filters/core - augment resource count filter to check for percentage of resources affected

### ISSUE THREAD

**Issue by thisisshi** [capitalone/cloud-custodian#2828]
In most cases restricting the number of resources affected isn't viable when managing multiple AWS accounts as the number of resources varies across accounts. Updating or adding a new filter similar to resource-count would be useful to limit the percentage of resources affected.

Proposed syntax:

```yaml
policies:
  - name: s3-limit-impact
    resource: s3
    filters:
      - type: resource-percentage
        percentage: 0.5
    actions:
      - type: delete
```

```bash
custodian.filters.WARNING Resource Percentage 100% - 1 of 1 resources exceeds 50%, exiting.
```

**Comment by kapilt** [comment]
incidentally done as a top level policy attribute to match existing limit, filters don't really have access to the population count, just the filtered set. also given its safety belt, its nicer define outside of the policy syntax. so new proposed syntax is

```
policies:
  - name: s3-limit-impact
    resource: s3
    max-resources-percentage: 50
    actions:
      - type: delete
```

which will bail if more than 50 percent of the total resources in the account will be affected.
