### ISSUE TITLE
Security-Gateway Filter not working as expected

### ISSUE THREAD

**Issue by timbo256** [capitalone/cloud-custodian#2867]
Should you be able to include two separate 'type: ingress' filters in a policy. The reason why I ask is because we have a policy as per example 1 that does not work and example 2 where it does

example 1 - only filters on the IP address - ignoring the Ports
```
       - type: ingress
         Ports: [22, 3389]
#
# Apply to all IPs that are NOT Bastion servers
       - type: ingress
         Cidr:
           value_type: cidr
           op: not-in
           value:
             - 10.183.102.10/32
```

example 2 - filters on both port and IP

```
      - type: ingress
        Ports: [22, 3389]
        Cidr:
          values_type: cidr
          op: not-in
          value:
            - 10.183.102.10/32
```

**Comment by timbo256** [comment]
Have a similar issue when using OnlyPorts
The following filter removes an inbound rule for https when source is 0.0.0.0/0 which I don't think it should?
```
    filters:
        - type: ingress
          OnlyPorts: [22, 80, 443]
          Cidr:
             value_type: cidr
             op: eq
             value: 0.0.0.0/0
```
