### ISSUE TITLE
User Pool with filter "tag" not working as expected.

### ISSUE THREAD

**Issue by amathew5** [capitalone/cloud-custodian#2868]
I am attempting to filter based upon tags attached to a user-pool
```yaml
policies:
  - name: cognito-tag-testing
    resource: user-pool
    description: |
      Filter for compliant user-pools
    filters:
      - "tag:Owner": present
```
I have two test user pools, one with the expected tag and the other without. I assumed that the "tag:Key" used under filters would work to return the count of 1 (the user-pool with the expected tag). Is there something that I might be doing incorrectly? I don't want to consider this to be a bug but it might also be something to add in for compliance purposes.
