### ISSUE TITLE
How to do a 'not' tag filter?

### ISSUE THREAD

**Issue by tzd-sh** [capitalone/cloud-custodian#2878]
I am trying to figure out how to write a filter that will match on 'not equal' to a value.

For example, this works great to filter out all instances with Environment = "Prod"

```
policies:
  - name: list-prod-ec2-instances
    resource: ec2
    filters:
      - tag:Environment: "Prod"
```

But, how do I write a filter that will list all instances where Environment is NOT "Prod"?

I can see from http://capitalone.github.io/cloud-custodian/docs/filters.html that I should be able to use 'value filters' for 'not-equal', but I don't know how to write them in the policy together with 'tag:Environment'.

I tried the following which did not work:

```
policies:
  - name: list-all-non-prod-ec2-instances
    resource: ec2
    filters:
      - tag:Environment
        value: "Prod"
        op: ne


policies:
  - name: list-all-non-prod-ec2-instances
    resource: ec2
    filters:
      - type: tag
        key: Environment
        value: "Prod"
        op: ne
```

**Comment by kumarsiyer** [comment]
You can try something like this 

```
policies:
  - name: list-prod-ec2-instances
    resource: ec2
    filters:
      - not:
        - tag:Environment: "Prod"

**Comment by tzd-sh** [comment]
Thanks kumarsiyer, that worked!

But I have a follow-up question:

The matching does not seem to be case-sensitive.  In the example above, both "Prod" and "PROD" would match the pattern.  How do I make the matching case-sensitive?

**Comment by tzd-sh** [comment]
I think I found something that works for case sensitive.  I have to write it like this:

```
policies:
  - name: list-non-prod-ec2-instances
    resource: ec2
    filters:
      - not:
        - type: value
          key: "tag:Environment"
          value: "Prod"

```
The above will match to exclude only 'Prod' and not 'PROD'
