### ISSUE TITLE
How to delete a tag?

### ISSUE THREAD

**Issue by tzd-sh** [capitalone/cloud-custodian#2879]
I have figured out how to tag instances.  But, what if I need to delete a specific tag?

For example, if I want to delete all tags of "Environment" from my instances, I wrote this (and tried many variations of actions):

```
policies:
  - name: untag-instances
    resource: ec2

    filters:
        - tag:Environment: present

    actions:
      - type: untag
        tags: "tag:Environment"
```

But I get error when I run it:

Exception: Failed to validate on policy untag-instances 
 {'type': 'untag', 'tags': 'tag:Environment'} is not valid under any of the given schemas

**Comment by kapilt** [comment]
make it a list of tags. ie `tags: ["tag:Environment"]`

**Comment by tzd-sh** [comment]
Thanks it works!  Really appreciate it!

**Comment by tzd-sh** [comment]
Oops sorry I spoke too soon.

```
policies:
  - name: untag-instances
    resource: ec2

    filters:
        - tag:Environment: present

    actions:
      - type: untag
        tags: [ "tag:Environment" ]
```

The above ran without errors.  But after running I checked and all my EC2 instances still have the Environment tag! :(

**Comment by kapilt** [comment]
i suspect your getting confused by the cache, by default custodian caches all resource queries for 15m, you can disable the cache with `--cache-period=0`

**Comment by tzd-sh** [comment]
Hi Kapilt,

I found the bug in my policy.  The following will work for me:

```
policies:
  - name: untag-instances
    resource: ec2

    filters:
        - tag:Environment: present

    actions:
      - type: untag
        tags: [ "Environment" ]

```

Speaking of cache, will deleting the output directory (specified in custodian run -s output/) be the same as clearing the cache?

Thanks!
