### ISSUE TITLE
AutoScaling Group 'mark-for-op' action doesn't support 'tag' attribute

### ISSUE THREAD

**Issue by ewbankkit** [capitalone/cloud-custodian#288]
This policy
```
  - name: asg-invalid-mark
    resource: asg
    comments: |
      Mark ASGs that are spinning.
    filters:
      - invalid
      - "tag:custodian_cleanup": absent
    actions:
      - type: mark-for-op
        tag: custodian_cleanup
        op: delete
        days: 2
```
fails validation:
```
2016-07-12 09:06:23,856: custodian.commands:ERROR Invalid configuration
2016-07-12 09:06:23,858: custodian.commands:ERROR  Additional properties are not allowed ('tag' was unexpected)

Failed validating 'additionalProperties' in schema[9]:
    {'additionalProperties': False,
     'properties': {'days': {'minimum': 0, 'type': 'number'},
                    'key': {'type': 'string'},
                    'op': {'enum': ['suspend', 'resume', 'delete']},
                    'type': {'enum': ['mark-for-op']}},
     'required': ['type'],
     'type': 'object'}

On instance:
    {'days': 2,
     'op': 'delete',
     'tag': 'custodian_cleanup',
     'type': 'mark-for-op'}
```
