### ISSUE TITLE
Rule Activate Upon Creation Of Resource

### ISSUE THREAD

**Issue by mason67git** [capitalone/cloud-custodian#2910]
Hi,

Struggling to find a way to run one of the rules I create when a set AWS resource is made.

Eg: If an S3 bucket is public when created then delete it/ if an RDS instance is unencrypted upon creation delete it.

**Comment by thisisshi** [comment]
@mason67git you can use the cloudtrail mode to react to cloudtrail events like CreateBucket in this case you could have a policy like so:

more docs: http://capitalone.github.io/cloud-custodian/docs/policy/lambda.html#cloudwatch-events

```yaml
policies:
  - name: public-s3-bucket-delete-on-create
    resource: s3
    mode:
      type: cloudtrail
      events:
       - CreateBucket
    filters:
      - type: global-grants
    actions:
      - type: delete
```
