### ISSUE TITLE
Can we add copy-tag ability from EC2 snapshot action to the EBS snapshot action?

### ISSUE THREAD

**Issue by scoleri** [capitalone/cloud-custodian#2915]
We have lots of unattached EBS volumes here and there.  We'd like to delete them but first do a snapshot which currently I'm doing using something like below.  However the new snapshots are completely unidentifiable.  If there is a way already to do this please help.

Thanks,

```
policies:
  - name: create-ebs-snapshots
    resource: ebs
    filters:
        - Attachments: []
        - "tag:CloudCustodianIgnore": absent
    actions:
       - type: snapshot
```
