### ISSUE TITLE
Security-Gateway Action remove-permissions deletes valid SG rules

### ISSUE THREAD

**Issue by timbo256** [capitalone/cloud-custodian#2917]
When run a policy to remove any SG rule that has a source IP of 0.0.0.0/0 and is not http or https the filter appears to match okay, but the action removes ALL SG rules where the source is 0.0.0.0/0, including any with HTTP or HTTPS. Use of ingress: matched does not appear to make any difference.
Policy:
```
policies:
  - name: sg-test
    resource: security-group
    filters:
       - and:  
         - type: ingress
           OnlyPorts: [22, 80, 443]
#
         - type: ingress
           Cidr:
              value_type: cidr
              op: eq
              value: 0.0.0.0/0
#
    actions:
      - type: remove-permissions
        ingress: matched 
```

**Comment by kapilt** [comment]
the removal is currently against the ANDED set of things that matched each ingress filter independently, the default block operator is 'AND'. The your intended use case is had by specifying the full condition for the rule on a single ingress filter, ie. with `OnlyPorts and `Cidr` on the same ingress filter.

**Comment by timbo256** [comment]
So i think you are saying the filter should be as follows?:
```
         - type: ingress
           OnlyPorts: [22, 80, 443]
           Cidr:
              value_type: cidr
              op: eq
              value: 0.0.0.0/0
```

**Comment by JoshRosen** [comment]
I think that I'm experiencing a similar problem, except I think that the issue might be related to `OnlyPorts` not working properly. Here's an example of a filter (the formatting is a bit weird due to having been code-generated from another markup language):

```yaml
filters:
  - Cidr:
      op: eq
      value: 0.0.0.0/0
      value_type: cidr
    OnlyPorts:
    - 22
    type: ingress
- actions:
  - ingress: matched
    type: remove-permissions
```

My expectation is that this filter would _not_ match a security group whose only rule is to open port 22 to the world. However, it _is_ matching the following SG:

![image](https://user-images.githubusercontent.com/50748/46587174-ff9b0c80-ca3c-11e8-9755-144e5817c660.png)

Given this, I'm suspecting that the behavior that @timbo256 reported is due to the `OnlyPorts` condition not taking effect.

This issue also looks like a potential duplicate of #2484.
