### ISSUE TITLE
how to tag a snapshot at creation. 

### ISSUE THREAD

**Issue by baptiste-s** [capitalone/cloud-custodian#2921]
Hi,

for my EC2 instances, I need to keep daily snapshots for 30 days and monthly snapshots for a year. 
I was thinking about creating 2 policies.
I would like to add a tag with the value daily or monthly at creation so I can filter for my delete policy. 
I am not sure how to do so...

**Comment by thisisshi** [comment]
@baptiste-s 

you can trigger policies based on cloudtrail events, in this case you would need one to trigger on a CreateSnapshot event and to tag it with the corresponding date that you need:

You can use expressions to include the date like so: https://github.com/capitalone/cloud-custodian/issues/2864#issuecomment-421568426

**Comment by baptiste-s** [comment]
Ok so the CreateSnapshot event is not supported by default. 

I had to add : 

>          'CreateSnapshot': {
>              'ids': 'requestParameters.SnapshotName',
>              'source': 'ec2.amazonaws.com'},

to the file :  INSTALLPATH/custodian/lib/python2.7/site-packages/c7n/cwe.py line 78

**Comment by thisisshi** [comment]
@baptiste-s 

you can add custom events directly in the policy without modifying the source code:

```yaml
policies:
  - name: tag-on-snap
    resource: ec2
    mode:
      - type: cloudtrail
        events:
           - source: ec2.amazonaws.com
              event: CreateSnapshot
              ids: requestParameters.SnapshotName
```
