### ISSUE TITLE
Lambda tags not being read when executing policies cross account

### ISSUE THREAD

**Issue by kericmiles** [capitalone/cloud-custodian#2942]
In version .30 when running a policy that checks for missing tags on Lambda functions, Cloud Custodian does not return any tags for the resources. This causes actions to be performed on the resources regardless of whether the tags are present or not. The policy below was used since .28.0 and was working until updating to version .30:

```yaml
policies:
    - name: aws-lambda-tag-policy
      resource: lambda
      mode:
        type: periodic
        schedule: "rate(5 minutes)"
        role: arn:aws:iam::XXXXXXXXXXXX:role/ROLENAME
        execution-options:
          assume_role: arn:aws:iam::XXXXXXXXXXXX:role/ROLENAME
      filters:
        - or:
          - "tag:name": absent
          - "tag:environment": absent
          - "tag:costcenter": absent
      actions:
          - type: invoke-lambda
            function: cloudcustodian-event-debug
            async: False
```
