### ISSUE TITLE
vpc flow log errors when creating flow log groups

### ISSUE THREAD

**Issue by fidelito** [capitalone/cloud-custodian#2944]
It looks like the flowLogId is empty. Not sure why DeleteFlowLogs operation is being called on when trying to create the vpc flow logs in the first place were no flow logs were created previously. I deleted the cache that custodian was using to make sure that wasn't the case, 

custodian.policy:INFO policy: vpc-flowlog-enable resource:vpc region:us-west-2 count:3 time:0.61
custodian.actions:ERROR delete flow-log: 1 validation error detected: Value null at 'flowLogId' has an invalid format
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/c7n/resources/vpc.py", line 1786, in delete_flow_logs
FlowLogIds=[f['FlowLogId'] for f in flow_logs])
File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 320, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 623, in _make_api_call
raise error_class(parsed_response, operation_name)

ClientError: An error occurred (InvalidParameterValue) when calling the DeleteFlowLogs operation: 1 validation error detected: Value null at 'flowLogId' has an invalid format

The Policy I am running is:

```
policies:
- name: vpc-flowlog-enable
  resource: vpc
  filters:
     - type: flow-logs
       enabled: false
  actions:
    - type: set-flow-log
      DeliverLogsPermissionArn: arn:aws:iam::${ACCOUNT}:role/role
      LogGroupName: vpc-flowlogs-${ACCOUNT}-${REGION}
      TrafficType: ALL
      state: false
```
