### ISSUE TITLE
lambda logging

### ISSUE THREAD

**Issue by baptiste-s** [capitalone/cloud-custodian#2947]
Hi, 

I want to get the result of the lambda from cloudwatch log : 

```
policies:
  - name: ec2-daily-backup
    resource: ec2
    mode:
         type: periodic
         schedule: "cron(0 3 * * ? *)"
         role: arn:aws:iam::{account_id}:role/custodian-lambda-snapshot
```

But there is no log_group : 

> There was an error loading Log Streams. Please try again by refreshing this page.
