### ISSUE TITLE
encrypt-instance-volumes not working for periodic policies

### ISSUE THREAD

**Issue by aggallim** [capitalone/cloud-custodian#2953]
I'm trying to create a policy that encrypts all volumes, following the capone example here:
https://github.com/jtroberts83/Cloud-Custodian/blob/master/Policies/GenericExamples/CapitalOnesPolicyExamples.txt#L2004

I can run the policy locally at run-time successfully but it fails when running as a lambda.

```
Custodian version
0.8.30.0
```

My policy:

This works when executing at run-time locally:
```
policies:
   - name: ebs-encrypt-volumes-runtime
     description: |
       Encrypt all unencrypted EBS volumes - scheduled
     resource: ebs
     filters:
       - Encrypted: false
     actions:
       - type: encrypt-instance-volumes
         key: alias/aws/ebs
```

The equivalent policy when run as a lambda gives an error:
```
policies:
   - name: ebs-encrypt-volumes
     description: |
       Encrypt all unencrypted EBS volumes - scheduled
     resource: ebs
     mode:
        type: periodic
        schedule: "rate(1 hour)"
        timeout: 300
        role: arn:aws:iam::{account_id}:role/c7n-lambda-execution
     filters:
       - Encrypted: false
     actions:
       - type: encrypt-instance-volumes
         key: alias/aws/ebs
```
c7n-lambda-execution was given Administrator permissions to rule that out.

Error:
[ERROR]	2018-10-02T13:27:58.500Z	83080034-c646-11e8-a942-2b17602ef774	Exception processing instance:i-091280fea240cc3d6 volset: [{u'AvailabilityZone': 'eu-central-1b', u'Attachments': [{u'AttachTime': datetime.datetime(2018, 10, 2, 13, 18, 52, tzinfo=tzlocal()), u'InstanceId': 'i-091280fea240cc3d6', u'VolumeId': 'vol-01820a94e31c1dcd6', u'State': 'attached', u'DeleteOnTermination': True, u'Device': '/dev/xvda'}], u'Tags': [{u'Value': 'agallimore', u'Key': 'Owner'}, {u'Value': 'c7n-admin', u'Key': 'Name'}], u'Encrypted': False, u'VolumeType': 'gp2', u'VolumeId': 'vol-01820a94e31c1dcd6', u'c7n:MatchedFilters': [u'Encrypted'], u'State': 'in-use', u'Iops': 100, u'SnapshotId': 'snap-0774bfadb11c2f468', u'CreateTime': datetime.datetime(2018, 10, 2, 13, 18, 52, 249000, tzinfo=tzlocal()), u'Size': 8}] 
An error occurred (InvalidVolume.NotFound) when calling the DetachVolume operation: The volume 'vol-01820a94e31c1dcd6' does not exist.

Any ideas?
