### ISSUE TITLE
How to : Policy variables

### ISSUE THREAD

**Issue by tcanelas** [capitalone/cloud-custodian#2957]
I'm trying to figure out if it is possible to declare specific variables in policies, because i didn't find any documentation on this.
I can create a file containing my vars and i can use them in my filters like this:
```
vars:
  global-vars: &global file://../../global-vars.json
policies:
  - name: iam-role-modified
    resource: iam-role
    filters:
        - type: value
          key: "Path"
          op: eq
          value_from:
            url: *global
            format: json
            expr: var.rolename
```
But my problem is what if i want to use a regex op with my defined variable, like {var}.* ?
Is there another way to define vars in my policies ?
I think the documentation needs an update on this
