### ISSUE TITLE
aws.cfn doesn't register EnableTerminationProtection property

### ISSUE THREAD

**Issue by sshvetsov** [capitalone/cloud-custodian#2964]
It seems version **0.8.31.2** doesn't detect 'EnableTerminationProtection' property of the aws.cfn resources.

I'm trying to enable termination protection using this policy:
```
policies:
  - name: cfn-protection
    resource: cfn
    filters:
      - "tag:Environment": special
      - "tag:ManagedBy": stacksets
      - type: value
        key: StackStatus
        op: in
        value:
          - CREATE_COMPLETE
          - UPDATE_COMPLETE
      - type: value
        key: EnableTerminationProtection
        op: not-equal
        value: true
    actions:
      - type: set-protection
        state: True
```
And CloudFormation stacks are passing through filter even when termination protection is enabled. I also do not see the property 'EnableTerminationProtection' in the resources.json on any of the stacks.

Here's a sample from resources.json after running the policy:
```
{
    "StackId": "arn:aws:cloudformation:ap-southeast-1:XXXXXXXXXXXX:stack/StackSet-AWSConfig-b145e611-5e91-4d9e-a168-2fb0802d902a/5b1dcc60-c0a0-11e8-b05d-500c33716656",
    "Description": "Enables AWS Config recording",
    "Tags": [
      {
        "Value": "stacksets",
        "Key": "ManagedBy"
      },
      {
        "Value": "special",
        "Key": "Environment"
      }
    ],
    "CreationTime": "2018-09-25T08:52:39.225000+00:00",
    "c7n:MatchedFilters": [
      "tag:Environment",
      "tag:ManagedBy",
      "StackStatus",
      "EnableTerminationProtection"
    ],
    "StackName": "StackSet-AWSConfig-b145e611-5e91-4d9e-a168-2fb0802d902a",
    "NotificationARNs": [
      "arn:aws:sns:ap-southeast-1:080873435863:StackSet-AWSConfig-b145e611-5e91-4d9e-a168-2fb0802d902a"
    ],
    "StackStatus": "UPDATE_COMPLETE",
    "DisableRollback": false,
    "RollbackConfiguration": {},
    "LastUpdatedTime": "2018-10-07T06:12:49.067000+00:00"
}
```
And here's the same stack described using aws cli:
```
cloudformation describe-stacks --stack-name StackSet-AWSConfig-b145e611-5e91-4d9e-a168-2fb0802d902a
{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-1:XXXXXXXXXXXX:stack:stack/StackSet-AWSConfig-b145e611-5e91-4d9e-a168-2fb0802d902a/5b1dcc60-c0a0-11e8-b05d-500c33716656",
            "Description": "Enables AWS Config recording",
            "Tags": [
                {
                    "Value": "stacksets",
                    "Key": "ManagedBy"
                },
                {
                    "Value": "special",
                    "Key": "Environment"
                }
            ],
            "EnableTerminationProtection": true,
            "CreationTime": "2018-09-25T08:52:39.225Z",
            "StackName": "StackSet-AWSConfig-b145e611-5e91-4d9e-a168-2fb0802d902a",
            "NotificationARNs": [
                "arn:aws:sns:ap-southeast-1:080873435863:StackSet-AWSConfig-b145e611-5e91-4d9e-a168-2fb0802d902a"
            ],
            "StackStatus": "UPDATE_COMPLETE",
            "DisableRollback": false,
            "RollbackConfiguration": {},
            "LastUpdatedTime": "2018-10-07T06:12:49.067Z"
        }
    ]
}
```
It appears to me that 'EnableTerminationProtection' property is ignored when cfn stack is described and not recorded by custodian.
