### ISSUE TITLE
Bug in user-data example

### ISSUE THREAD

**Issue by ritesh** [capitalone/cloud-custodian#2968]
Trying the user-data filter from the example:

```
policies:
          - name: ec2_userdata_stop
            resource: ec2
            filters:
              - type: user-data
                op: regex
                value: (?smi).*password=
            actions:
              - stop
```

when I run `custodian validate` on the policy file,  I get:

```2018-10-08 16:11:35,729: custodian.commands:ERROR Policy: ec2_userdata_stop is invalid: Missing 'key' in value filter {'type': 'user-data', 'value': '(?smi).*password=', 'op': 'regex'```

```
$ custodian version
0.8.31.2
```
