### ISSUE TITLE
c7n: Elasticsearch resource returns output for AccessPolicies key that cannot be parsed using regex

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2978]
**Business Use Case**
An employee recently created an Elasticsearch (ES) domain with an [IP-based policy](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-ac.html#es-ac-types-ip )  (this is configured within the Elasticsearch management console for a selected domain under the "Modify access policy" button) that was too permissive. 

**Desired Outcome**
Generate an alarm when an ES access policy is found that does not match specific source IP addresses.  

**Problem Description**
It appears the returned output of the elasticsearch resource for the key `AccessPolicies` cannot be parsed using the regex operator in order to verify approved source IP addresses have been provisioned properly.

Consider the following policy used to extract all the key:value pairs for the `elasticsource` resource:
```
 policies:
  - name: elasticsearch_access_policies
    resource: elasticsearch
    description: |
      Cloud Custodian Elasticsearch
    comments: |
      Retrieve Elasticsearch Attributes
    filters:
      - type: value
        key: AccessPolicies
        op: regex
        value: .*
```

The output file results in something that looks like this (Note: The beginning section and AccessPolicies section have been retained to show output difference.  Account number and IP addresses have been made up for privacy and other misc sections truncated for brevity sake.):
```
$ more ./foo/elasticsearch_access_policies/resources.json
[
  {
    "ElasticsearchClusterConfig": {
      "DedicatedMasterEnabled": true,
      "InstanceCount": 2,
      "ZoneAwarenessEnabled": true,
      "DedicatedMasterType": "m4.large.elasticsearch",
      "InstanceType": "m4.large.elasticsearch",
      "DedicatedMasterCount": 3
...
    "AccessPolicies": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::12345:root\"},\"Action\
":\"es:*\",\"Resource\":\"arn:aws:es:us-east-1:12345:domain/cloud/*\"},{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::12345:role
/kubernetes-app-cloud-mdm-dashboard\",\"arn:aws:iam::12345:role/kubernetes-app-cloud-mdm-labeled-data\",\"arn:aws:iam::12345:role/cloud-jenkin
s\",\"arn:aws:iam::12345:role/kubernetes-app-cloud-mdm-issue-ingest-check\",\"arn:aws:iam::12345:role/kubernetes-app-cloud-mdm-fleetops\",\"ar
n:aws:iam::12345:role/kubernetes-app-cloud-mdm-skiiing\"]},\"Action\":\"es:*\",\"Resource\":\"arn:aws:es:us-east-1:12345:domain/cloud/*\"},{\"
Effect\":\"Allow\",\"Principal\":{\"AWS\":\"*\"},\"Action\":\"es:*\",\"Resource\":\"arn:aws:es:us-east-1:12345:domain/cloud/*\",\"Condition\":{\"IpAd
dress\":{\"aws:SourceIp\":[\"96.8.1.1\",\"50.2.7.19\",\"12.15.6.3\",\"50.2.23.4/30\",\"50.2.2.1/29\",\"52.8.13.16\",\"108.6.26.2\"]
}}}]}"
  },
  {
    "ElasticsearchClusterConfig": {
      "DedicatedMasterEnabled": false,
      "InstanceCount": 1,
      "ZoneAwarenessEnabled": false,
      "InstanceType": "m4.large.elasticsearch"
    },
...
```

Now when we modify the policy to filter against an IP address, the regular expression returns no matches:
```
 policies:
  - name: elasticsearch_access_policies
    resource: elasticsearch
    description: |
      Cloud Custodian Elasticsearch
    comments: |
      Retrieve Elasticsearch Attributes
    filters:
      - type: value
        key: AccessPolicies
        op: regex
        value: "12.15.6.3"   
```

```
(c7n_mailer) $ custodian run -s foo elasticsearch.yml
2018-10-10 20:24:30,219: custodian.policy:INFO policy: elasticsearch_access_policies resource:elasticsearch region:us-east-1 count:0 time:0.77
```
It appears the output for `AccessPolicies` is a string but the string contains sub-strings making it challenging to parse against using regex.  

Ideally, it would be nice to get keys for `AccessPolicies` to filter against. 
For example, maybe `AccessPolicies[0].aws:SourceIp` but any other approach is fine for the moment.

**Comment by davidclin** [comment]
Issue resolved using greedy match pattern.

Working policy:
```
policies:
  - name: elasticsearch_security_audit
    resource: elasticsearch
    description: |
      Cloud Custodian Elasticsearch Security Audit
    comments: |
      Periodically check PUBLIC ES domains that have
      access policies that are too permissive.
      Ignore PRIVATE ES domains.
      PRIVATE domains will have VPCOptions configured.
      PUBLIC  domains will have AccessApolicies configured.
    filters:
      - type: value
        key: VPCOptions
        value: null
      - or:
        - not:
          - type: value
            key: AccessPolicies
            op: regex
            value: .*Condition.*
        - type: value
          key: AccessPolicies
          op: regex
          value: .*0.0.0.0/0.*
```
