### ISSUE TITLE
Error validating example policy

### ISSUE THREAD

**Issue by DenverJ** [capitalone/cloud-custodian#30]
Using the first policy from the Usage section on the project page fails with the following error. Have I missed something?

**Policy**
```yaml
policies:
 - name: remediate-extant-keys
   description: |
     Scan through all s3 buckets in an account and ensure all objects
     are encrypted (default to AES256).
   resources: s3
   actions:
     - encrypt-keys
```
**Output**
```console
# custodian validate -c policy.yml
Traceback (most recent call last):
  File "C:/Dev/Projects/virtual_envs/cloud_custodian/Scripts/custodian-script.py", line 9, in <module>
    load_entry_point('c7n==0.8.3', 'console_scripts', 'custodian')()
  File "C:\Dev\Projects\github\cloud-custodian\c7n\cli.py", line 105, in main
    config = policy.load(options, options.config)
  File "C:\Dev\Projects\github\cloud-custodian\c7n\policy.py", line 45, in load
    raise errors[0]
jsonschema.exceptions.ValidationError: {'resources': 's3', 'name': 'remediate-extant-keys', 'actions': ['encrypt-keys'], 'description': 'Scan through all s3 buckets in an account and ensure all objects\nare encrypted (default to AES256).\n'} is not valid under any of the given schemas

Failed validating 'anyOf' in schema['properties']['policies']['items']:
    {'anyOf': [{'$ref': '#/definitions/resources/ami/policy'},
               {'$ref': '#/definitions/resources/rds/policy'},
               {'$ref': '#/definitions/resources/redshift/policy'},
               {'$ref': '#/definitions/resources/elb/policy'},
               {'$ref': '#/definitions/resources/s3/policy'},
               {'$ref': '#/definitions/resources/asg/policy'},
               {'$ref': '#/definitions/resources/ec2/policy'},
               {'$ref': '#/definitions/resources/ebs/policy'},
               {'$ref': '#/definitions/resources/kms/policy'},
               {'$ref': '#/definitions/resources/ebs-snapshot/policy'}]}

On instance['policies'][0]:
    {'actions': ['encrypt-keys'],
     'description': 'Scan through all s3 buckets in an account and ensure all objects\nare encrypted (default to AES256).\n',
     'name': 'remediate-extant-keys',
     'resources': 's3'}
````
