### ISSUE TITLE
Add support for Delete events

### ISSUE THREAD

**Issue by tcanelas** [capitalone/cloud-custodian#3065]
Actually, in cloudtrail mode, c7n doesn't support Delete events, because the lambda function looks for the resources and returns nothing (obviously it is deleted).
So it is not possible (using c7n) to have a simple policy notifying on resource deletion.
It can be nice to add a possibility of disabling resource checking for Delete events, instead of having part of the rules in custom code.
Is there smthg like this in your roadmap ?

**Comment by kapilt** [comment]
the missing filter on the account can be used for delete events on resources, you don't have access to the resource description outside of the event itself.

**Comment by tcanelas** [comment]
It "works" just by changing the resource type to account, but that's not clean.
I tried to use the missing filter based on your example in this issue https://github.com/capitalone/cloud-custodian/issues/1517#issuecomment-326025454
When i do that, it filters on all the log groups i have in the account/region, not on the event received

Here is my original policy:
```
- name: delete-loggroup
    resource: log-group
    filters:
      - and:
        - type: event
          key: "detail.userIdentity.sessionContext.sessionIssuer.arn"
          op: ne
          value: {var:rolearn}
        - or:
          - type: event
            key: "detail.requestParameters.logGroupName"
            value: "/aws/lambda/{var:prefix}.*"
            op: regex
          - type: event
            key: "detail.requestParameters.logGroupName"
            value: "/{var:prefix}/.*"
            op: regex
    mode:
      function-prefix: {var:prefix}
      type: cloudtrail
      role: {var:rolearn}
      events:
        - source: logs.amazonaws.com
          event: DeleteLogGroup
          ids: requestParameters.logGroupName
    description: {var:description}
    actions:
      - type: invoke-lambda
        function: {var:notifier_function}
```
