### ISSUE TITLE
Feature Request - c7n-org allow accounts to be specified in policy

### ISSUE THREAD

**Issue by rbowlby** [capitalone/cloud-custodian#3069]
Currently a list of accounts to apply a given policy to is specified as an arg to c7n-org. We have 20+ accounts and 20+ policies that are applied to a subset of those accounts. If we could specify the accounts to apply a given policy to within the policy file that would be tremendously helpful.

**Comment by kapilt** [comment]
so the scenario I think is a set of accounts in an accounts.yml file, a set of policies in a policy.yml file, and wanting to run a subset of policies against a subset of accounts. the c7n-org cli allows account filtering by name/account_id/tag, but at the moment the policy subset requires splitting out the policy subsets to separate files. an enhancement would be to allow filtering the policies to be executed as well when running, ideally via policy name or tag.

[update] - as I went to look into this, afaics we already support it. ie you can specify a policy subset by name using `-p` or policy tag with `-l`

**Comment by rbowlby** [comment]
What I was hoping for is some way to specify the accounts in the accounts.yml in-line within the policy:

```
policies:
  - name: ec2-missing-email-tag-mark-for-stop
    resource: ec2
    comment: |
       Alert and mark EC2 instances missing email tag for future stop in 5 days.
    accounts:
      - "non-prod"
      - "prod"
    filters:
      - "State.Name": running
      - "tag:aws:autoscaling:groupName": absent
      - "tag:Email": absent
      - type: instance-age
        hours: 1
    actions:
      - type: mark-for-op
        tag: missing-email-tag
        op: stop
        days: 5
      - type: notify
        template: mail.html
        subject: AWS Policy Alerts - EC2 Email Tag Missing
        violation_desc: |
            These EC2 instances are missing the Email tag and will be stopped in 5 days.
        to:
          - redacted@email.com
```
