### ISSUE TITLE
Azure - C7n-Mailer - Email Fails to Send using 'resource-owner' and 'Owner_absent_contact '

### ISSUE THREAD

**Issue by jdogg89** [capitalone/cloud-custodian#3089]
### Description: 
Trying to send an email without a hard coded email address in the policy results with no email being sent. When specifying 'resource-owner', which should tie to the 'OwnerContact' tag to a specified email, an empty dictionary is returned (which I assume is what custodian mailer defaults to). It also appears that 'owner_absent_contact' also does not get notified. When reverting back to a hard coded email address in the 'to' field, email resumes
### Policy: 
```
policies:
  - name: azure-notify
    resource: azure.resourcegroup
    description: example policy
    actions:
      - type: notify
        template: default
        priority_header: '2'
        subject: Hello from C7N Mailer
        to:
          - resource-owner
        owner_absent_contact:
          - me@me.com
        transport:
          type: asq
          queue: https://myblob.queue.core.windows.net/taskqueue
```
### terminal output:
```
2018-11-01 20:02:32,792 - custodian-mailer - INFO - Sending account:XXXX policy:azure-notify azure.resourcegroup:7 email:default to {}
```

**Comment by aluong** [comment]
You should be able to specify `tag: OwnerContact`

**Comment by jdogg89** [comment]
#### update:
@aluong @stefangordon @logachev @erwelch 
The function : get_email_to_addrs_to_resources_map"in sendgrid_delivery.py, appears to be sending an empty object to utils_email.py, or the first 'if' block in the is_email function in utils_email.py is causing the ability to send emails via 'tag' not to work:
```
File "/usr/local/lib/python3.6/site-packages/c7n_mailer/utils_email.py", line 8, in is_email
if target.startswith('slack://'):
AttributeError: 'NoneType' object has no attribute 'startswith'
2018-11-02 12:07:13,851 - custodian-mailer - INFO - No messages left on the azure storage queue, exiting c7n_mailer.
```
working policy:
```
policies:

  policies:
  - name: azure-notify
    resource: azure.resourcegroup
    description: example policy
    actions:
      - type: notify
        template: default
        priority_header: '2'
        subject: hello from the mailer
        to:
          - tag:OwnerContact
        transport:
          type: asq
          queue: https://myblob.queue.core.windows.net/taskqueue

```


I commented out lines 8-10 in the is_email functions and sendgrid is able to send emails via tags for Azure. I'll put this in the issue, I know this doesnt help with support of using slack webhooks but how it currently sits its nerfing some email delivery functionality. 

Based on "target.startswith('slack://" I'm guessing slack with API keys is the only currently supported slack output based on the other slack deliver options?
