### ISSUE TITLE
Azure - Custom pyformat in output_dir - {policy} variable is expanded as policy instead of policy name

### ISSUE THREAD

**Issue by billpratt** [capitalone/cloud-custodian#3091]
I'm trying to use the built in pyformat feature to add the subscription id in the output path for each policy run log using 
```azure://<storage-account-name>.blob.core.windows.net/custodianlogs/{account_id}/{policy}/{now:%Y/%m/%d/%H/}```.

**Note**: In all examples, I replaced my actual storage account name with `<storage-account-name>`

When using this format, {account_id} is replaced with the subscription id however, {policy} is not the policy name but instead the entire policy json.

```
"output_dir": "azure://<storage-account-name>.blob.core.windows.net/custodianlogs/00000000-0000-0000-0000-000000/{'name': 'rg-find-empty', 'description': 'Find any empty resource groups from subscription\\n', 'resource': 'azure.resourcegroup', 'mode': {'type': 'azure-periodic', 'schedule': '0 30 9 * * *', 'provision-options': {'servicePlan': {'name': 'custodian', 'skuTier': 'Basic', 'skuName': 'B2', 'resourceGroupName': 'custodian'}}, 'execution-options': {'output_dir': 'azure://<storage-account-name>.blob.core.windows.net/custodianlogs/{account_id}/{policy}/{now:%Y/%m/%d/%H/}'}}, 'filters': [{'type': 'empty-group'}]}/2018/11/01/23/"
```

I also noticed that `/2018/11/01/23/` is hard-coded in the output_dir path now instead of `{now:%Y/%m/%d/%H/}`

## Example
```yaml
policies:
    - name: rg-find-empty
      description: |
        Find any empty resource groups from subscription
      resource: azure.resourcegroup
      mode:
        type: azure-periodic
        schedule: '0 30 9 * * *'
        provision-options:
          servicePlan:
            name: custodian
            skuTier: Basic
            skuName: B2
            resourceGroupName: custodian
        execution-options:
          output_dir: azure://<storage-account-name>.blob.core.windows.net/custodianlogs/{account_id}/{policy}/{now:%Y/%m/%d/%H/}
      filters:
        - type: empty-group
```

## config.json output
```json
{
  "policies": [
    {
      "name": "rg-find-empty",
      "description": "Find any empty resource groups from subscription\n",
      "resource": "azure.resourcegroup",
      "mode": {
        "type": "azure-periodic",
        "schedule": "0 30 9 * * *",
        "provision-options": {
          "servicePlan": {
            "name": "custodian",
            "skuTier": "Basic",
            "skuName": "B2",
            "resourceGroupName": "custodian"
          }
        },
        "execution-options": {
          "output_dir": "azure://<storage-account-name>.blob.core.windows.net/custodianlogs/00000000-0000-0000-0000-000000/{'name': 'rg-find-empty', 'description': 'Find any empty resource groups from subscription\\n', 'resource': 'azure.resourcegroup', 'mode': {'type': 'azure-periodic', 'schedule': '0 30 9 * * *', 'provision-options': {'servicePlan': {'name': 'custodian', 'skuTier': 'Basic', 'skuName': 'B2', 'resourceGroupName': 'custodian'}}, 'execution-options': {'output_dir': 'azure://<storage-account-name>.blob.core.windows.net/custodianlogs/{account_id}/{policy}/{now:%Y/%m/%d/%H/}'}}, 'filters': [{'type': 'empty-group'}]}/2018/11/01/23/"
        }
      },
      "filters": [
        {
          "type": "empty-group"
        }
      ]
    }
  ]
}
```

/cc @stefangordon @aluong @noelbundick
