### ISSUE TITLE
Group filter returns no results

### ISSUE THREAD

**Issue by Ashex** [capitalone/cloud-custodian#3094]
The following policy returns no resources despite a user being a member of the group:

```yaml
   - name: iam-user-delete
     comment: |
       Delete Users in specific group 
     resource: iam-user
     filters:
       - type: group
         key: GroupName
         value: InactiveUsers
```

Output of a run:

```
2018-11-02 12:13:41,351: custodian.policy:INFO policy: iam-user-delete resource:iam-user region:us-east-1 count:0 time:0.45
```

The user in question was created with no login profile or access keys.

The resources file from the run is also empty.

Custodian 0.8.31.0
CentOS release 6.9
