### ISSUE TITLE
Feed one filter into another policy

### ISSUE THREAD

**Issue by steveparker-1984** [capitalone/cloud-custodian#3173]
I want to query for AMIs that are missing a certain tag, and then use the resulting AMIs to find running instances. Is this possible?

**Comment by kapilt** [comment]
```
policies:
   - name: ec2-instances-with-ami
      resource: ec2
      filters:
         - type: image
            key: "tag:Foo"
            value: absent
```
