### ISSUE TITLE
AWS c7n.resources.appelb.AppELBListenerFilter object is not in list

### ISSUE THREAD

**Issue by 1FastSTi** [capitalone/cloud-custodian#3195]
0.8.32.1 introduces a problem that 0.8.32.0 did not have, and I'm not sure what is occurring.

`<c7n.resources.appelb.AppELBListenerFilter object at 0x7f22eed29610> is not in list`

Minimal policy to reproduce issue with a `custodian run --dryrun --cache-period 0 x.yml`:
```yml
policies:
  - name: alb-http-listeners-redirect
    resource: aws.app-elb
    mode:
      type: periodic
      schedule: "rate(5 minutes)"
    filters:
      - and:
        - type: listener
          key: Protocol
          value: HTTP
        - type: listener
          key: DefaultActions[*].Type
          op: ni
          value_type: swap
          value: redirect
          matched: true
```

**Comment by kapilt** [comment]
thanks for the bug report, working on it now.

There was a fix in 0.8.32.1 for ensuring that validate was called even in nested filters of a boolean group. It looks like in this case, the validate for the listener filter implementation wasnt expected the nesting either.

btw. the default behavior for filters is `and`,  iotw, the following would work and not trigger the issue.

```
policies:
  - name: alb-http-listeners-redirect
    resource: aws.app-elb
    mode:
      type: periodic
      schedule: "rate(5 minutes)"
    filters:
        - type: listener
          key: Protocol
          value: HTTP
        - type: listener
          key: DefaultActions[*].Type
          op: ni
          value_type: swap
          value: redirect
          matched: true
```
