### ISSUE TITLE
EBS resource issue - encrypt-instance-volumes, Index error

### ISSUE THREAD

**Issue by mukavik** [capitalone/cloud-custodian#3200]
I am getting the following error when using the C7N action - encrypt-instance-volumes
Custodian version - 0.8.31.2
**Traceback:**
Traceback (most recent call last):
File "/var/task/c7n/policy.py", line 273, in run
results = a.process(resources)
File "/var/task/c7n/resources/ebs.py", line 798, in process
instance_id = v['Attachments'][0]['InstanceId']
IndexError: list index out of range

**Policy:**
```
policies:
   - name: terminate-unattached-unencrypted-ebs-periodic
     description: |
       Terminate all unattached, unencrypted EBS volumes upon creation
     resource: ebs
     mode:
      execution-options:
        log_group: /aws/terminate-unattached-unencrypted-ebs/resources
      role: arn:aws:iam::{account_id}:role/CloudCustodianExecutionRole
      type: cloudtrail
      type: periodic
      schedule: rate(1 minute)
     filters:
       - Encrypted: false
     actions:
       - type: encrypt-instance-volumes
         key: alias/encrypted
```

**Comment by kapilt** [comment]
encrypt-instance-volumes was really intended for one off migrations, its not really suitable to a lambda execution, as it has to orchestrate a complex workflow (and requires bringing down an instance to patch volumes etc) that time wise is O(n) on size of volume.

wrt to the error in question is because you need to filter out unattached volumes.

**Comment by mukavik** [comment]
Once i filter out unattached volumes I get a different error which i see was reported in issue # 2886. I using custodian version 0.8.31.2.
**Traceback:**
[ERROR]	2018-12-04T21:58:00.897Z	a9d9c830-f80f-11e8-91dc-2fda8a271717	Exception processing instance:i-0fc332aba204fcaeb volset: [{u'AvailabilityZone': 'us-east-1c', u'Attachments': [{u'AttachTime': datetime.datetime(2018, 12, 3, 16, 52, 58, tzinfo=tzlocal()), u'InstanceId': 'i-0fc332aba204fcaeb', u'VolumeId': 'vol-07c2c9c88ee810be0', u'State': 'attached', u'DeleteOnTermination': True, u'Device': '/dev/xvda'}], u'Encrypted': False, u'VolumeType': 'gp2', u'VolumeId': 'vol-07c2c9c88ee810be0', u'c7n:MatchedFilters': [u'Attachments', u'State', u'Encrypted'], u'State': 'in-use', u'Iops': 100, u'SnapshotId': 'snap-05c184ed39d0ecd7b', u'CreateTime': datetime.datetime(2018, 12, 3, 16, 52, 58, 71000, tzinfo=tzlocal()), u'Size': 8}, {u'AvailabilityZone': 'us-east-1c', u'Attachments': [{u'AttachTime': datetime.datetime(2018, 12, 3, 16, 52, 58, tzinfo=tzlocal()), u'InstanceId': 'i-0fc332aba204fcaeb', u'VolumeId': 'vol-08530f7d3bed7e611', u'State': 'attached', u'DeleteOnTermination': False, u'Device': '/dev/sdb'}], u'Encrypted': False, u'VolumeType': 'gp2', u'VolumeId': 'vol-08530f7d3bed7e611', u'c7n:MatchedFilters': [u'Attachments', u'State', u'Encrypted'], u'State': 'in-use', u'Iops': 100, u'SnapshotId': '', u'CreateTime': datetime.datetime(2018, 12, 3, 16, 52, 58, 164000, tzinfo=tzlocal()), u'Size': 8}] 
'EncryptInstanceVolumes' object has no attribute 'verbose'

**Policy:**
```
policies:
   - name: notify-unencrypted-ebs-cloudtrail
     description: |
       Notify on unencrypted EBS volumes upon creation
     resource: ebs
     mode:
      execution-options:
        log_group: /aws/notify-unencrypted-ebs/resources
      role: arn:aws:iam::{account_id}:role/CloudCustodianExecutionRole
      type: periodic
      schedule: rate(1 minute)
     filters:
       - type: value
         key: Attachments
         op: ne
         value: []
       - type: value
         key: State
         op: eq
         value: "in-use"
       - Encrypted: false
     actions:
       - type: encrypt-instance-volumes
         key: alias/ebsencryption
```
