### ISSUE TITLE
put metric action

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#400]
for given expression evaluate and publish per resource metric for given attribute, or the collection's aggregate attributes (size, etc).

**Comment by calvinhp** [comment]
Are you envisioning something like this:

```yaml
policies:
  - name: track-bucket-size
    resource: s3
    comment: |
      Put the sum of the size of all keys in an S3 bucket into CloudWatch Metrics
    filter:
      - Name: metric-tracked-bucket
    actions:
      - type: put-metric
        key: Contents[].Size
        metric_name: Bucket Size
        op: sum
```

Or something like this:

```yaml
  - name: track-attached-ebs
    resource: ec2
    comment: |
      Put the count of the number of EBS attached disks to an instance
    filter:
      - Name: tracked-ec2-instance
    actions:
      - type: put-metric
        key: Reservations[].Instances[].BlockDeviceMappings[].DeviceName
        metric_name: Attached Disks
        op: count
```

The action can figure out based on the resource, operation and the key handed to it what to put into CloudWatch.

Operations could be:

* count
* sum
* average
* duration (is this even possible?)
