### ISSUE TITLE
S3 policy does not work in periodic mode

### ISSUE THREAD

**Issue by rowanu** [capitalone/cloud-custodian#505]
I'm trying to run a policy against S3 periodically (i.e. daily), but keep getting an error.

Is this supported, or am I doing it wrong?

My policy is:

```yaml
policies:
  - name: s3_no_global_access
    resource: s3
    description: |
      Do not allow global ACLs on buckets
    mode:
      type: periodic
      schedule: rate(1 day)
      role: arn:aws:iam::XXX:role/CustodianPolicyRole
    filters:
      - type: global-grants
    actions:
      - type: no-op
```

When the policy runs, I get this error:

```
run() takes exactly 1 argument (3 given): TypeError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 74, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 434, in push
return mode.run(event, lambda_ctx)
TypeError: run() takes exactly 1 argument (3 given)
```

The event payload that the policy is triggered with is:

```json
{
    "account": "XXX",
    "region": "ap-southeast-2",
    "detail": {},
    "detail-type": "Scheduled Event",
    "source": "aws.events",
    "version": "0",
    "time": "2016-10-11T05:19:59Z",
    "debug": true,
    "id": "XXX",
    "resources": [
        "arn:aws:events:ap-southeast-2:XXX:rule/custodian-s3_no_global_access"
    ]
}
```

Looking at the code, this is because the event payload doesn't have any resources in it, but I want it to check _all_ buckets anyways so I'm hoping this is just my configuration issue. I have configured the same policy to work with CloudTrail events, and it works (because each event payload has bucket names in it).
