### ISSUE TITLE
Security Group filter "default-vpc" does not function correctly.

### ISSUE THREAD

**Issue by aiell0** [capitalone/cloud-custodian#552]
Using the following policy:

```
policies:
  - name: default-sg-allows-all-traffic
    description: |
      Find whether the default security group allows all traffic.
    resource: security-group
    filters:
       - type: default-vpc
```

Comes up with no results, even when I have confirmed that my account has a default vpc and a default security group associated with it.
