### ISSUE TITLE
Ability to add a lifecycle policy to an S3 bucket

### ISSUE THREAD

**Issue by tim-elliott** [capitalone/cloud-custodian#559]
Especially on versioned buckets, there is a need to be able to apply a default lifecycle policy so that items aren't kept forever.

**Comment by kapilt** [comment]
Any thoughts on what syntax would look like, i was looking over the lifecycle parameters and its pretty open-ended

http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.put_bucket_lifecycle_configuration

**Comment by kapilt** [comment]
@tim-elliott any thoughts on usage scenarios/example policies.

**Comment by tim-elliott** [comment]
@kapilt For usage, we would like to be able to put a default lifecycle policy on any bucket that is created as or becomes versioned so that old versions won't live forever.  Another use case we would like to enforce is expiration on log buckets.  In either case i would see the policy being something like

```
{
  "Rules": [
    {
      "ID": "default-retention-policy",
      "Status": "Enabled",
      "Expiration": {
        "Days": 60
        "ExpiredObjectDeleteMarker": false
      },
      "NoncurrentVersionExpiration": {
          "NoncurrentDays": 60
      }
    }
  ]
}
```

As for syntax, for this policy it could be something like:
```
actions:
  - type: lifecycle
  - id: default-retention-policy
  - expire-days: 60
  - expire-obj-del-marker: false
  - noncur-expire-days: 60
```
And in general:
```
actions:
  - type: lifecycle
  # probably must-haves (though I only care about expire options):
  - id: <string>
  - prefix <string>
  - expire-days: <num-days>
  - expire-obj-del-marker: <true|false>
  - noncur-expire-days: <num-days>
  - abort-multipart-days: <num-days>
  - trans-days: <num-days>
  - trans-type: <GLACIER|STANDARD_IA>
  - non-curr-trans-days: <num-days>
  - noncurr-trans-type: <GLACIER|STANDARD_IA>
  # can live without:
  - expire-date: <yyyy-mm-dd>
  - trans-date: <yyyy-mm-dd>
```

Custodian shouldn't attempt to check the rationality of the policy parms, that is up to the user.  If if fails to apply it is on the user to catch it and fix it.
