### ISSUE TITLE
policy resource (meta)

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#614]
we'd like to use custodian filters to query and filter policies. ie write a policy to filter and find other policies that match criteria. we'll need to do something funky with the query section as we'll want to pull other files/urls for the policies we want to query/match against. note this query abstraction dove tails with the abstractions nesc for config as query source issue.

**Comment by thisisshi** [comment]
coincidentally i've been working on this with this type of syntax, similar to the way crds are defined in c7n_k8s

```yaml
policies:
  - name: find-policies-with-max-resources
    resource: c7n.policy
    query:
      - location: s3
        source: s3-bucket-name
        path: prefix/policy.yml
    filters:
        - max-resources: present
```

location would be one of `azure`, `http`, `https`, `gcp`, `s3` etc.
