### ISSUE TITLE
type_schema does not register required properties.

### ISSUE THREAD

**Issue by aiell0** [capitalone/cloud-custodian#671]
I am using the type_schema method to handle when a user doesn't put in a proper variable into a filter. I find that it works for most things, except this one case. Here's an example using the `type: value` filter that is core to all users.

Here is the policy:

```
  - name: name
    description: |
      something
    resource: iam-user
    filters:
      - type: value
```

This policy runs fine, even though `key` and `value` are required for this filter to work correctly. However, let's switch it to this:
```
  - name: name
    description: |
      something
    resource: iam-user
    filters:
      - type: value
      - key: key
```

Running that policy will correctly produce an error stating that the `value` property is missing.
