### ISSUE TITLE
ebs piops metric filtering

### ISSUE THREAD

**Issue by ocampocj** [capitalone/cloud-custodian#808]
@kapilt - Currently, there's no way to easily filter provisioned IOPS (PIOPS) volumes that are underused with Custodian.  We should have a filter that allows us to set a threshold for the 'VolumeConsumedReadWriteOps' metric and return volumes that come in below that threshold.  The problem with using 'VolumeConsumedReadWriteOps', is that the metric is a 'Count' metric.  It looks like the denominator needed to calculate the percentage used varies per volume.  Thoughts?

example policy

  - name: under-utilized-piops
    resource: ebs
    filters:
      - type: under-utilized-piops
        threshold: 50
        op: lt
    actions:
      - notify

**Comment by kapilt** [comment]
make sense, i'm wondering if we can extend the extant metrics filter syntax in a way that we could add calculations against the resource attribute. the proposed syntax in your example is very specific to a given metric and resource type, where as this seems like a common scenario for cost optimization of verifying reserved utilization.

**Comment by ocampocj** [comment]
Modifying the metrics filter sounds like a similar effort to just creating this one filter for piops, so it may very well be worth it.

**Comment by kapilt** [comment]
i guess the question is what would it look like on the metrics filter here's a sketch, suggestions welcome

```
name: underutilized-provisioned
resource: ebs
filters:
  - VolumeType: io1
  - type: metric
     name: VolumeConsumedReadWriteOps
     op: less-than
     value: 60
     period: 7
     # need to specify conversion and resource attribute to use.
     value_type: percent
     value_attr: Iops
```
