### ISSUE TITLE
match-annotation parameter for modify-security-groups action

### ISSUE THREAD

**Issue by andrewalexander** [capitalone/cloud-custodian#839]
Specific use case this could be used for is trying to match tags on security group to tags on a subnet for automatic enforcement.  

At the moment, we can do a `match-resource` for a subnet or security group type filter on an arbitrary tag, but when run against an ec2 resource, the `match-resource` compares tags on the ec2 with tags on the subnet or security group.

Ideal syntax would be something more akin to:
```
- type: security-group
   key: tag:SubnetType
   value: not-null
   match-annotation: subnet
```
This would (in theory) take the extant `subnet` type filter and allow it to be referenced under the match-annotation, allowing us to match the `tag:SubnetType` on both the SG and the subnet associated with the resource in question.

**Comment by kapilt** [comment]
i think we probably can do this as a more generic match-attribute syntax with some value interpolation (prefix match) for annotations like we do for resource tags.

**Comment by andrewalexander** [comment]
I think we can simplify this by swapping the match-resource from a boolean into a selector of resource type. I think it should inherit from all related resources. So since ec2 has security-group, subnet, and other related resources that are exposed in the filters, it should be more or less internal references. 

Sample syntax
```
policies:
  - name: test-ec2-sg-subnet-matching
    resource: ec2
    filters:
      - type: security-group
        key: tag:SubnetType
        value: not-null
        match-resource: self | subnet | security-group | etc
```

**Comment by andrewalexander** [comment]
How about this for usage/policy syntax instead? More of your match-attributes. Unsure of whether we need a new `value_type` type for simplicity on the checking of the contents of `value` but that sounds like a code review kind of decision.

Target state would be to have a few more keywords like `tag:` in the `value` field that can be matched across resources. Use case/example below _should_ take the SubnetId that the ec2 is residing in and then compare its `SubnetType` tag to EC2's attached security groups' `SubnetType` tags. 
```
policies:
  - name: test-ec2-sg-subnet-matching
    resource: ec2
    filters:
      - type: security-group                     
        key: tag:SubnetType     # attribute to match
        resource: SubnetId      # Resource ID or JMESPath expression from ec2 resource
        op: ne                  # match if the tags aren't equal, i.e. the security group doesn't belong in this subnet
        value-type: match-resource-attribute      
```
