### ISSUE TITLE
force auto-tag-user

### ISSUE THREAD

**Issue by barundel** [capitalone/cloud-custodian#863]
Hello

Have a small issue where auto-tag-user doesn't update the tag if it's empty or contains another value. It will work if the tag is not present on the instance. 

I'm trying to write a policy that covers the event of a tag being deleted via the console which doesn't completely remove the tag just makes it null. 

```
policies:
 - name: tag-owner-policy
   resource: ec2
   mode:
     type: cloudtrail
     events:
       - source: ec2.amazonaws.com
         event: StartInstances
         ids: "responseElements.instancesSet.items[].instanceId"
       - source: ec2.amazonaws.com
         event: RunInstances
         ids: "responseElements.instancesSet.items[].instanceId"
       - source: ec2.amazonaws.com
         event: RebootInstances
         ids: "responseElements.instancesSet.items[].instanceId"
     role: arn:aws:iam::number:role/lambda
   filters:
   - or:
     - "tag:Owner": empty
     - "tag:Name": empty
     - "tag:Role": empty
     - "tag:Contact": empty
     - "tag:Project": empty
     - "tag:Team": empty
   actions:
   - type: tag
     key: Notice
     value: Missing-Required-Tag
   - type: auto-tag-user
     tag: Owner
```

This always works for the tag action but only works for the auto-tag-user when the Owner tag is not present. 

Is this the correct behaviour and if so is there any way to get it to function as the tag action?
