### ISSUE TITLE
When deploying RDS and S3 Buckets for tag compliance as AWS config rules, all resources are being included in the filter

### ISSUE THREAD

**Issue by caversa** [capitalone/cloud-custodian#879]
I believe this is related to https://github.com/capitalone/cloud-custodian/issues/801 but I wanted to report this as well, because it has serious implications.

If I run a tagging compliance policy for RDS and S3 buckets via dryrun mode AND explicitly pass in the region, I get the correct results.  However, if I deploy the policy as an AWS config rule, every one of my S3 and RDS resources seems to be included as non-compliant, even when I'm passing in region at the command line.  Fortunately, I did not have any actions enabled (we'll be deleting them once this is filtering properly).

Here are the policies:

```
- name: rds-tag-compliance
  resource: rds
  description:
    Terminate an RDS through a config rule
    if it does not comply with tagging best practices.
    The instance will be terminated within 15 minutes.
  mode:
      type: config-rule
  filters:
    - "tag:CostCenter": absent

- name: s3-tag-compliance
  resource: s3
  description:
    Terminate an S3 through a config rule
    if it does not comply with tagging best practices.
    The instance will be terminated within 15 minutes.
  mode:
      type: config-rule
  filters:
    - "tag:CostCenter": absent
```
