### ISSUE TITLE
filter on tag name - EBS Snapshots

### ISSUE THREAD

**Issue by willjgillen** [capitalone/cloud-custodian#920]
Is it possible to filter on EBS Snapshot names?  I want to delete based on age but also only specific name patterns (or regex matching).
thank you

**Comment by kapilt** [comment]
the value filter covers these use cases.

```
policies:
 - name: snap-delete
    resource: ebs-snapshot
    filters:
      - or:
         # key=value shortcut for type: value filter, supports tags
         - "tag:Name": "myvol"
         # Alternative full spelling with regex
         - type: value
            key: "tag:Name"
            value: "my*"
            op: regex 
```
