### ISSUE TITLE
emr set default server side query to (waiting, bootstrapping, running)

### ISSUE THREAD

**Issue by fathre2** [capitalone/cloud-custodian#978]
Policy looks like so
  - name: weekend_emr_terminate
    resource: emr
    comments:
      weekend emr termination
    filters:
      - "tag:custodian_opt_out": absent
      - "ClusterStates": waiting
    actions:
      - terminate

Getting a throttling exception

ClientError: An error occurred (ThrottlingException) when calling the DescribeCluster operation (reached max retries: 4): Rate exceeded
2017-02-23 12:54:56,986: custodian.commands:ERROR Error while executing policy weekend_emr_terminate, continuing

**Comment by kapilt** [comment]
emr keeps full history, so its important to use a server side query filter. we should probably make this a default (for pending, waiting, running).

```
  - name: weekend_emr_terminate
    resource: emr
    comments:
      weekend emr termination
    query:
      ClusterStates: 
         - waiting
    filters:
      - "tag:custodian_opt_out": absent
    actions:
      - terminate
```
